/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgeVerificationStatusResponse,
  ConfirmAgeVerificationRequest,
  ConfirmAgeVerificationResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AgeVerificationStatusResponseFromJSON,
    AgeVerificationStatusResponseToJSON,
    ConfirmAgeVerificationRequestFromJSON,
    ConfirmAgeVerificationRequestToJSON,
    ConfirmAgeVerificationResponseFromJSON,
    ConfirmAgeVerificationResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ConfirmAgeVerificationConfirmPostRequest {
    confirmAgeVerificationRequest: ConfirmAgeVerificationRequest;
}

/**
 * 
 */
export class AgeVerificationApi extends runtime.BaseAPI {

    /**
     * Callback
     */
    async callbackAgeVerificationCallbackPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/age-verification/callback/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Callback
     */
    async callbackAgeVerificationCallbackPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.callbackAgeVerificationCallbackPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Confirm
     */
    async confirmAgeVerificationConfirmPostRaw(requestParameters: ConfirmAgeVerificationConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmAgeVerificationResponse>> {
        if (requestParameters['confirmAgeVerificationRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmAgeVerificationRequest',
                'Required parameter "confirmAgeVerificationRequest" was null or undefined when calling confirmAgeVerificationConfirmPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/age-verification/confirm/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmAgeVerificationRequestToJSON(requestParameters['confirmAgeVerificationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmAgeVerificationResponseFromJSON(jsonValue));
    }

    /**
     * Confirm
     */
    async confirmAgeVerificationConfirmPost(requestParameters: ConfirmAgeVerificationConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmAgeVerificationResponse> {
        const response = await this.confirmAgeVerificationConfirmPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Status
     */
    async getStatusAgeVerificationStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgeVerificationStatusResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/age-verification/status/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgeVerificationStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get Status
     */
    async getStatusAgeVerificationStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgeVerificationStatusResponse> {
        const response = await this.getStatusAgeVerificationStatusGetRaw(initOverrides);
        return await response.value();
    }

}
