/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatReponse,
  GetConversationMessagesResponse,
  GetConversationResponse,
  GetImageModerationPromptResponse,
  GetLiveRoleplayHistoryResponse,
  HTTPValidationError,
  ListConversationsResponse,
  PatchChatMessageRequest,
  PatchImageModerationPromptRequest,
  PostChatRequest,
  PostChatSuggestionRequest,
  PostConversationSettingsRequest,
  PostLiveRoleplayRequest,
  PostLiveRoleplayResponse,
  TokenPricingConfigResponse,
} from '../models/index';
import {
    ChatReponseFromJSON,
    ChatReponseToJSON,
    GetConversationMessagesResponseFromJSON,
    GetConversationMessagesResponseToJSON,
    GetConversationResponseFromJSON,
    GetConversationResponseToJSON,
    GetImageModerationPromptResponseFromJSON,
    GetImageModerationPromptResponseToJSON,
    GetLiveRoleplayHistoryResponseFromJSON,
    GetLiveRoleplayHistoryResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListConversationsResponseFromJSON,
    ListConversationsResponseToJSON,
    PatchChatMessageRequestFromJSON,
    PatchChatMessageRequestToJSON,
    PatchImageModerationPromptRequestFromJSON,
    PatchImageModerationPromptRequestToJSON,
    PostChatRequestFromJSON,
    PostChatRequestToJSON,
    PostChatSuggestionRequestFromJSON,
    PostChatSuggestionRequestToJSON,
    PostConversationSettingsRequestFromJSON,
    PostConversationSettingsRequestToJSON,
    PostLiveRoleplayRequestFromJSON,
    PostLiveRoleplayRequestToJSON,
    PostLiveRoleplayResponseFromJSON,
    PostLiveRoleplayResponseToJSON,
    TokenPricingConfigResponseFromJSON,
    TokenPricingConfigResponseToJSON,
} from '../models/index';

export interface ChatChatChatbotIdPostRequest {
    chatbotId: string;
    postChatRequest: PostChatRequest;
}

export interface ChatSuggestionChatChatbotIdSuggestionPostRequest {
    chatbotId: string;
    postChatSuggestionRequest: PostChatSuggestionRequest;
}

export interface ClaimLiveRoleplayChatChatbotIdLiveRoleplayClaimPostRequest {
    chatbotId: string;
}

export interface ConversationChatChatbotIdGetRequest {
    chatbotId: string;
    limit?: number;
}

export interface ConversationMessagesChatChatbotIdMessagesConversationIdGetRequest {
    conversationId: string;
    chatbotId: string;
    paginationToken?: string | null;
    limit?: number;
}

export interface ConversationsChatGetRequest {
    paginationToken?: string | null;
    limit?: number;
}

export interface DeleteChatChatChatbotIdDeleteRequest {
    chatbotId: string;
}

export interface DeleteMessageChatMessageMessageIdDeleteRequest {
    messageId: string;
    imageId?: string | null;
    videoId?: string | null;
}

export interface GenerateImageOnMessageChatChatbotIdMessageRequestIdImagePostRequest {
    chatbotId: string;
    requestId: string;
    postChatRequest: PostChatRequest;
}

export interface GetLiveRoleplayHistoryChatChatbotIdLiveRoleplayGetRequest {
    chatbotId: string;
}

export interface LiveRoleplayChatChatbotIdLiveRoleplayPostRequest {
    chatbotId: string;
    postLiveRoleplayRequest: PostLiveRoleplayRequest;
}

export interface RegenerateChatChatbotIdMessageMessageIdRegeneratePostRequest {
    chatbotId: string;
    messageId: string;
    postChatRequest: PostChatRequest;
}

export interface ResetConversationChatConversationConversationIdResetPostRequest {
    conversationId: string;
}

export interface UpdateConversationSettingsChatConversationConversationIdSettingsPatchRequest {
    conversationId: string;
    postConversationSettingsRequest: PostConversationSettingsRequest;
}

export interface UpdateImageModerationPromptChatImageModerationPromptPatchRequest {
    patchImageModerationPromptRequest: PatchImageModerationPromptRequest;
}

export interface UpdateMessageChatMessageMessageIdPatchRequest {
    messageId: string;
    patchChatMessageRequest: PatchChatMessageRequest;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Chat
     */
    async chatChatChatbotIdPostRaw(requestParameters: ChatChatChatbotIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatReponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling chatChatChatbotIdPost().'
            );
        }

        if (requestParameters['postChatRequest'] == null) {
            throw new runtime.RequiredError(
                'postChatRequest',
                'Required parameter "postChatRequest" was null or undefined when calling chatChatChatbotIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/{chatbot_id}`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostChatRequestToJSON(requestParameters['postChatRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatReponseFromJSON(jsonValue));
    }

    /**
     * Chat
     */
    async chatChatChatbotIdPost(requestParameters: ChatChatChatbotIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatReponse> {
        const response = await this.chatChatChatbotIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Chat Suggestion
     */
    async chatSuggestionChatChatbotIdSuggestionPostRaw(requestParameters: ChatSuggestionChatChatbotIdSuggestionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatReponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling chatSuggestionChatChatbotIdSuggestionPost().'
            );
        }

        if (requestParameters['postChatSuggestionRequest'] == null) {
            throw new runtime.RequiredError(
                'postChatSuggestionRequest',
                'Required parameter "postChatSuggestionRequest" was null or undefined when calling chatSuggestionChatChatbotIdSuggestionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/{chatbot_id}/suggestion`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostChatSuggestionRequestToJSON(requestParameters['postChatSuggestionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatReponseFromJSON(jsonValue));
    }

    /**
     * Chat Suggestion
     */
    async chatSuggestionChatChatbotIdSuggestionPost(requestParameters: ChatSuggestionChatChatbotIdSuggestionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatReponse> {
        const response = await this.chatSuggestionChatChatbotIdSuggestionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Claim Live Roleplay
     */
    async claimLiveRoleplayChatChatbotIdLiveRoleplayClaimPostRaw(requestParameters: ClaimLiveRoleplayChatChatbotIdLiveRoleplayClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling claimLiveRoleplayChatChatbotIdLiveRoleplayClaimPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/{chatbot_id}/live-roleplay/claim`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Claim Live Roleplay
     */
    async claimLiveRoleplayChatChatbotIdLiveRoleplayClaimPost(requestParameters: ClaimLiveRoleplayChatChatbotIdLiveRoleplayClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.claimLiveRoleplayChatChatbotIdLiveRoleplayClaimPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Conversation
     */
    async conversationChatChatbotIdGetRaw(requestParameters: ConversationChatChatbotIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetConversationResponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling conversationChatChatbotIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/{chatbot_id}`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetConversationResponseFromJSON(jsonValue));
    }

    /**
     * Conversation
     */
    async conversationChatChatbotIdGet(requestParameters: ConversationChatChatbotIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetConversationResponse> {
        const response = await this.conversationChatChatbotIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Conversation Messages
     */
    async conversationMessagesChatChatbotIdMessagesConversationIdGetRaw(requestParameters: ConversationMessagesChatChatbotIdMessagesConversationIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetConversationMessagesResponse>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling conversationMessagesChatChatbotIdMessagesConversationIdGet().'
            );
        }

        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling conversationMessagesChatChatbotIdMessagesConversationIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['paginationToken'] != null) {
            queryParameters['pagination_token'] = requestParameters['paginationToken'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/{chatbot_id}/messages/{conversation_id}`.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId']))).replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetConversationMessagesResponseFromJSON(jsonValue));
    }

    /**
     * Conversation Messages
     */
    async conversationMessagesChatChatbotIdMessagesConversationIdGet(requestParameters: ConversationMessagesChatChatbotIdMessagesConversationIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetConversationMessagesResponse> {
        const response = await this.conversationMessagesChatChatbotIdMessagesConversationIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Conversations
     */
    async conversationsChatGetRaw(requestParameters: ConversationsChatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListConversationsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['paginationToken'] != null) {
            queryParameters['pagination_token'] = requestParameters['paginationToken'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListConversationsResponseFromJSON(jsonValue));
    }

    /**
     * Conversations
     */
    async conversationsChatGet(requestParameters: ConversationsChatGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListConversationsResponse> {
        const response = await this.conversationsChatGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Chat
     */
    async deleteChatChatChatbotIdDeleteRaw(requestParameters: DeleteChatChatChatbotIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling deleteChatChatChatbotIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/{chatbot_id}`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Chat
     */
    async deleteChatChatChatbotIdDelete(requestParameters: DeleteChatChatChatbotIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteChatChatChatbotIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Message
     */
    async deleteMessageChatMessageMessageIdDeleteRaw(requestParameters: DeleteMessageChatMessageMessageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling deleteMessageChatMessageMessageIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['imageId'] != null) {
            queryParameters['image_id'] = requestParameters['imageId'];
        }

        if (requestParameters['videoId'] != null) {
            queryParameters['video_id'] = requestParameters['videoId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/message/{message_id}`.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Message
     */
    async deleteMessageChatMessageMessageIdDelete(requestParameters: DeleteMessageChatMessageMessageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteMessageChatMessageMessageIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Image On Message
     */
    async generateImageOnMessageChatChatbotIdMessageRequestIdImagePostRaw(requestParameters: GenerateImageOnMessageChatChatbotIdMessageRequestIdImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatReponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling generateImageOnMessageChatChatbotIdMessageRequestIdImagePost().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling generateImageOnMessageChatChatbotIdMessageRequestIdImagePost().'
            );
        }

        if (requestParameters['postChatRequest'] == null) {
            throw new runtime.RequiredError(
                'postChatRequest',
                'Required parameter "postChatRequest" was null or undefined when calling generateImageOnMessageChatChatbotIdMessageRequestIdImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/{chatbot_id}/message/{request_id}/image`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))).replace(`{${"request_id"}}`, encodeURIComponent(String(requestParameters['requestId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostChatRequestToJSON(requestParameters['postChatRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatReponseFromJSON(jsonValue));
    }

    /**
     * Generate Image On Message
     */
    async generateImageOnMessageChatChatbotIdMessageRequestIdImagePost(requestParameters: GenerateImageOnMessageChatChatbotIdMessageRequestIdImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatReponse> {
        const response = await this.generateImageOnMessageChatChatbotIdMessageRequestIdImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Chat Config
     */
    async getChatConfigChatConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPricingConfigResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPricingConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get Chat Config
     */
    async getChatConfigChatConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPricingConfigResponse> {
        const response = await this.getChatConfigChatConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Image Moderation Prompt
     */
    async getImageModerationPromptChatImageModerationPromptGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetImageModerationPromptResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/image-moderation-prompt`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetImageModerationPromptResponseFromJSON(jsonValue));
    }

    /**
     * Get Image Moderation Prompt
     */
    async getImageModerationPromptChatImageModerationPromptGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetImageModerationPromptResponse> {
        const response = await this.getImageModerationPromptChatImageModerationPromptGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Live Roleplay History
     */
    async getLiveRoleplayHistoryChatChatbotIdLiveRoleplayGetRaw(requestParameters: GetLiveRoleplayHistoryChatChatbotIdLiveRoleplayGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetLiveRoleplayHistoryResponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling getLiveRoleplayHistoryChatChatbotIdLiveRoleplayGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/{chatbot_id}/live-roleplay`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetLiveRoleplayHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Get Live Roleplay History
     */
    async getLiveRoleplayHistoryChatChatbotIdLiveRoleplayGet(requestParameters: GetLiveRoleplayHistoryChatChatbotIdLiveRoleplayGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetLiveRoleplayHistoryResponse> {
        const response = await this.getLiveRoleplayHistoryChatChatbotIdLiveRoleplayGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Live Roleplay
     */
    async liveRoleplayChatChatbotIdLiveRoleplayPostRaw(requestParameters: LiveRoleplayChatChatbotIdLiveRoleplayPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostLiveRoleplayResponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling liveRoleplayChatChatbotIdLiveRoleplayPost().'
            );
        }

        if (requestParameters['postLiveRoleplayRequest'] == null) {
            throw new runtime.RequiredError(
                'postLiveRoleplayRequest',
                'Required parameter "postLiveRoleplayRequest" was null or undefined when calling liveRoleplayChatChatbotIdLiveRoleplayPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/{chatbot_id}/live-roleplay`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostLiveRoleplayRequestToJSON(requestParameters['postLiveRoleplayRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostLiveRoleplayResponseFromJSON(jsonValue));
    }

    /**
     * Live Roleplay
     */
    async liveRoleplayChatChatbotIdLiveRoleplayPost(requestParameters: LiveRoleplayChatChatbotIdLiveRoleplayPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostLiveRoleplayResponse> {
        const response = await this.liveRoleplayChatChatbotIdLiveRoleplayPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Regenerate
     */
    async regenerateChatChatbotIdMessageMessageIdRegeneratePostRaw(requestParameters: RegenerateChatChatbotIdMessageMessageIdRegeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatReponse>> {
        if (requestParameters['chatbotId'] == null) {
            throw new runtime.RequiredError(
                'chatbotId',
                'Required parameter "chatbotId" was null or undefined when calling regenerateChatChatbotIdMessageMessageIdRegeneratePost().'
            );
        }

        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling regenerateChatChatbotIdMessageMessageIdRegeneratePost().'
            );
        }

        if (requestParameters['postChatRequest'] == null) {
            throw new runtime.RequiredError(
                'postChatRequest',
                'Required parameter "postChatRequest" was null or undefined when calling regenerateChatChatbotIdMessageMessageIdRegeneratePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/{chatbot_id}/message/{message_id}/regenerate`.replace(`{${"chatbot_id"}}`, encodeURIComponent(String(requestParameters['chatbotId']))).replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostChatRequestToJSON(requestParameters['postChatRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatReponseFromJSON(jsonValue));
    }

    /**
     * Regenerate
     */
    async regenerateChatChatbotIdMessageMessageIdRegeneratePost(requestParameters: RegenerateChatChatbotIdMessageMessageIdRegeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatReponse> {
        const response = await this.regenerateChatChatbotIdMessageMessageIdRegeneratePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reset Conversation
     */
    async resetConversationChatConversationConversationIdResetPostRaw(requestParameters: ResetConversationChatConversationConversationIdResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling resetConversationChatConversationConversationIdResetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/conversation/{conversation_id}/reset`.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Reset Conversation
     */
    async resetConversationChatConversationConversationIdResetPost(requestParameters: ResetConversationChatConversationConversationIdResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.resetConversationChatConversationConversationIdResetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Conversation Settings
     */
    async updateConversationSettingsChatConversationConversationIdSettingsPatchRaw(requestParameters: UpdateConversationSettingsChatConversationConversationIdSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversationSettingsChatConversationConversationIdSettingsPatch().'
            );
        }

        if (requestParameters['postConversationSettingsRequest'] == null) {
            throw new runtime.RequiredError(
                'postConversationSettingsRequest',
                'Required parameter "postConversationSettingsRequest" was null or undefined when calling updateConversationSettingsChatConversationConversationIdSettingsPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/conversation/{conversation_id}/settings`.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PostConversationSettingsRequestToJSON(requestParameters['postConversationSettingsRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Conversation Settings
     */
    async updateConversationSettingsChatConversationConversationIdSettingsPatch(requestParameters: UpdateConversationSettingsChatConversationConversationIdSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateConversationSettingsChatConversationConversationIdSettingsPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Image Moderation Prompt
     */
    async updateImageModerationPromptChatImageModerationPromptPatchRaw(requestParameters: UpdateImageModerationPromptChatImageModerationPromptPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['patchImageModerationPromptRequest'] == null) {
            throw new runtime.RequiredError(
                'patchImageModerationPromptRequest',
                'Required parameter "patchImageModerationPromptRequest" was null or undefined when calling updateImageModerationPromptChatImageModerationPromptPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/image-moderation-prompt`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchImageModerationPromptRequestToJSON(requestParameters['patchImageModerationPromptRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Image Moderation Prompt
     */
    async updateImageModerationPromptChatImageModerationPromptPatch(requestParameters: UpdateImageModerationPromptChatImageModerationPromptPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateImageModerationPromptChatImageModerationPromptPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Message
     */
    async updateMessageChatMessageMessageIdPatchRaw(requestParameters: UpdateMessageChatMessageMessageIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling updateMessageChatMessageMessageIdPatch().'
            );
        }

        if (requestParameters['patchChatMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'patchChatMessageRequest',
                'Required parameter "patchChatMessageRequest" was null or undefined when calling updateMessageChatMessageMessageIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/message/{message_id}`.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchChatMessageRequestToJSON(requestParameters['patchChatMessageRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Message
     */
    async updateMessageChatMessageMessageIdPatch(requestParameters: UpdateMessageChatMessageMessageIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateMessageChatMessageMessageIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
