/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameAdventureCreatorCreateRequest,
  GameAdventureCreatorListResponse,
  GameAdventureCreatorResponse,
  GameAdventureCreatorUpdateRequest,
  GameAdventureSessionResponse,
  HTTPValidationError,
} from '../models/index';
import {
    GameAdventureCreatorCreateRequestFromJSON,
    GameAdventureCreatorCreateRequestToJSON,
    GameAdventureCreatorListResponseFromJSON,
    GameAdventureCreatorListResponseToJSON,
    GameAdventureCreatorResponseFromJSON,
    GameAdventureCreatorResponseToJSON,
    GameAdventureCreatorUpdateRequestFromJSON,
    GameAdventureCreatorUpdateRequestToJSON,
    GameAdventureSessionResponseFromJSON,
    GameAdventureSessionResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateGameAdventureCreatorPostRequest {
    gameAdventureCreatorCreateRequest: GameAdventureCreatorCreateRequest;
}

export interface CreatePreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPostRequest {
    gameAdventureId: string;
}

export interface DeleteGameAdventureCreatorGameAdventureIdDeleteRequest {
    gameAdventureId: string;
}

export interface GetGameAdventureCreatorGameAdventureIdGetRequest {
    gameAdventureId: string;
}

export interface ListOwnGameAdventureCreatorGetRequest {
    excludeEventEntries?: boolean;
}

export interface UnpublishGameAdventureCreatorGameAdventureIdPublishDeleteRequest {
    gameAdventureId: string;
}

export interface UpdateGameAdventureCreatorGameAdventureIdPatchRequest {
    gameAdventureId: string;
    gameAdventureCreatorUpdateRequest: GameAdventureCreatorUpdateRequest;
}

/**
 * 
 */
export class GameAdventureCreatorApi extends runtime.BaseAPI {

    /**
     * **Creates a new draft game adventure from an owned chatbot, with one empty target**
     * Create new game adventure draft
     */
    async createGameAdventureCreatorPostRaw(requestParameters: CreateGameAdventureCreatorPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureCreatorResponse>> {
        if (requestParameters['gameAdventureCreatorCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureCreatorCreateRequest',
                'Required parameter "gameAdventureCreatorCreateRequest" was null or undefined when calling createGameAdventureCreatorPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventure-creator`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GameAdventureCreatorCreateRequestToJSON(requestParameters['gameAdventureCreatorCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureCreatorResponseFromJSON(jsonValue));
    }

    /**
     * **Creates a new draft game adventure from an owned chatbot, with one empty target**
     * Create new game adventure draft
     */
    async createGameAdventureCreatorPost(requestParameters: CreateGameAdventureCreatorPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureCreatorResponse> {
        const response = await this.createGameAdventureCreatorPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Plays the latest version (even unpublished) as if a regular player; never creates unlocks and surfaces hidden journal entries**
     * Start an owner preview session
     */
    async createPreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPostRaw(requestParameters: CreatePreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureSessionResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling createPreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-creator/{game_adventure_id}/preview-session`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureSessionResponseFromJSON(jsonValue));
    }

    /**
     * **Plays the latest version (even unpublished) as if a regular player; never creates unlocks and surfaces hidden journal entries**
     * Start an owner preview session
     */
    async createPreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPost(requestParameters: CreatePreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureSessionResponse> {
        const response = await this.createPreviewSessionGameAdventureCreatorGameAdventureIdPreviewSessionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deleteGameAdventureCreatorGameAdventureIdDeleteRaw(requestParameters: DeleteGameAdventureCreatorGameAdventureIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling deleteGameAdventureCreatorGameAdventureIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-creator/{game_adventure_id}`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteGameAdventureCreatorGameAdventureIdDelete(requestParameters: DeleteGameAdventureCreatorGameAdventureIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGameAdventureCreatorGameAdventureIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get
     */
    async getGameAdventureCreatorGameAdventureIdGetRaw(requestParameters: GetGameAdventureCreatorGameAdventureIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureCreatorResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling getGameAdventureCreatorGameAdventureIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-creator/{game_adventure_id}`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureCreatorResponseFromJSON(jsonValue));
    }

    /**
     * Get
     */
    async getGameAdventureCreatorGameAdventureIdGet(requestParameters: GetGameAdventureCreatorGameAdventureIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureCreatorResponse> {
        const response = await this.getGameAdventureCreatorGameAdventureIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Own
     */
    async listOwnGameAdventureCreatorGetRaw(requestParameters: ListOwnGameAdventureCreatorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureCreatorListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['excludeEventEntries'] != null) {
            queryParameters['exclude_event_entries'] = requestParameters['excludeEventEntries'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-creator`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureCreatorListResponseFromJSON(jsonValue));
    }

    /**
     * List Own
     */
    async listOwnGameAdventureCreatorGet(requestParameters: ListOwnGameAdventureCreatorGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureCreatorListResponse> {
        const response = await this.listOwnGameAdventureCreatorGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Returns the adventure to draft and hides its post; existing unlocks keep their prize access**
     * Unpublish a game adventure
     */
    async unpublishGameAdventureCreatorGameAdventureIdPublishDeleteRaw(requestParameters: UnpublishGameAdventureCreatorGameAdventureIdPublishDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling unpublishGameAdventureCreatorGameAdventureIdPublishDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-creator/{game_adventure_id}/publish`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Returns the adventure to draft and hides its post; existing unlocks keep their prize access**
     * Unpublish a game adventure
     */
    async unpublishGameAdventureCreatorGameAdventureIdPublishDelete(requestParameters: UnpublishGameAdventureCreatorGameAdventureIdPublishDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unpublishGameAdventureCreatorGameAdventureIdPublishDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Update
     */
    async updateGameAdventureCreatorGameAdventureIdPatchRaw(requestParameters: UpdateGameAdventureCreatorGameAdventureIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureCreatorResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling updateGameAdventureCreatorGameAdventureIdPatch().'
            );
        }

        if (requestParameters['gameAdventureCreatorUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureCreatorUpdateRequest',
                'Required parameter "gameAdventureCreatorUpdateRequest" was null or undefined when calling updateGameAdventureCreatorGameAdventureIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventure-creator/{game_adventure_id}`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GameAdventureCreatorUpdateRequestToJSON(requestParameters['gameAdventureCreatorUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureCreatorResponseFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateGameAdventureCreatorGameAdventureIdPatch(requestParameters: UpdateGameAdventureCreatorGameAdventureIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureCreatorResponse> {
        const response = await this.updateGameAdventureCreatorGameAdventureIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
