/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameAdventureDetailResponse,
  GameAdventurePrizesResponse,
  GameAdventureRating,
  GameAdventureSessionDetailResponse,
  GameAdventureSessionListResponse,
  GameAdventureSessionResponse,
  HTTPValidationError,
  PostGameAdventureImageRequest,
  PostGameAdventureJournalReviewRequest,
  PostGameAdventureJournalReviewResponse,
  PostGameAdventureMediaResponse,
  PostGameAdventureMessageRequest,
  PostGameAdventureMessageResponse,
  PostGameAdventureRatingRequest,
  PostGameAdventureVideoRequest,
} from '../models/index';
import {
    GameAdventureDetailResponseFromJSON,
    GameAdventureDetailResponseToJSON,
    GameAdventurePrizesResponseFromJSON,
    GameAdventurePrizesResponseToJSON,
    GameAdventureRatingFromJSON,
    GameAdventureRatingToJSON,
    GameAdventureSessionDetailResponseFromJSON,
    GameAdventureSessionDetailResponseToJSON,
    GameAdventureSessionListResponseFromJSON,
    GameAdventureSessionListResponseToJSON,
    GameAdventureSessionResponseFromJSON,
    GameAdventureSessionResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PostGameAdventureImageRequestFromJSON,
    PostGameAdventureImageRequestToJSON,
    PostGameAdventureJournalReviewRequestFromJSON,
    PostGameAdventureJournalReviewRequestToJSON,
    PostGameAdventureJournalReviewResponseFromJSON,
    PostGameAdventureJournalReviewResponseToJSON,
    PostGameAdventureMediaResponseFromJSON,
    PostGameAdventureMediaResponseToJSON,
    PostGameAdventureMessageRequestFromJSON,
    PostGameAdventureMessageRequestToJSON,
    PostGameAdventureMessageResponseFromJSON,
    PostGameAdventureMessageResponseToJSON,
    PostGameAdventureRatingRequestFromJSON,
    PostGameAdventureRatingRequestToJSON,
    PostGameAdventureVideoRequestFromJSON,
    PostGameAdventureVideoRequestToJSON,
} from '../models/index';

export interface CreateSessionGameAdventuresGameAdventureIdSessionsPostRequest {
    gameAdventureId: string;
}

export interface DeleteSessionGameAdventureSessionsSessionIdDeleteRequest {
    sessionId: string;
}

export interface GenerateImageGameAdventureSessionsSessionIdImagePostRequest {
    sessionId: string;
    postGameAdventureImageRequest: PostGameAdventureImageRequest;
}

export interface GenerateVideoGameAdventureSessionsSessionIdVideoPostRequest {
    sessionId: string;
    postGameAdventureVideoRequest: PostGameAdventureVideoRequest;
}

export interface GetDetailGameAdventuresGameAdventureIdGetRequest {
    gameAdventureId: string;
}

export interface GetPrizesGameAdventuresGameAdventureIdPrizesGetRequest {
    gameAdventureId: string;
}

export interface GetSessionGameAdventureSessionsSessionIdGetRequest {
    sessionId: string;
}

export interface ListSessionsGameAdventuresGameAdventureIdSessionsGetRequest {
    gameAdventureId: string;
}

export interface RateGameAdventuresGameAdventureIdRatingPostRequest {
    gameAdventureId: string;
    postGameAdventureRatingRequest: PostGameAdventureRatingRequest;
}

export interface ReviewJournalGameAdventureSessionsSessionIdJournalReviewPostRequest {
    sessionId: string;
    postGameAdventureJournalReviewRequest: PostGameAdventureJournalReviewRequest;
}

export interface SendMessageGameAdventureSessionsSessionIdMessagePostRequest {
    sessionId: string;
    postGameAdventureMessageRequest: PostGameAdventureMessageRequest;
}

/**
 * 
 */
export class GameAdventuresApi extends runtime.BaseAPI {

    /**
     * **Creates a new session pinned to the latest published version, seeding the greeting messages**
     * Start a new game adventure session
     */
    async createSessionGameAdventuresGameAdventureIdSessionsPostRaw(requestParameters: CreateSessionGameAdventuresGameAdventureIdSessionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureSessionResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling createSessionGameAdventuresGameAdventureIdSessionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventures/{game_adventure_id}/sessions`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureSessionResponseFromJSON(jsonValue));
    }

    /**
     * **Creates a new session pinned to the latest published version, seeding the greeting messages**
     * Start a new game adventure session
     */
    async createSessionGameAdventuresGameAdventureIdSessionsPost(requestParameters: CreateSessionGameAdventuresGameAdventureIdSessionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureSessionResponse> {
        const response = await this.createSessionGameAdventuresGameAdventureIdSessionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Session
     */
    async deleteSessionGameAdventureSessionsSessionIdDeleteRaw(requestParameters: DeleteSessionGameAdventureSessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deleteSessionGameAdventureSessionsSessionIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-sessions/{session_id}`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Session
     */
    async deleteSessionGameAdventureSessionsSessionIdDelete(requestParameters: DeleteSessionGameAdventureSessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSessionGameAdventureSessionsSessionIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Generate Image
     */
    async generateImageGameAdventureSessionsSessionIdImagePostRaw(requestParameters: GenerateImageGameAdventureSessionsSessionIdImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostGameAdventureMediaResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling generateImageGameAdventureSessionsSessionIdImagePost().'
            );
        }

        if (requestParameters['postGameAdventureImageRequest'] == null) {
            throw new runtime.RequiredError(
                'postGameAdventureImageRequest',
                'Required parameter "postGameAdventureImageRequest" was null or undefined when calling generateImageGameAdventureSessionsSessionIdImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventure-sessions/{session_id}/image`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostGameAdventureImageRequestToJSON(requestParameters['postGameAdventureImageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostGameAdventureMediaResponseFromJSON(jsonValue));
    }

    /**
     * Generate Image
     */
    async generateImageGameAdventureSessionsSessionIdImagePost(requestParameters: GenerateImageGameAdventureSessionsSessionIdImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostGameAdventureMediaResponse> {
        const response = await this.generateImageGameAdventureSessionsSessionIdImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Video
     */
    async generateVideoGameAdventureSessionsSessionIdVideoPostRaw(requestParameters: GenerateVideoGameAdventureSessionsSessionIdVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostGameAdventureMediaResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling generateVideoGameAdventureSessionsSessionIdVideoPost().'
            );
        }

        if (requestParameters['postGameAdventureVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'postGameAdventureVideoRequest',
                'Required parameter "postGameAdventureVideoRequest" was null or undefined when calling generateVideoGameAdventureSessionsSessionIdVideoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventure-sessions/{session_id}/video`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostGameAdventureVideoRequestToJSON(requestParameters['postGameAdventureVideoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostGameAdventureMediaResponseFromJSON(jsonValue));
    }

    /**
     * Generate Video
     */
    async generateVideoGameAdventureSessionsSessionIdVideoPost(requestParameters: GenerateVideoGameAdventureSessionsSessionIdVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostGameAdventureMediaResponse> {
        const response = await this.generateVideoGameAdventureSessionsSessionIdVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Detail
     */
    async getDetailGameAdventuresGameAdventureIdGetRaw(requestParameters: GetDetailGameAdventuresGameAdventureIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureDetailResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling getDetailGameAdventuresGameAdventureIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventures/{game_adventure_id}`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get Detail
     */
    async getDetailGameAdventuresGameAdventureIdGet(requestParameters: GetDetailGameAdventuresGameAdventureIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureDetailResponse> {
        const response = await this.getDetailGameAdventuresGameAdventureIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Prizes
     */
    async getPrizesGameAdventuresGameAdventureIdPrizesGetRaw(requestParameters: GetPrizesGameAdventuresGameAdventureIdPrizesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventurePrizesResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling getPrizesGameAdventuresGameAdventureIdPrizesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventures/{game_adventure_id}/prizes`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventurePrizesResponseFromJSON(jsonValue));
    }

    /**
     * Get Prizes
     */
    async getPrizesGameAdventuresGameAdventureIdPrizesGet(requestParameters: GetPrizesGameAdventuresGameAdventureIdPrizesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventurePrizesResponse> {
        const response = await this.getPrizesGameAdventuresGameAdventureIdPrizesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Session
     */
    async getSessionGameAdventureSessionsSessionIdGetRaw(requestParameters: GetSessionGameAdventureSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureSessionDetailResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionGameAdventureSessionsSessionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventure-sessions/{session_id}`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureSessionDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get Session
     */
    async getSessionGameAdventureSessionsSessionIdGet(requestParameters: GetSessionGameAdventureSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureSessionDetailResponse> {
        const response = await this.getSessionGameAdventureSessionsSessionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Sessions
     */
    async listSessionsGameAdventuresGameAdventureIdSessionsGetRaw(requestParameters: ListSessionsGameAdventuresGameAdventureIdSessionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureSessionListResponse>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling listSessionsGameAdventuresGameAdventureIdSessionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game-adventures/{game_adventure_id}/sessions`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureSessionListResponseFromJSON(jsonValue));
    }

    /**
     * List Sessions
     */
    async listSessionsGameAdventuresGameAdventureIdSessionsGet(requestParameters: ListSessionsGameAdventuresGameAdventureIdSessionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureSessionListResponse> {
        const response = await this.listSessionsGameAdventuresGameAdventureIdSessionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rate
     */
    async rateGameAdventuresGameAdventureIdRatingPostRaw(requestParameters: RateGameAdventuresGameAdventureIdRatingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameAdventureRating>> {
        if (requestParameters['gameAdventureId'] == null) {
            throw new runtime.RequiredError(
                'gameAdventureId',
                'Required parameter "gameAdventureId" was null or undefined when calling rateGameAdventuresGameAdventureIdRatingPost().'
            );
        }

        if (requestParameters['postGameAdventureRatingRequest'] == null) {
            throw new runtime.RequiredError(
                'postGameAdventureRatingRequest',
                'Required parameter "postGameAdventureRatingRequest" was null or undefined when calling rateGameAdventuresGameAdventureIdRatingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventures/{game_adventure_id}/rating`.replace(`{${"game_adventure_id"}}`, encodeURIComponent(String(requestParameters['gameAdventureId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostGameAdventureRatingRequestToJSON(requestParameters['postGameAdventureRatingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameAdventureRatingFromJSON(jsonValue));
    }

    /**
     * Rate
     */
    async rateGameAdventuresGameAdventureIdRatingPost(requestParameters: RateGameAdventuresGameAdventureIdRatingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameAdventureRating> {
        const response = await this.rateGameAdventuresGameAdventureIdRatingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **The judge reviews the turn\'s player message + response and appends journal facts if anything new is worth recording**
     * Review one exchange for the journal
     */
    async reviewJournalGameAdventureSessionsSessionIdJournalReviewPostRaw(requestParameters: ReviewJournalGameAdventureSessionsSessionIdJournalReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostGameAdventureJournalReviewResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling reviewJournalGameAdventureSessionsSessionIdJournalReviewPost().'
            );
        }

        if (requestParameters['postGameAdventureJournalReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'postGameAdventureJournalReviewRequest',
                'Required parameter "postGameAdventureJournalReviewRequest" was null or undefined when calling reviewJournalGameAdventureSessionsSessionIdJournalReviewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventure-sessions/{session_id}/journal-review`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostGameAdventureJournalReviewRequestToJSON(requestParameters['postGameAdventureJournalReviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostGameAdventureJournalReviewResponseFromJSON(jsonValue));
    }

    /**
     * **The judge reviews the turn\'s player message + response and appends journal facts if anything new is worth recording**
     * Review one exchange for the journal
     */
    async reviewJournalGameAdventureSessionsSessionIdJournalReviewPost(requestParameters: ReviewJournalGameAdventureSessionsSessionIdJournalReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostGameAdventureJournalReviewResponse> {
        const response = await this.reviewJournalGameAdventureSessionsSessionIdJournalReviewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send Message
     */
    async sendMessageGameAdventureSessionsSessionIdMessagePostRaw(requestParameters: SendMessageGameAdventureSessionsSessionIdMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostGameAdventureMessageResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling sendMessageGameAdventureSessionsSessionIdMessagePost().'
            );
        }

        if (requestParameters['postGameAdventureMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'postGameAdventureMessageRequest',
                'Required parameter "postGameAdventureMessageRequest" was null or undefined when calling sendMessageGameAdventureSessionsSessionIdMessagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/game-adventure-sessions/{session_id}/message`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostGameAdventureMessageRequestToJSON(requestParameters['postGameAdventureMessageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostGameAdventureMessageResponseFromJSON(jsonValue));
    }

    /**
     * Send Message
     */
    async sendMessageGameAdventureSessionsSessionIdMessagePost(requestParameters: SendMessageGameAdventureSessionsSessionIdMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostGameAdventureMessageResponse> {
        const response = await this.sendMessageGameAdventureSessionsSessionIdMessagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
