/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PromotionListResponse,
} from '../models/index';
import {
    PromotionListResponseFromJSON,
    PromotionListResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class PromotionApi extends runtime.BaseAPI {

    /**
     * The promotions live right now, for the client\'s offer banners.
     * Get Promotions
     */
    async getPromotionsPromotionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromotionListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/promotion`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromotionListResponseFromJSON(jsonValue));
    }

    /**
     * The promotions live right now, for the client\'s offer banners.
     * Get Promotions
     */
    async getPromotionsPromotionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromotionListResponse> {
        const response = await this.getPromotionsPromotionGetRaw(initOverrides);
        return await response.value();
    }

}
