/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminTokenUsageGroupResponse } from './AdminTokenUsageGroupResponse';
import {
    AdminTokenUsageGroupResponseFromJSON,
    AdminTokenUsageGroupResponseFromJSONTyped,
    AdminTokenUsageGroupResponseToJSON,
    AdminTokenUsageGroupResponseToJSONTyped,
} from './AdminTokenUsageGroupResponse';
import type { AdminPricingGroupResponse } from './AdminPricingGroupResponse';
import {
    AdminPricingGroupResponseFromJSON,
    AdminPricingGroupResponseFromJSONTyped,
    AdminPricingGroupResponseToJSON,
    AdminPricingGroupResponseToJSONTyped,
} from './AdminPricingGroupResponse';

/**
 * 
 * @export
 * @interface AdminPricingGroupRevisionsResponse
 */
export interface AdminPricingGroupRevisionsResponse {
    /**
     * 
     * @type {AdminPricingGroupResponse}
     * @memberof AdminPricingGroupRevisionsResponse
     */
    pricingGroup: AdminPricingGroupResponse | null;
    /**
     * 
     * @type {AdminTokenUsageGroupResponse}
     * @memberof AdminPricingGroupRevisionsResponse
     */
    tokenUsageGroup: AdminTokenUsageGroupResponse | null;
}

/**
 * Check if a given object implements the AdminPricingGroupRevisionsResponse interface.
 */
export function instanceOfAdminPricingGroupRevisionsResponse(value: object): value is AdminPricingGroupRevisionsResponse {
    if (!('pricingGroup' in value) || value['pricingGroup'] === undefined) return false;
    if (!('tokenUsageGroup' in value) || value['tokenUsageGroup'] === undefined) return false;
    return true;
}

export function AdminPricingGroupRevisionsResponseFromJSON(json: any): AdminPricingGroupRevisionsResponse {
    return AdminPricingGroupRevisionsResponseFromJSONTyped(json, false);
}

export function AdminPricingGroupRevisionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPricingGroupRevisionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pricingGroup': AdminPricingGroupResponseFromJSON(json['pricing_group']),
        'tokenUsageGroup': AdminTokenUsageGroupResponseFromJSON(json['token_usage_group']),
    };
}

  export function AdminPricingGroupRevisionsResponseToJSON(json: any): AdminPricingGroupRevisionsResponse {
      return AdminPricingGroupRevisionsResponseToJSONTyped(json, false);
  }

  export function AdminPricingGroupRevisionsResponseToJSONTyped(value?: AdminPricingGroupRevisionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pricing_group': AdminPricingGroupResponseToJSON(value['pricingGroup']),
        'token_usage_group': AdminTokenUsageGroupResponseToJSON(value['tokenUsageGroup']),
    };
}

