/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminCreatePricingProductRequest } from './AdminCreatePricingProductRequest';
import {
    AdminCreatePricingProductRequestFromJSON,
    AdminCreatePricingProductRequestFromJSONTyped,
    AdminCreatePricingProductRequestToJSON,
    AdminCreatePricingProductRequestToJSONTyped,
} from './AdminCreatePricingProductRequest';
import type { Id } from './Id';
import {
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
    IdToJSONTyped,
} from './Id';

/**
 * 
 * @export
 * @interface AdminSavePricingGroupRequestInput
 */
export interface AdminSavePricingGroupRequestInput {
    [key: string]: any | any;
    /**
     * 
     * @type {Id}
     * @memberof AdminSavePricingGroupRequestInput
     */
    id?: Id;
    /**
     * 
     * @type {string}
     * @memberof AdminSavePricingGroupRequestInput
     */
    code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminSavePricingGroupRequestInput
     */
    activate?: boolean;
    /**
     * 
     * @type {Array<AdminCreatePricingProductRequest>}
     * @memberof AdminSavePricingGroupRequestInput
     */
    prices?: Array<AdminCreatePricingProductRequest>;
}

/**
 * Check if a given object implements the AdminSavePricingGroupRequestInput interface.
 */
export function instanceOfAdminSavePricingGroupRequestInput(value: object): value is AdminSavePricingGroupRequestInput {
    return true;
}

export function AdminSavePricingGroupRequestInputFromJSON(json: any): AdminSavePricingGroupRequestInput {
    return AdminSavePricingGroupRequestInputFromJSONTyped(json, false);
}

export function AdminSavePricingGroupRequestInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSavePricingGroupRequestInput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : IdFromJSON(json['id']),
        'code': json['code'] == null ? undefined : json['code'],
        'activate': json['activate'] == null ? undefined : json['activate'],
        'prices': json['prices'] == null ? undefined : ((json['prices'] as Array<any>).map(AdminCreatePricingProductRequestFromJSON)),
    };
}

  export function AdminSavePricingGroupRequestInputToJSON(json: any): AdminSavePricingGroupRequestInput {
      return AdminSavePricingGroupRequestInputToJSONTyped(json, false);
  }

  export function AdminSavePricingGroupRequestInputToJSONTyped(value?: AdminSavePricingGroupRequestInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': IdToJSON(value['id']),
        'code': value['code'],
        'activate': value['activate'],
        'prices': value['prices'] == null ? undefined : ((value['prices'] as Array<any>).map(AdminCreatePricingProductRequestToJSON)),
    };
}

