/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSaveTokenUsageGroupRequest } from './AdminSaveTokenUsageGroupRequest';
import {
    AdminSaveTokenUsageGroupRequestFromJSON,
    AdminSaveTokenUsageGroupRequestFromJSONTyped,
    AdminSaveTokenUsageGroupRequestToJSON,
    AdminSaveTokenUsageGroupRequestToJSONTyped,
} from './AdminSaveTokenUsageGroupRequest';
import type { AdminSavePricingGroupRequest } from './AdminSavePricingGroupRequest';
import {
    AdminSavePricingGroupRequestFromJSON,
    AdminSavePricingGroupRequestFromJSONTyped,
    AdminSavePricingGroupRequestToJSON,
    AdminSavePricingGroupRequestToJSONTyped,
} from './AdminSavePricingGroupRequest';

/**
 * 
 * @export
 * @interface AdminPricingGroupsResponse
 */
export interface AdminPricingGroupsResponse {
    /**
     * 
     * @type {Array<AdminSavePricingGroupRequest>}
     * @memberof AdminPricingGroupsResponse
     */
    pricingGroups: Array<AdminSavePricingGroupRequest>;
    /**
     * 
     * @type {Array<AdminSaveTokenUsageGroupRequest>}
     * @memberof AdminPricingGroupsResponse
     */
    tokenUsageGroups: Array<AdminSaveTokenUsageGroupRequest>;
}

/**
 * Check if a given object implements the AdminPricingGroupsResponse interface.
 */
export function instanceOfAdminPricingGroupsResponse(value: object): value is AdminPricingGroupsResponse {
    if (!('pricingGroups' in value) || value['pricingGroups'] === undefined) return false;
    if (!('tokenUsageGroups' in value) || value['tokenUsageGroups'] === undefined) return false;
    return true;
}

export function AdminPricingGroupsResponseFromJSON(json: any): AdminPricingGroupsResponse {
    return AdminPricingGroupsResponseFromJSONTyped(json, false);
}

export function AdminPricingGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPricingGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pricingGroups': ((json['pricing_groups'] as Array<any>).map(AdminSavePricingGroupRequestFromJSON)),
        'tokenUsageGroups': ((json['token_usage_groups'] as Array<any>).map(AdminSaveTokenUsageGroupRequestFromJSON)),
    };
}

  export function AdminPricingGroupsResponseToJSON(json: any): AdminPricingGroupsResponse {
      return AdminPricingGroupsResponseToJSONTyped(json, false);
  }

  export function AdminPricingGroupsResponseToJSONTyped(value?: AdminPricingGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pricing_groups': ((value['pricingGroups'] as Array<any>).map(AdminSavePricingGroupRequestToJSON)),
        'token_usage_groups': ((value['tokenUsageGroups'] as Array<any>).map(AdminSaveTokenUsageGroupRequestToJSON)),
    };
}

