/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpecialOffer } from './SpecialOffer';
import {
    SpecialOfferFromJSON,
    SpecialOfferFromJSONTyped,
    SpecialOfferToJSON,
    SpecialOfferToJSONTyped,
} from './SpecialOffer';
import type { BillingPeriod } from './BillingPeriod';
import {
    BillingPeriodFromJSON,
    BillingPeriodFromJSONTyped,
    BillingPeriodToJSON,
    BillingPeriodToJSONTyped,
} from './BillingPeriod';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
    ProductTypeToJSONTyped,
} from './ProductType';
import type { SubscriptionTier } from './SubscriptionTier';
import {
    SubscriptionTierFromJSON,
    SubscriptionTierFromJSONTyped,
    SubscriptionTierToJSON,
    SubscriptionTierToJSONTyped,
} from './SubscriptionTier';
import type { PaymentCurrency } from './PaymentCurrency';
import {
    PaymentCurrencyFromJSON,
    PaymentCurrencyFromJSONTyped,
    PaymentCurrencyToJSON,
    PaymentCurrencyToJSONTyped,
} from './PaymentCurrency';

/**
 * 
 * @export
 * @interface AdminPricingProductResponse
 */
export interface AdminPricingProductResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminPricingProductResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPricingProductResponse
     */
    code: string;
    /**
     * 
     * @type {ProductType}
     * @memberof AdminPricingProductResponse
     */
    productType: ProductType;
    /**
     * 
     * @type {SpecialOffer}
     * @memberof AdminPricingProductResponse
     */
    specialOffer: SpecialOffer;
    /**
     * 
     * @type {string}
     * @memberof AdminPricingProductResponse
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    displayPrice: number;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    totalPrice: number;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    monthlyTokens: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    oneTimeTokens: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminPricingProductResponse
     */
    displayDiscount: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    discountOriginalPrice: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    discountOriginalTokens: number | null;
    /**
     * 
     * @type {BillingPeriod}
     * @memberof AdminPricingProductResponse
     */
    billingPeriod: BillingPeriod | null;
    /**
     * 
     * @type {SubscriptionTier}
     * @memberof AdminPricingProductResponse
     */
    subscriptionTier: SubscriptionTier | null;
    /**
     * 
     * @type {PaymentCurrency}
     * @memberof AdminPricingProductResponse
     */
    currency: PaymentCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof AdminPricingProductResponse
     */
    hidden: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminPricingProductResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof AdminPricingProductResponse
     */
    sortOrder: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AdminPricingProductResponse
     */
    externalProductIds: { [key: string]: string; };
}



/**
 * Check if a given object implements the AdminPricingProductResponse interface.
 */
export function instanceOfAdminPricingProductResponse(value: object): value is AdminPricingProductResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('productType' in value) || value['productType'] === undefined) return false;
    if (!('specialOffer' in value) || value['specialOffer'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('displayPrice' in value) || value['displayPrice'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('monthlyTokens' in value) || value['monthlyTokens'] === undefined) return false;
    if (!('oneTimeTokens' in value) || value['oneTimeTokens'] === undefined) return false;
    if (!('displayDiscount' in value) || value['displayDiscount'] === undefined) return false;
    if (!('discountOriginalPrice' in value) || value['discountOriginalPrice'] === undefined) return false;
    if (!('discountOriginalTokens' in value) || value['discountOriginalTokens'] === undefined) return false;
    if (!('billingPeriod' in value) || value['billingPeriod'] === undefined) return false;
    if (!('subscriptionTier' in value) || value['subscriptionTier'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('hidden' in value) || value['hidden'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('externalProductIds' in value) || value['externalProductIds'] === undefined) return false;
    return true;
}

export function AdminPricingProductResponseFromJSON(json: any): AdminPricingProductResponse {
    return AdminPricingProductResponseFromJSONTyped(json, false);
}

export function AdminPricingProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPricingProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'productType': ProductTypeFromJSON(json['product_type']),
        'specialOffer': SpecialOfferFromJSON(json['special_offer']),
        'displayName': json['display_name'],
        'displayPrice': json['display_price'],
        'totalPrice': json['total_price'],
        'monthlyTokens': json['monthly_tokens'],
        'oneTimeTokens': json['one_time_tokens'],
        'displayDiscount': json['display_discount'],
        'discountOriginalPrice': json['discount_original_price'],
        'discountOriginalTokens': json['discount_original_tokens'],
        'billingPeriod': BillingPeriodFromJSON(json['billing_period']),
        'subscriptionTier': SubscriptionTierFromJSON(json['subscription_tier']),
        'currency': PaymentCurrencyFromJSON(json['currency']),
        'hidden': json['hidden'],
        'enabled': json['enabled'],
        'sortOrder': json['sort_order'],
        'externalProductIds': json['external_product_ids'],
    };
}

  export function AdminPricingProductResponseToJSON(json: any): AdminPricingProductResponse {
      return AdminPricingProductResponseToJSONTyped(json, false);
  }

  export function AdminPricingProductResponseToJSONTyped(value?: AdminPricingProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'product_type': ProductTypeToJSON(value['productType']),
        'special_offer': SpecialOfferToJSON(value['specialOffer']),
        'display_name': value['displayName'],
        'display_price': value['displayPrice'],
        'total_price': value['totalPrice'],
        'monthly_tokens': value['monthlyTokens'],
        'one_time_tokens': value['oneTimeTokens'],
        'display_discount': value['displayDiscount'],
        'discount_original_price': value['discountOriginalPrice'],
        'discount_original_tokens': value['discountOriginalTokens'],
        'billing_period': BillingPeriodToJSON(value['billingPeriod']),
        'subscription_tier': SubscriptionTierToJSON(value['subscriptionTier']),
        'currency': PaymentCurrencyToJSON(value['currency']),
        'hidden': value['hidden'],
        'enabled': value['enabled'],
        'sort_order': value['sortOrder'],
        'external_product_ids': value['externalProductIds'],
    };
}

