/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminCreateTokenUsageRequest } from './AdminCreateTokenUsageRequest';
import {
    AdminCreateTokenUsageRequestFromJSON,
    AdminCreateTokenUsageRequestFromJSONTyped,
    AdminCreateTokenUsageRequestToJSON,
    AdminCreateTokenUsageRequestToJSONTyped,
} from './AdminCreateTokenUsageRequest';
import type { Id } from './Id';
import {
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
    IdToJSONTyped,
} from './Id';
import type { AdminSaveTokenUsageGroupRequestInput } from './AdminSaveTokenUsageGroupRequestInput';
import {
    AdminSaveTokenUsageGroupRequestInputFromJSON,
    AdminSaveTokenUsageGroupRequestInputFromJSONTyped,
    AdminSaveTokenUsageGroupRequestInputToJSON,
    AdminSaveTokenUsageGroupRequestInputToJSONTyped,
} from './AdminSaveTokenUsageGroupRequestInput';

/**
 * 
 * @export
 * @interface AdminSavePricingGroupRevisionsRequestTokenUsageGroup
 */
export interface AdminSavePricingGroupRevisionsRequestTokenUsageGroup {
    /**
     * 
     * @type {Id}
     * @memberof AdminSavePricingGroupRevisionsRequestTokenUsageGroup
     */
    id?: Id;
    /**
     * 
     * @type {string}
     * @memberof AdminSavePricingGroupRevisionsRequestTokenUsageGroup
     */
    code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminSavePricingGroupRevisionsRequestTokenUsageGroup
     */
    activate?: boolean;
    /**
     * 
     * @type {Array<AdminCreateTokenUsageRequest>}
     * @memberof AdminSavePricingGroupRevisionsRequestTokenUsageGroup
     */
    rules?: Array<AdminCreateTokenUsageRequest>;
}

/**
 * Check if a given object implements the AdminSavePricingGroupRevisionsRequestTokenUsageGroup interface.
 */
export function instanceOfAdminSavePricingGroupRevisionsRequestTokenUsageGroup(value: object): value is AdminSavePricingGroupRevisionsRequestTokenUsageGroup {
    return true;
}

export function AdminSavePricingGroupRevisionsRequestTokenUsageGroupFromJSON(json: any): AdminSavePricingGroupRevisionsRequestTokenUsageGroup {
    return AdminSavePricingGroupRevisionsRequestTokenUsageGroupFromJSONTyped(json, false);
}

export function AdminSavePricingGroupRevisionsRequestTokenUsageGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSavePricingGroupRevisionsRequestTokenUsageGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : IdFromJSON(json['id']),
        'code': json['code'] == null ? undefined : json['code'],
        'activate': json['activate'] == null ? undefined : json['activate'],
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(AdminCreateTokenUsageRequestFromJSON)),
    };
}

  export function AdminSavePricingGroupRevisionsRequestTokenUsageGroupToJSON(json: any): AdminSavePricingGroupRevisionsRequestTokenUsageGroup {
      return AdminSavePricingGroupRevisionsRequestTokenUsageGroupToJSONTyped(json, false);
  }

  export function AdminSavePricingGroupRevisionsRequestTokenUsageGroupToJSONTyped(value?: AdminSavePricingGroupRevisionsRequestTokenUsageGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': IdToJSON(value['id']),
        'code': value['code'],
        'activate': value['activate'],
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(AdminCreateTokenUsageRequestToJSON)),
    };
}

