/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpecialOffer } from './SpecialOffer';
import {
    SpecialOfferFromJSON,
    SpecialOfferFromJSONTyped,
    SpecialOfferToJSON,
    SpecialOfferToJSONTyped,
} from './SpecialOffer';
import type { AdminCreatePricingProductRequestSubscriptionTier } from './AdminCreatePricingProductRequestSubscriptionTier';
import {
    AdminCreatePricingProductRequestSubscriptionTierFromJSON,
    AdminCreatePricingProductRequestSubscriptionTierFromJSONTyped,
    AdminCreatePricingProductRequestSubscriptionTierToJSON,
    AdminCreatePricingProductRequestSubscriptionTierToJSONTyped,
} from './AdminCreatePricingProductRequestSubscriptionTier';
import type { MonthlyTokens } from './MonthlyTokens';
import {
    MonthlyTokensFromJSON,
    MonthlyTokensFromJSONTyped,
    MonthlyTokensToJSON,
    MonthlyTokensToJSONTyped,
} from './MonthlyTokens';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
    ProductTypeToJSONTyped,
} from './ProductType';
import type { OneTimeTokens } from './OneTimeTokens';
import {
    OneTimeTokensFromJSON,
    OneTimeTokensFromJSONTyped,
    OneTimeTokensToJSON,
    OneTimeTokensToJSONTyped,
} from './OneTimeTokens';
import type { PaymentCurrency } from './PaymentCurrency';
import {
    PaymentCurrencyFromJSON,
    PaymentCurrencyFromJSONTyped,
    PaymentCurrencyToJSON,
    PaymentCurrencyToJSONTyped,
} from './PaymentCurrency';
import type { DiscountOriginalPrice } from './DiscountOriginalPrice';
import {
    DiscountOriginalPriceFromJSON,
    DiscountOriginalPriceFromJSONTyped,
    DiscountOriginalPriceToJSON,
    DiscountOriginalPriceToJSONTyped,
} from './DiscountOriginalPrice';
import type { DiscountOriginalTokens } from './DiscountOriginalTokens';
import {
    DiscountOriginalTokensFromJSON,
    DiscountOriginalTokensFromJSONTyped,
    DiscountOriginalTokensToJSON,
    DiscountOriginalTokensToJSONTyped,
} from './DiscountOriginalTokens';
import type { DisplayDiscount } from './DisplayDiscount';
import {
    DisplayDiscountFromJSON,
    DisplayDiscountFromJSONTyped,
    DisplayDiscountToJSON,
    DisplayDiscountToJSONTyped,
} from './DisplayDiscount';
import type { AdminCreatePricingProductRequestBillingPeriod } from './AdminCreatePricingProductRequestBillingPeriod';
import {
    AdminCreatePricingProductRequestBillingPeriodFromJSON,
    AdminCreatePricingProductRequestBillingPeriodFromJSONTyped,
    AdminCreatePricingProductRequestBillingPeriodToJSON,
    AdminCreatePricingProductRequestBillingPeriodToJSONTyped,
} from './AdminCreatePricingProductRequestBillingPeriod';

/**
 * 
 * @export
 * @interface AdminCreatePricingProductRequest
 */
export interface AdminCreatePricingProductRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AdminCreatePricingProductRequest
     */
    code: string;
    /**
     * 
     * @type {ProductType}
     * @memberof AdminCreatePricingProductRequest
     */
    productType: ProductType;
    /**
     * 
     * @type {SpecialOffer}
     * @memberof AdminCreatePricingProductRequest
     */
    specialOffer?: SpecialOffer;
    /**
     * 
     * @type {string}
     * @memberof AdminCreatePricingProductRequest
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof AdminCreatePricingProductRequest
     */
    displayPrice: number;
    /**
     * 
     * @type {number}
     * @memberof AdminCreatePricingProductRequest
     */
    totalPrice: number;
    /**
     * 
     * @type {MonthlyTokens}
     * @memberof AdminCreatePricingProductRequest
     */
    monthlyTokens?: MonthlyTokens;
    /**
     * 
     * @type {OneTimeTokens}
     * @memberof AdminCreatePricingProductRequest
     */
    oneTimeTokens?: OneTimeTokens;
    /**
     * 
     * @type {DisplayDiscount}
     * @memberof AdminCreatePricingProductRequest
     */
    displayDiscount?: DisplayDiscount;
    /**
     * 
     * @type {DiscountOriginalPrice}
     * @memberof AdminCreatePricingProductRequest
     */
    discountOriginalPrice?: DiscountOriginalPrice;
    /**
     * 
     * @type {DiscountOriginalTokens}
     * @memberof AdminCreatePricingProductRequest
     */
    discountOriginalTokens?: DiscountOriginalTokens;
    /**
     * 
     * @type {AdminCreatePricingProductRequestBillingPeriod}
     * @memberof AdminCreatePricingProductRequest
     */
    billingPeriod?: AdminCreatePricingProductRequestBillingPeriod;
    /**
     * 
     * @type {AdminCreatePricingProductRequestSubscriptionTier}
     * @memberof AdminCreatePricingProductRequest
     */
    subscriptionTier?: AdminCreatePricingProductRequestSubscriptionTier;
    /**
     * 
     * @type {PaymentCurrency}
     * @memberof AdminCreatePricingProductRequest
     */
    currency: PaymentCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCreatePricingProductRequest
     */
    hidden?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCreatePricingProductRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AdminCreatePricingProductRequest
     */
    sortOrder?: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AdminCreatePricingProductRequest
     */
    externalProductIds?: { [key: string]: string; };
}



/**
 * Check if a given object implements the AdminCreatePricingProductRequest interface.
 */
export function instanceOfAdminCreatePricingProductRequest(value: object): value is AdminCreatePricingProductRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('productType' in value) || value['productType'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('displayPrice' in value) || value['displayPrice'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function AdminCreatePricingProductRequestFromJSON(json: any): AdminCreatePricingProductRequest {
    return AdminCreatePricingProductRequestFromJSONTyped(json, false);
}

export function AdminCreatePricingProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCreatePricingProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'productType': ProductTypeFromJSON(json['product_type']),
        'specialOffer': json['special_offer'] == null ? undefined : SpecialOfferFromJSON(json['special_offer']),
        'displayName': json['display_name'],
        'displayPrice': json['display_price'],
        'totalPrice': json['total_price'],
        'monthlyTokens': json['monthly_tokens'] == null ? undefined : MonthlyTokensFromJSON(json['monthly_tokens']),
        'oneTimeTokens': json['one_time_tokens'] == null ? undefined : OneTimeTokensFromJSON(json['one_time_tokens']),
        'displayDiscount': json['display_discount'] == null ? undefined : DisplayDiscountFromJSON(json['display_discount']),
        'discountOriginalPrice': json['discount_original_price'] == null ? undefined : DiscountOriginalPriceFromJSON(json['discount_original_price']),
        'discountOriginalTokens': json['discount_original_tokens'] == null ? undefined : DiscountOriginalTokensFromJSON(json['discount_original_tokens']),
        'billingPeriod': json['billing_period'] == null ? undefined : AdminCreatePricingProductRequestBillingPeriodFromJSON(json['billing_period']),
        'subscriptionTier': json['subscription_tier'] == null ? undefined : AdminCreatePricingProductRequestSubscriptionTierFromJSON(json['subscription_tier']),
        'currency': PaymentCurrencyFromJSON(json['currency']),
        'hidden': json['hidden'] == null ? undefined : json['hidden'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'externalProductIds': json['external_product_ids'] == null ? undefined : json['external_product_ids'],
    };
}

  export function AdminCreatePricingProductRequestToJSON(json: any): AdminCreatePricingProductRequest {
      return AdminCreatePricingProductRequestToJSONTyped(json, false);
  }

  export function AdminCreatePricingProductRequestToJSONTyped(value?: AdminCreatePricingProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'product_type': ProductTypeToJSON(value['productType']),
        'special_offer': SpecialOfferToJSON(value['specialOffer']),
        'display_name': value['displayName'],
        'display_price': value['displayPrice'],
        'total_price': value['totalPrice'],
        'monthly_tokens': MonthlyTokensToJSON(value['monthlyTokens']),
        'one_time_tokens': OneTimeTokensToJSON(value['oneTimeTokens']),
        'display_discount': DisplayDiscountToJSON(value['displayDiscount']),
        'discount_original_price': DiscountOriginalPriceToJSON(value['discountOriginalPrice']),
        'discount_original_tokens': DiscountOriginalTokensToJSON(value['discountOriginalTokens']),
        'billing_period': AdminCreatePricingProductRequestBillingPeriodToJSON(value['billingPeriod']),
        'subscription_tier': AdminCreatePricingProductRequestSubscriptionTierToJSON(value['subscriptionTier']),
        'currency': PaymentCurrencyToJSON(value['currency']),
        'hidden': value['hidden'],
        'enabled': value['enabled'],
        'sort_order': value['sortOrder'],
        'external_product_ids': value['externalProductIds'],
    };
}

