/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenUsageType } from './TokenUsageType';
import {
    TokenUsageTypeFromJSON,
    TokenUsageTypeFromJSONTyped,
    TokenUsageTypeToJSON,
    TokenUsageTypeToJSONTyped,
} from './TokenUsageType';
import type { TokenUsageCalculationMode } from './TokenUsageCalculationMode';
import {
    TokenUsageCalculationModeFromJSON,
    TokenUsageCalculationModeFromJSONTyped,
    TokenUsageCalculationModeToJSON,
    TokenUsageCalculationModeToJSONTyped,
} from './TokenUsageCalculationMode';
import type { VideoResolution } from './VideoResolution';
import {
    VideoResolutionFromJSON,
    VideoResolutionFromJSONTyped,
    VideoResolutionToJSON,
    VideoResolutionToJSONTyped,
} from './VideoResolution';

/**
 * 
 * @export
 * @interface AdminTokenUsageResponse
 */
export interface AdminTokenUsageResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminTokenUsageResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminTokenUsageResponse
     */
    code: string;
    /**
     * 
     * @type {TokenUsageType}
     * @memberof AdminTokenUsageResponse
     */
    usageType: TokenUsageType;
    /**
     * 
     * @type {TokenUsageCalculationMode}
     * @memberof AdminTokenUsageResponse
     */
    usageBy: TokenUsageCalculationMode;
    /**
     * 
     * @type {number}
     * @memberof AdminTokenUsageResponse
     */
    tokenPrice: number;
    /**
     * 
     * @type {number}
     * @memberof AdminTokenUsageResponse
     */
    unitSize: number;
    /**
     * 
     * @type {number}
     * @memberof AdminTokenUsageResponse
     */
    minimumUnits: number;
    /**
     * 
     * @type {string}
     * @memberof AdminTokenUsageResponse
     */
    model: string | null;
    /**
     * 
     * @type {VideoResolution}
     * @memberof AdminTokenUsageResponse
     */
    resolution: VideoResolution | null;
    /**
     * 
     * @type {number}
     * @memberof AdminTokenUsageResponse
     */
    fixedDurationSeconds: number | null;
}



/**
 * Check if a given object implements the AdminTokenUsageResponse interface.
 */
export function instanceOfAdminTokenUsageResponse(value: object): value is AdminTokenUsageResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('usageType' in value) || value['usageType'] === undefined) return false;
    if (!('usageBy' in value) || value['usageBy'] === undefined) return false;
    if (!('tokenPrice' in value) || value['tokenPrice'] === undefined) return false;
    if (!('unitSize' in value) || value['unitSize'] === undefined) return false;
    if (!('minimumUnits' in value) || value['minimumUnits'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('fixedDurationSeconds' in value) || value['fixedDurationSeconds'] === undefined) return false;
    return true;
}

export function AdminTokenUsageResponseFromJSON(json: any): AdminTokenUsageResponse {
    return AdminTokenUsageResponseFromJSONTyped(json, false);
}

export function AdminTokenUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminTokenUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'usageType': TokenUsageTypeFromJSON(json['usage_type']),
        'usageBy': TokenUsageCalculationModeFromJSON(json['usage_by']),
        'tokenPrice': json['token_price'],
        'unitSize': json['unit_size'],
        'minimumUnits': json['minimum_units'],
        'model': json['model'],
        'resolution': VideoResolutionFromJSON(json['resolution']),
        'fixedDurationSeconds': json['fixed_duration_seconds'],
    };
}

  export function AdminTokenUsageResponseToJSON(json: any): AdminTokenUsageResponse {
      return AdminTokenUsageResponseToJSONTyped(json, false);
  }

  export function AdminTokenUsageResponseToJSONTyped(value?: AdminTokenUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'usage_type': TokenUsageTypeToJSON(value['usageType']),
        'usage_by': TokenUsageCalculationModeToJSON(value['usageBy']),
        'token_price': value['tokenPrice'],
        'unit_size': value['unitSize'],
        'minimum_units': value['minimumUnits'],
        'model': value['model'],
        'resolution': VideoResolutionToJSON(value['resolution']),
        'fixed_duration_seconds': value['fixedDurationSeconds'],
    };
}

