/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminFaceAgeEstimate } from './AdminFaceAgeEstimate';
import {
    AdminFaceAgeEstimateFromJSON,
    AdminFaceAgeEstimateFromJSONTyped,
    AdminFaceAgeEstimateToJSON,
    AdminFaceAgeEstimateToJSONTyped,
} from './AdminFaceAgeEstimate';

/**
 * Apparent-age screening of one generated picture; returned to admins only.
 * @export
 * @interface AdminAgeEstimation
 */
export interface AdminAgeEstimation {
    /**
     * 
     * @type {number}
     * @memberof AdminAgeEstimation
     */
    minApparentAge: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminAgeEstimation
     */
    faceCount: number;
    /**
     * 
     * @type {Array<AdminFaceAgeEstimate>}
     * @memberof AdminAgeEstimation
     */
    faces: Array<AdminFaceAgeEstimate>;
}

/**
 * Check if a given object implements the AdminAgeEstimation interface.
 */
export function instanceOfAdminAgeEstimation(value: object): value is AdminAgeEstimation {
    if (!('minApparentAge' in value) || value['minApparentAge'] === undefined) return false;
    if (!('faceCount' in value) || value['faceCount'] === undefined) return false;
    if (!('faces' in value) || value['faces'] === undefined) return false;
    return true;
}

export function AdminAgeEstimationFromJSON(json: any): AdminAgeEstimation {
    return AdminAgeEstimationFromJSONTyped(json, false);
}

export function AdminAgeEstimationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAgeEstimation {
    if (json == null) {
        return json;
    }
    return {
        
        'minApparentAge': json['min_apparent_age'],
        'faceCount': json['face_count'],
        'faces': ((json['faces'] as Array<any>).map(AdminFaceAgeEstimateFromJSON)),
    };
}

  export function AdminAgeEstimationToJSON(json: any): AdminAgeEstimation {
      return AdminAgeEstimationToJSONTyped(json, false);
  }

  export function AdminAgeEstimationToJSONTyped(value?: AdminAgeEstimation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_apparent_age': value['minApparentAge'],
        'face_count': value['faceCount'],
        'faces': ((value['faces'] as Array<any>).map(AdminFaceAgeEstimateToJSON)),
    };
}

