/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminCreateTokenUsageRequest } from './AdminCreateTokenUsageRequest';
import {
    AdminCreateTokenUsageRequestFromJSON,
    AdminCreateTokenUsageRequestFromJSONTyped,
    AdminCreateTokenUsageRequestToJSON,
    AdminCreateTokenUsageRequestToJSONTyped,
} from './AdminCreateTokenUsageRequest';
import type { Id } from './Id';
import {
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
    IdToJSONTyped,
} from './Id';

/**
 * 
 * @export
 * @interface AdminSaveTokenUsageGroupRequestInput
 */
export interface AdminSaveTokenUsageGroupRequestInput {
    [key: string]: any | any;
    /**
     * 
     * @type {Id}
     * @memberof AdminSaveTokenUsageGroupRequestInput
     */
    id?: Id;
    /**
     * 
     * @type {string}
     * @memberof AdminSaveTokenUsageGroupRequestInput
     */
    code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminSaveTokenUsageGroupRequestInput
     */
    activate?: boolean;
    /**
     * 
     * @type {Array<AdminCreateTokenUsageRequest>}
     * @memberof AdminSaveTokenUsageGroupRequestInput
     */
    rules?: Array<AdminCreateTokenUsageRequest>;
}

/**
 * Check if a given object implements the AdminSaveTokenUsageGroupRequestInput interface.
 */
export function instanceOfAdminSaveTokenUsageGroupRequestInput(value: object): value is AdminSaveTokenUsageGroupRequestInput {
    return true;
}

export function AdminSaveTokenUsageGroupRequestInputFromJSON(json: any): AdminSaveTokenUsageGroupRequestInput {
    return AdminSaveTokenUsageGroupRequestInputFromJSONTyped(json, false);
}

export function AdminSaveTokenUsageGroupRequestInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSaveTokenUsageGroupRequestInput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : IdFromJSON(json['id']),
        'code': json['code'] == null ? undefined : json['code'],
        'activate': json['activate'] == null ? undefined : json['activate'],
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(AdminCreateTokenUsageRequestFromJSON)),
    };
}

  export function AdminSaveTokenUsageGroupRequestInputToJSON(json: any): AdminSaveTokenUsageGroupRequestInput {
      return AdminSaveTokenUsageGroupRequestInputToJSONTyped(json, false);
  }

  export function AdminSaveTokenUsageGroupRequestInputToJSONTyped(value?: AdminSaveTokenUsageGroupRequestInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': IdToJSON(value['id']),
        'code': value['code'],
        'activate': value['activate'],
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(AdminCreateTokenUsageRequestToJSON)),
    };
}

