/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserJourneyListItem } from './AdminUserJourneyListItem';
import {
    AdminUserJourneyListItemFromJSON,
    AdminUserJourneyListItemFromJSONTyped,
    AdminUserJourneyListItemToJSON,
    AdminUserJourneyListItemToJSONTyped,
} from './AdminUserJourneyListItem';

/**
 * 
 * @export
 * @interface AdminUserJourneysResponse
 */
export interface AdminUserJourneysResponse {
    /**
     * 
     * @type {Array<AdminUserJourneyListItem>}
     * @memberof AdminUserJourneysResponse
     */
    users: Array<AdminUserJourneyListItem>;
    /**
     * 
     * @type {string}
     * @memberof AdminUserJourneysResponse
     */
    paginationToken?: string | null;
}

/**
 * Check if a given object implements the AdminUserJourneysResponse interface.
 */
export function instanceOfAdminUserJourneysResponse(value: object): value is AdminUserJourneysResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function AdminUserJourneysResponseFromJSON(json: any): AdminUserJourneysResponse {
    return AdminUserJourneysResponseFromJSONTyped(json, false);
}

export function AdminUserJourneysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserJourneysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(AdminUserJourneyListItemFromJSON)),
        'paginationToken': json['pagination_token'] == null ? undefined : json['pagination_token'],
    };
}

  export function AdminUserJourneysResponseToJSON(json: any): AdminUserJourneysResponse {
      return AdminUserJourneysResponseToJSONTyped(json, false);
  }

  export function AdminUserJourneysResponseToJSONTyped(value?: AdminUserJourneysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(AdminUserJourneyListItemToJSON)),
        'pagination_token': value['paginationToken'],
    };
}

