/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoPricingModel } from './VideoPricingModel';
import {
    VideoPricingModelFromJSON,
    VideoPricingModelFromJSONTyped,
    VideoPricingModelToJSON,
    VideoPricingModelToJSONTyped,
} from './VideoPricingModel';

/**
 * 
 * @export
 * @interface AdminCreatePromotionRequest
 */
export interface AdminCreatePromotionRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AdminCreatePromotionRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AdminCreatePromotionRequest
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof AdminCreatePromotionRequest
     */
    percentOff: number;
    /**
     * 
     * @type {Array<VideoPricingModel>}
     * @memberof AdminCreatePromotionRequest
     */
    pricingModels: Array<VideoPricingModel>;
    /**
     * 
     * @type {Date}
     * @memberof AdminCreatePromotionRequest
     */
    startsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminCreatePromotionRequest
     */
    endsAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCreatePromotionRequest
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the AdminCreatePromotionRequest interface.
 */
export function instanceOfAdminCreatePromotionRequest(value: object): value is AdminCreatePromotionRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('percentOff' in value) || value['percentOff'] === undefined) return false;
    if (!('pricingModels' in value) || value['pricingModels'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    return true;
}

export function AdminCreatePromotionRequestFromJSON(json: any): AdminCreatePromotionRequest {
    return AdminCreatePromotionRequestFromJSONTyped(json, false);
}

export function AdminCreatePromotionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCreatePromotionRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'title': json['title'],
        'percentOff': json['percent_off'],
        'pricingModels': ((json['pricing_models'] as Array<any>).map(VideoPricingModelFromJSON)),
        'startsAt': (new Date(json['starts_at'])),
        'endsAt': (new Date(json['ends_at'])),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

  export function AdminCreatePromotionRequestToJSON(json: any): AdminCreatePromotionRequest {
      return AdminCreatePromotionRequestToJSONTyped(json, false);
  }

  export function AdminCreatePromotionRequestToJSONTyped(value?: AdminCreatePromotionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'title': value['title'],
        'percent_off': value['percentOff'],
        'pricing_models': ((value['pricingModels'] as Array<any>).map(VideoPricingModelToJSON)),
        'starts_at': ((value['startsAt']).toISOString()),
        'ends_at': ((value['endsAt']).toISOString()),
        'enabled': value['enabled'],
    };
}

