/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionTier } from './SubscriptionTier';
import {
    SubscriptionTierFromJSON,
    SubscriptionTierFromJSONTyped,
    SubscriptionTierToJSON,
    SubscriptionTierToJSONTyped,
} from './SubscriptionTier';

/**
 * 
 * @export
 * @interface AdminCreatePricingProductRequestSubscriptionTier
 */
export interface AdminCreatePricingProductRequestSubscriptionTier {
}

/**
 * Check if a given object implements the AdminCreatePricingProductRequestSubscriptionTier interface.
 */
export function instanceOfAdminCreatePricingProductRequestSubscriptionTier(value: object): value is AdminCreatePricingProductRequestSubscriptionTier {
    return true;
}

export function AdminCreatePricingProductRequestSubscriptionTierFromJSON(json: any): AdminCreatePricingProductRequestSubscriptionTier {
    return AdminCreatePricingProductRequestSubscriptionTierFromJSONTyped(json, false);
}

export function AdminCreatePricingProductRequestSubscriptionTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCreatePricingProductRequestSubscriptionTier {
    return json;
}

  export function AdminCreatePricingProductRequestSubscriptionTierToJSON(json: any): AdminCreatePricingProductRequestSubscriptionTier {
      return AdminCreatePricingProductRequestSubscriptionTierToJSONTyped(json, false);
  }

  export function AdminCreatePricingProductRequestSubscriptionTierToJSONTyped(value?: AdminCreatePricingProductRequestSubscriptionTier | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

