/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EndsAt } from './EndsAt';
import {
    EndsAtFromJSON,
    EndsAtFromJSONTyped,
    EndsAtToJSON,
    EndsAtToJSONTyped,
} from './EndsAt';
import type { StartsAt } from './StartsAt';
import {
    StartsAtFromJSON,
    StartsAtFromJSONTyped,
    StartsAtToJSON,
    StartsAtToJSONTyped,
} from './StartsAt';
import type { PercentOff } from './PercentOff';
import {
    PercentOffFromJSON,
    PercentOffFromJSONTyped,
    PercentOffToJSON,
    PercentOffToJSONTyped,
} from './PercentOff';
import type { PricingModels } from './PricingModels';
import {
    PricingModelsFromJSON,
    PricingModelsFromJSONTyped,
    PricingModelsToJSON,
    PricingModelsToJSONTyped,
} from './PricingModels';
import type { Enabled } from './Enabled';
import {
    EnabledFromJSON,
    EnabledFromJSONTyped,
    EnabledToJSON,
    EnabledToJSONTyped,
} from './Enabled';
import type { Title } from './Title';
import {
    TitleFromJSON,
    TitleFromJSONTyped,
    TitleToJSON,
    TitleToJSONTyped,
} from './Title';
import type { Code } from './Code';
import {
    CodeFromJSON,
    CodeFromJSONTyped,
    CodeToJSON,
    CodeToJSONTyped,
} from './Code';

/**
 * 
 * @export
 * @interface AdminUpdatePromotionRequest
 */
export interface AdminUpdatePromotionRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {Code}
     * @memberof AdminUpdatePromotionRequest
     */
    code?: Code;
    /**
     * 
     * @type {Title}
     * @memberof AdminUpdatePromotionRequest
     */
    title?: Title;
    /**
     * 
     * @type {PercentOff}
     * @memberof AdminUpdatePromotionRequest
     */
    percentOff?: PercentOff;
    /**
     * 
     * @type {PricingModels}
     * @memberof AdminUpdatePromotionRequest
     */
    pricingModels?: PricingModels;
    /**
     * 
     * @type {StartsAt}
     * @memberof AdminUpdatePromotionRequest
     */
    startsAt?: StartsAt;
    /**
     * 
     * @type {EndsAt}
     * @memberof AdminUpdatePromotionRequest
     */
    endsAt?: EndsAt;
    /**
     * 
     * @type {Enabled}
     * @memberof AdminUpdatePromotionRequest
     */
    enabled?: Enabled;
}

/**
 * Check if a given object implements the AdminUpdatePromotionRequest interface.
 */
export function instanceOfAdminUpdatePromotionRequest(value: object): value is AdminUpdatePromotionRequest {
    return true;
}

export function AdminUpdatePromotionRequestFromJSON(json: any): AdminUpdatePromotionRequest {
    return AdminUpdatePromotionRequestFromJSONTyped(json, false);
}

export function AdminUpdatePromotionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUpdatePromotionRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'] == null ? undefined : CodeFromJSON(json['code']),
        'title': json['title'] == null ? undefined : TitleFromJSON(json['title']),
        'percentOff': json['percent_off'] == null ? undefined : PercentOffFromJSON(json['percent_off']),
        'pricingModels': json['pricing_models'] == null ? undefined : PricingModelsFromJSON(json['pricing_models']),
        'startsAt': json['starts_at'] == null ? undefined : StartsAtFromJSON(json['starts_at']),
        'endsAt': json['ends_at'] == null ? undefined : EndsAtFromJSON(json['ends_at']),
        'enabled': json['enabled'] == null ? undefined : EnabledFromJSON(json['enabled']),
    };
}

  export function AdminUpdatePromotionRequestToJSON(json: any): AdminUpdatePromotionRequest {
      return AdminUpdatePromotionRequestToJSONTyped(json, false);
  }

  export function AdminUpdatePromotionRequestToJSONTyped(value?: AdminUpdatePromotionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': CodeToJSON(value['code']),
        'title': TitleToJSON(value['title']),
        'percent_off': PercentOffToJSON(value['percentOff']),
        'pricing_models': PricingModelsToJSON(value['pricingModels']),
        'starts_at': StartsAtToJSON(value['startsAt']),
        'ends_at': EndsAtToJSON(value['endsAt']),
        'enabled': EnabledToJSON(value['enabled']),
    };
}

