/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSavePricingGroupRevisionsRequestPricingGroup } from './AdminSavePricingGroupRevisionsRequestPricingGroup';
import {
    AdminSavePricingGroupRevisionsRequestPricingGroupFromJSON,
    AdminSavePricingGroupRevisionsRequestPricingGroupFromJSONTyped,
    AdminSavePricingGroupRevisionsRequestPricingGroupToJSON,
    AdminSavePricingGroupRevisionsRequestPricingGroupToJSONTyped,
} from './AdminSavePricingGroupRevisionsRequestPricingGroup';
import type { AdminSavePricingGroupRevisionsRequestTokenUsageGroup } from './AdminSavePricingGroupRevisionsRequestTokenUsageGroup';
import {
    AdminSavePricingGroupRevisionsRequestTokenUsageGroupFromJSON,
    AdminSavePricingGroupRevisionsRequestTokenUsageGroupFromJSONTyped,
    AdminSavePricingGroupRevisionsRequestTokenUsageGroupToJSON,
    AdminSavePricingGroupRevisionsRequestTokenUsageGroupToJSONTyped,
} from './AdminSavePricingGroupRevisionsRequestTokenUsageGroup';

/**
 * 
 * @export
 * @interface AdminSavePricingGroupRevisionsRequest
 */
export interface AdminSavePricingGroupRevisionsRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {AdminSavePricingGroupRevisionsRequestPricingGroup}
     * @memberof AdminSavePricingGroupRevisionsRequest
     */
    pricingGroup?: AdminSavePricingGroupRevisionsRequestPricingGroup;
    /**
     * 
     * @type {AdminSavePricingGroupRevisionsRequestTokenUsageGroup}
     * @memberof AdminSavePricingGroupRevisionsRequest
     */
    tokenUsageGroup?: AdminSavePricingGroupRevisionsRequestTokenUsageGroup;
}

/**
 * Check if a given object implements the AdminSavePricingGroupRevisionsRequest interface.
 */
export function instanceOfAdminSavePricingGroupRevisionsRequest(value: object): value is AdminSavePricingGroupRevisionsRequest {
    return true;
}

export function AdminSavePricingGroupRevisionsRequestFromJSON(json: any): AdminSavePricingGroupRevisionsRequest {
    return AdminSavePricingGroupRevisionsRequestFromJSONTyped(json, false);
}

export function AdminSavePricingGroupRevisionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSavePricingGroupRevisionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'pricingGroup': json['pricing_group'] == null ? undefined : AdminSavePricingGroupRevisionsRequestPricingGroupFromJSON(json['pricing_group']),
        'tokenUsageGroup': json['token_usage_group'] == null ? undefined : AdminSavePricingGroupRevisionsRequestTokenUsageGroupFromJSON(json['token_usage_group']),
    };
}

  export function AdminSavePricingGroupRevisionsRequestToJSON(json: any): AdminSavePricingGroupRevisionsRequest {
      return AdminSavePricingGroupRevisionsRequestToJSONTyped(json, false);
  }

  export function AdminSavePricingGroupRevisionsRequestToJSONTyped(value?: AdminSavePricingGroupRevisionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'pricing_group': AdminSavePricingGroupRevisionsRequestPricingGroupToJSON(value['pricingGroup']),
        'token_usage_group': AdminSavePricingGroupRevisionsRequestTokenUsageGroupToJSON(value['tokenUsageGroup']),
    };
}

