/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminPromotionResponse
 */
export interface AdminPromotionResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminPromotionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPromotionResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPromotionResponse
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof AdminPromotionResponse
     */
    percentOff: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminPromotionResponse
     */
    pricingModels: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof AdminPromotionResponse
     */
    startsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminPromotionResponse
     */
    endsAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AdminPromotionResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminPromotionResponse
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminPromotionResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminPromotionResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AdminPromotionResponse interface.
 */
export function instanceOfAdminPromotionResponse(value: object): value is AdminPromotionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('percentOff' in value) || value['percentOff'] === undefined) return false;
    if (!('pricingModels' in value) || value['pricingModels'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AdminPromotionResponseFromJSON(json: any): AdminPromotionResponse {
    return AdminPromotionResponseFromJSONTyped(json, false);
}

export function AdminPromotionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPromotionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'title': json['title'],
        'percentOff': json['percent_off'],
        'pricingModels': json['pricing_models'],
        'startsAt': (new Date(json['starts_at'])),
        'endsAt': (new Date(json['ends_at'])),
        'enabled': json['enabled'],
        'active': json['active'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function AdminPromotionResponseToJSON(json: any): AdminPromotionResponse {
      return AdminPromotionResponseToJSONTyped(json, false);
  }

  export function AdminPromotionResponseToJSONTyped(value?: AdminPromotionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'title': value['title'],
        'percent_off': value['percentOff'],
        'pricing_models': value['pricingModels'],
        'starts_at': ((value['startsAt']).toISOString()),
        'ends_at': ((value['endsAt']).toISOString()),
        'enabled': value['enabled'],
        'active': value['active'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

