/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicUserPreview } from './PublicUserPreview';
import {
    PublicUserPreviewFromJSON,
    PublicUserPreviewFromJSONTyped,
    PublicUserPreviewToJSON,
    PublicUserPreviewToJSONTyped,
} from './PublicUserPreview';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';
import type { BadgeModel } from './BadgeModel';
import {
    BadgeModelFromJSON,
    BadgeModelFromJSONTyped,
    BadgeModelToJSON,
    BadgeModelToJSONTyped,
} from './BadgeModel';

/**
 * 
 * @export
 * @interface BadgeAwardedNotification
 */
export interface BadgeAwardedNotification {
    /**
     * 
     * @type {string}
     * @memberof BadgeAwardedNotification
     */
    id: string;
    /**
     * 
     * @type {NotificationType}
     * @memberof BadgeAwardedNotification
     */
    notificationType?: NotificationType;
    /**
     * 
     * @type {boolean}
     * @memberof BadgeAwardedNotification
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof BadgeAwardedNotification
     */
    createdAt: Date;
    /**
     * 
     * @type {PublicUserPreview}
     * @memberof BadgeAwardedNotification
     */
    sender?: PublicUserPreview | null;
    /**
     * 
     * @type {BadgeModel}
     * @memberof BadgeAwardedNotification
     */
    badge: BadgeModel;
    /**
     * 
     * @type {string}
     * @memberof BadgeAwardedNotification
     */
    sourceEventId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BadgeAwardedNotification
     */
    sourceEventName?: string | null;
}



/**
 * Check if a given object implements the BadgeAwardedNotification interface.
 */
export function instanceOfBadgeAwardedNotification(value: object): value is BadgeAwardedNotification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('badge' in value) || value['badge'] === undefined) return false;
    return true;
}

export function BadgeAwardedNotificationFromJSON(json: any): BadgeAwardedNotification {
    return BadgeAwardedNotificationFromJSONTyped(json, false);
}

export function BadgeAwardedNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeAwardedNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'notificationType': json['notification_type'] == null ? undefined : NotificationTypeFromJSON(json['notification_type']),
        'isRead': json['is_read'],
        'createdAt': (new Date(json['created_at'])),
        'sender': json['sender'] == null ? undefined : PublicUserPreviewFromJSON(json['sender']),
        'badge': BadgeModelFromJSON(json['badge']),
        'sourceEventId': json['source_event_id'] == null ? undefined : json['source_event_id'],
        'sourceEventName': json['source_event_name'] == null ? undefined : json['source_event_name'],
    };
}

  export function BadgeAwardedNotificationToJSON(json: any): BadgeAwardedNotification {
      return BadgeAwardedNotificationToJSONTyped(json, false);
  }

  export function BadgeAwardedNotificationToJSONTyped(value?: BadgeAwardedNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'notification_type': NotificationTypeToJSON(value['notificationType']),
        'is_read': value['isRead'],
        'created_at': ((value['createdAt']).toISOString()),
        'sender': PublicUserPreviewToJSON(value['sender']),
        'badge': BadgeModelToJSON(value['badge']),
        'source_event_id': value['sourceEventId'],
        'source_event_name': value['sourceEventName'],
    };
}

