/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlacklistTarget = {
    Character: 'character',
    Picture: 'picture',
    Video: 'video',
    Story: 'story',
    GameAdventure: 'game_adventure',
    User: 'user'
} as const;
export type BlacklistTarget = typeof BlacklistTarget[keyof typeof BlacklistTarget];


export function instanceOfBlacklistTarget(value: any): boolean {
    for (const key in BlacklistTarget) {
        if (Object.prototype.hasOwnProperty.call(BlacklistTarget, key)) {
            if (BlacklistTarget[key as keyof typeof BlacklistTarget] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlacklistTargetFromJSON(json: any): BlacklistTarget {
    return BlacklistTargetFromJSONTyped(json, false);
}

export function BlacklistTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlacklistTarget {
    return json as BlacklistTarget;
}

export function BlacklistTargetToJSON(value?: BlacklistTarget | null): any {
    return value as any;
}

export function BlacklistTargetToJSONTyped(value: any, ignoreDiscriminator: boolean): BlacklistTarget {
    return value as BlacklistTarget;
}

