/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlacklistReason } from './BlacklistReason';
import {
    BlacklistReasonFromJSON,
    BlacklistReasonFromJSONTyped,
    BlacklistReasonToJSON,
    BlacklistReasonToJSONTyped,
} from './BlacklistReason';
import type { BlacklistTarget } from './BlacklistTarget';
import {
    BlacklistTargetFromJSON,
    BlacklistTargetFromJSONTyped,
    BlacklistTargetToJSON,
    BlacklistTargetToJSONTyped,
} from './BlacklistTarget';
import type { MediaOrigin } from './MediaOrigin';
import {
    MediaOriginFromJSON,
    MediaOriginFromJSONTyped,
    MediaOriginToJSON,
    MediaOriginToJSONTyped,
} from './MediaOrigin';

/**
 * 
 * @export
 * @interface BlacklistCard
 */
export interface BlacklistCard {
    /**
     * 
     * @type {BlacklistReason}
     * @memberof BlacklistCard
     */
    reason: BlacklistReason;
    /**
     * 
     * @type {string}
     * @memberof BlacklistCard
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlacklistCard
     */
    prompt?: string | null;
    /**
     * 
     * @type {MediaOrigin}
     * @memberof BlacklistCard
     */
    origin?: MediaOrigin | null;
    /**
     * 
     * @type {BlacklistTarget}
     * @memberof BlacklistCard
     */
    targetType: BlacklistTarget;
    /**
     * 
     * @type {Date}
     * @memberof BlacklistCard
     */
    blacklistedAt: Date;
}



/**
 * Check if a given object implements the BlacklistCard interface.
 */
export function instanceOfBlacklistCard(value: object): value is BlacklistCard {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('targetType' in value) || value['targetType'] === undefined) return false;
    if (!('blacklistedAt' in value) || value['blacklistedAt'] === undefined) return false;
    return true;
}

export function BlacklistCardFromJSON(json: any): BlacklistCard {
    return BlacklistCardFromJSONTyped(json, false);
}

export function BlacklistCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlacklistCard {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': BlacklistReasonFromJSON(json['reason']),
        'message': json['message'] == null ? undefined : json['message'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'origin': json['origin'] == null ? undefined : MediaOriginFromJSON(json['origin']),
        'targetType': BlacklistTargetFromJSON(json['target_type']),
        'blacklistedAt': (new Date(json['blacklisted_at'])),
    };
}

  export function BlacklistCardToJSON(json: any): BlacklistCard {
      return BlacklistCardToJSONTyped(json, false);
  }

  export function BlacklistCardToJSONTyped(value?: BlacklistCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': BlacklistReasonToJSON(value['reason']),
        'message': value['message'],
        'prompt': value['prompt'],
        'origin': MediaOriginToJSON(value['origin']),
        'target_type': BlacklistTargetToJSON(value['targetType']),
        'blacklisted_at': ((value['blacklistedAt']).toISOString()),
    };
}

