/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlacklistReason } from './BlacklistReason';
import {
    BlacklistReasonFromJSON,
    BlacklistReasonFromJSONTyped,
    BlacklistReasonToJSON,
    BlacklistReasonToJSONTyped,
} from './BlacklistReason';

/**
 * 
 * @export
 * @interface BlacklistRequest
 */
export interface BlacklistRequest {
    /**
     * 
     * @type {BlacklistReason}
     * @memberof BlacklistRequest
     */
    reason: BlacklistReason;
    /**
     * 
     * @type {string}
     * @memberof BlacklistRequest
     */
    message?: string | null;
}



/**
 * Check if a given object implements the BlacklistRequest interface.
 */
export function instanceOfBlacklistRequest(value: object): value is BlacklistRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function BlacklistRequestFromJSON(json: any): BlacklistRequest {
    return BlacklistRequestFromJSONTyped(json, false);
}

export function BlacklistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlacklistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': BlacklistReasonFromJSON(json['reason']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

  export function BlacklistRequestToJSON(json: any): BlacklistRequest {
      return BlacklistRequestToJSONTyped(json, false);
  }

  export function BlacklistRequestToJSONTyped(value?: BlacklistRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': BlacklistReasonToJSON(value['reason']),
        'message': value['message'],
    };
}

