/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Code1
 */
export interface Code1 {
}

/**
 * Check if a given object implements the Code1 interface.
 */
export function instanceOfCode1(value: object): value is Code1 {
    return true;
}

export function Code1FromJSON(json: any): Code1 {
    return Code1FromJSONTyped(json, false);
}

export function Code1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Code1 {
    return json;
}

  export function Code1ToJSON(json: any): Code1 {
      return Code1ToJSONTyped(json, false);
  }

  export function Code1ToJSONTyped(value?: Code1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

