/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentType } from './ContentType';
import {
    ContentTypeFromJSON,
    ContentTypeFromJSONTyped,
    ContentTypeToJSON,
    ContentTypeToJSONTyped,
} from './ContentType';

/**
 * 
 * @export
 * @interface ContentOrigin
 */
export interface ContentOrigin {
    /**
     * 
     * @type {ContentType}
     * @memberof ContentOrigin
     */
    contentType: ContentType;
    /**
     * 
     * @type {string}
     * @memberof ContentOrigin
     */
    contentId: string;
    /**
     * 
     * @type {string}
     * @memberof ContentOrigin
     */
    postId: string | null;
}



/**
 * Check if a given object implements the ContentOrigin interface.
 */
export function instanceOfContentOrigin(value: object): value is ContentOrigin {
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('contentId' in value) || value['contentId'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function ContentOriginFromJSON(json: any): ContentOrigin {
    return ContentOriginFromJSONTyped(json, false);
}

export function ContentOriginFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentOrigin {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': ContentTypeFromJSON(json['content_type']),
        'contentId': json['content_id'],
        'postId': json['post_id'],
    };
}

  export function ContentOriginToJSON(json: any): ContentOrigin {
      return ContentOriginToJSONTyped(json, false);
  }

  export function ContentOriginToJSONTyped(value?: ContentOrigin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': ContentTypeToJSON(value['contentType']),
        'content_id': value['contentId'],
        'post_id': value['postId'],
    };
}

