/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Funnel milestones reported to ExoClick as goals.
 * 
 * These used to fire from the browser through ExoClick's tag script, which pings a
 * dozen ExoClick alias hosts; Malwarebytes blocks one of them and ad-network AV checks
 * then flag the landing page. The goals now leave from the API only.
 * @export
 */
export const ConversionEvent = {
    Visit: 'visit',
    FirstBabeCreated: 'first_babe_created',
    ChatLimitReached: 'chat_limit_reached',
    SubscriptionPageSeen: 'subscription_page_seen',
    StoryFinished: 'story_finished',
    TransactionDeclined: 'transaction_declined'
} as const;
export type ConversionEvent = typeof ConversionEvent[keyof typeof ConversionEvent];


export function instanceOfConversionEvent(value: any): boolean {
    for (const key in ConversionEvent) {
        if (Object.prototype.hasOwnProperty.call(ConversionEvent, key)) {
            if (ConversionEvent[key as keyof typeof ConversionEvent] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConversionEventFromJSON(json: any): ConversionEvent {
    return ConversionEventFromJSONTyped(json, false);
}

export function ConversionEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversionEvent {
    return json as ConversionEvent;
}

export function ConversionEventToJSON(value?: ConversionEvent | null): any {
    return value as any;
}

export function ConversionEventToJSONTyped(value: any, ignoreDiscriminator: boolean): ConversionEvent {
    return value as ConversionEvent;
}

