/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateAnonymousConversationMessageRequest } from './CreateAnonymousConversationMessageRequest';
import {
    CreateAnonymousConversationMessageRequestFromJSON,
    CreateAnonymousConversationMessageRequestFromJSONTyped,
    CreateAnonymousConversationMessageRequestToJSON,
    CreateAnonymousConversationMessageRequestToJSONTyped,
} from './CreateAnonymousConversationMessageRequest';

/**
 * 
 * @export
 * @interface CreateAnonymousConversationRequest
 */
export interface CreateAnonymousConversationRequest {
    /**
     * 
     * @type {Array<CreateAnonymousConversationMessageRequest>}
     * @memberof CreateAnonymousConversationRequest
     */
    messages?: Array<CreateAnonymousConversationMessageRequest>;
}

/**
 * Check if a given object implements the CreateAnonymousConversationRequest interface.
 */
export function instanceOfCreateAnonymousConversationRequest(value: object): value is CreateAnonymousConversationRequest {
    return true;
}

export function CreateAnonymousConversationRequestFromJSON(json: any): CreateAnonymousConversationRequest {
    return CreateAnonymousConversationRequestFromJSONTyped(json, false);
}

export function CreateAnonymousConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnonymousConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(CreateAnonymousConversationMessageRequestFromJSON)),
    };
}

  export function CreateAnonymousConversationRequestToJSON(json: any): CreateAnonymousConversationRequest {
      return CreateAnonymousConversationRequestToJSONTyped(json, false);
  }

  export function CreateAnonymousConversationRequestToJSONTyped(value?: CreateAnonymousConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(CreateAnonymousConversationMessageRequestToJSON)),
    };
}

