/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatRole } from './ChatRole';
import {
    ChatRoleFromJSON,
    ChatRoleFromJSONTyped,
    ChatRoleToJSON,
    ChatRoleToJSONTyped,
} from './ChatRole';
import type { MessageType } from './MessageType';
import {
    MessageTypeFromJSON,
    MessageTypeFromJSONTyped,
    MessageTypeToJSON,
    MessageTypeToJSONTyped,
} from './MessageType';

/**
 * One imported message. Media arrives as the URL the roleplay showed the visitor.
 * 
 * The roleplay renders its media straight from storage, so nothing was ever written to
 * generated_picture / generated_video / generated_audio and there is no id to send. The
 * import creates those rows from the file the URL points at - see AnonymousChatService.
 * @export
 * @interface CreateAnonymousConversationMessageRequest
 */
export interface CreateAnonymousConversationMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAnonymousConversationMessageRequest
     */
    content: string;
    /**
     * 
     * @type {ChatRole}
     * @memberof CreateAnonymousConversationMessageRequest
     */
    role: ChatRole;
    /**
     * 
     * @type {MessageType}
     * @memberof CreateAnonymousConversationMessageRequest
     */
    type?: MessageType;
    /**
     * 
     * @type {string}
     * @memberof CreateAnonymousConversationMessageRequest
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAnonymousConversationMessageRequest
     */
    videoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAnonymousConversationMessageRequest
     */
    audioUrl?: string | null;
}



/**
 * Check if a given object implements the CreateAnonymousConversationMessageRequest interface.
 */
export function instanceOfCreateAnonymousConversationMessageRequest(value: object): value is CreateAnonymousConversationMessageRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CreateAnonymousConversationMessageRequestFromJSON(json: any): CreateAnonymousConversationMessageRequest {
    return CreateAnonymousConversationMessageRequestFromJSONTyped(json, false);
}

export function CreateAnonymousConversationMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnonymousConversationMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'role': ChatRoleFromJSON(json['role']),
        'type': json['type'] == null ? undefined : MessageTypeFromJSON(json['type']),
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'videoUrl': json['video_url'] == null ? undefined : json['video_url'],
        'audioUrl': json['audio_url'] == null ? undefined : json['audio_url'],
    };
}

  export function CreateAnonymousConversationMessageRequestToJSON(json: any): CreateAnonymousConversationMessageRequest {
      return CreateAnonymousConversationMessageRequestToJSONTyped(json, false);
  }

  export function CreateAnonymousConversationMessageRequestToJSONTyped(value?: CreateAnonymousConversationMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'role': ChatRoleToJSON(value['role']),
        'type': MessageTypeToJSON(value['type']),
        'image_url': value['imageUrl'],
        'video_url': value['videoUrl'],
        'audio_url': value['audioUrl'],
    };
}

