/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscountOriginalPrice
 */
export interface DiscountOriginalPrice {
}

/**
 * Check if a given object implements the DiscountOriginalPrice interface.
 */
export function instanceOfDiscountOriginalPrice(value: object): value is DiscountOriginalPrice {
    return true;
}

export function DiscountOriginalPriceFromJSON(json: any): DiscountOriginalPrice {
    return DiscountOriginalPriceFromJSONTyped(json, false);
}

export function DiscountOriginalPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountOriginalPrice {
    return json;
}

  export function DiscountOriginalPriceToJSON(json: any): DiscountOriginalPrice {
      return DiscountOriginalPriceToJSONTyped(json, false);
  }

  export function DiscountOriginalPriceToJSONTyped(value?: DiscountOriginalPrice | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

