/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisplayDiscount
 */
export interface DisplayDiscount {
}

/**
 * Check if a given object implements the DisplayDiscount interface.
 */
export function instanceOfDisplayDiscount(value: object): value is DisplayDiscount {
    return true;
}

export function DisplayDiscountFromJSON(json: any): DisplayDiscount {
    return DisplayDiscountFromJSONTyped(json, false);
}

export function DisplayDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisplayDiscount {
    return json;
}

  export function DisplayDiscountToJSON(json: any): DisplayDiscount {
      return DisplayDiscountToJSONTyped(json, false);
  }

  export function DisplayDiscountToJSONTyped(value?: DisplayDiscount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

