/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownscaleRequest
 */
export interface DownscaleRequest {
    /**
     * 
     * @type {string}
     * @memberof DownscaleRequest
     */
    source: string;
}

/**
 * Check if a given object implements the DownscaleRequest interface.
 */
export function instanceOfDownscaleRequest(value: object): value is DownscaleRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function DownscaleRequestFromJSON(json: any): DownscaleRequest {
    return DownscaleRequestFromJSONTyped(json, false);
}

export function DownscaleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownscaleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
    };
}

  export function DownscaleRequestToJSON(json: any): DownscaleRequest {
      return DownscaleRequestToJSONTyped(json, false);
  }

  export function DownscaleRequestToJSONTyped(value?: DownscaleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
    };
}

