/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndsAt
 */
export interface EndsAt {
}

/**
 * Check if a given object implements the EndsAt interface.
 */
export function instanceOfEndsAt(value: object): value is EndsAt {
    return true;
}

export function EndsAtFromJSON(json: any): EndsAt {
    return EndsAtFromJSONTyped(json, false);
}

export function EndsAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndsAt {
    return json;
}

  export function EndsAtToJSON(json: any): EndsAt {
      return EndsAtToJSONTyped(json, false);
  }

  export function EndsAtToJSONTyped(value?: EndsAt | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

