/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicUserPreview } from './PublicUserPreview';
import {
    PublicUserPreviewFromJSON,
    PublicUserPreviewFromJSONTyped,
    PublicUserPreviewToJSON,
    PublicUserPreviewToJSONTyped,
} from './PublicUserPreview';
import type { EventResultType } from './EventResultType';
import {
    EventResultTypeFromJSON,
    EventResultTypeFromJSONTyped,
    EventResultTypeToJSON,
    EventResultTypeToJSONTyped,
} from './EventResultType';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';

/**
 * 
 * @export
 * @interface EventResultNotification
 */
export interface EventResultNotification {
    /**
     * 
     * @type {NotificationType}
     * @memberof EventResultNotification
     */
    notificationType?: NotificationType;
    /**
     * 
     * @type {boolean}
     * @memberof EventResultNotification
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof EventResultNotification
     */
    createdAt: Date;
    /**
     * 
     * @type {PublicUserPreview}
     * @memberof EventResultNotification
     */
    sender?: PublicUserPreview | null;
    /**
     * 
     * @type {string}
     * @memberof EventResultNotification
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof EventResultNotification
     */
    eventName: string;
    /**
     * 
     * @type {string}
     * @memberof EventResultNotification
     */
    eventBackgroundImage?: string;
    /**
     * 
     * @type {EventResultType}
     * @memberof EventResultNotification
     */
    resultType: EventResultType;
    /**
     * 
     * @type {number}
     * @memberof EventResultNotification
     */
    rank?: number | null;
}



/**
 * Check if a given object implements the EventResultNotification interface.
 */
export function instanceOfEventResultNotification(value: object): value is EventResultNotification {
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('eventName' in value) || value['eventName'] === undefined) return false;
    if (!('resultType' in value) || value['resultType'] === undefined) return false;
    return true;
}

export function EventResultNotificationFromJSON(json: any): EventResultNotification {
    return EventResultNotificationFromJSONTyped(json, false);
}

export function EventResultNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventResultNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationType': json['notification_type'] == null ? undefined : NotificationTypeFromJSON(json['notification_type']),
        'isRead': json['is_read'],
        'createdAt': (new Date(json['created_at'])),
        'sender': json['sender'] == null ? undefined : PublicUserPreviewFromJSON(json['sender']),
        'eventId': json['event_id'],
        'eventName': json['event_name'],
        'eventBackgroundImage': json['event_background_image'] == null ? undefined : json['event_background_image'],
        'resultType': EventResultTypeFromJSON(json['result_type']),
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

  export function EventResultNotificationToJSON(json: any): EventResultNotification {
      return EventResultNotificationToJSONTyped(json, false);
  }

  export function EventResultNotificationToJSONTyped(value?: EventResultNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notification_type': NotificationTypeToJSON(value['notificationType']),
        'is_read': value['isRead'],
        'created_at': ((value['createdAt']).toISOString()),
        'sender': PublicUserPreviewToJSON(value['sender']),
        'event_id': value['eventId'],
        'event_name': value['eventName'],
        'event_background_image': value['eventBackgroundImage'],
        'result_type': EventResultTypeToJSON(value['resultType']),
        'rank': value['rank'],
    };
}

