/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicUserPreview } from './PublicUserPreview';
import {
    PublicUserPreviewFromJSON,
    PublicUserPreviewFromJSONTyped,
    PublicUserPreviewToJSON,
    PublicUserPreviewToJSONTyped,
} from './PublicUserPreview';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';

/**
 * 
 * @export
 * @interface EventEndedNotification
 */
export interface EventEndedNotification {
    /**
     * 
     * @type {NotificationType}
     * @memberof EventEndedNotification
     */
    notificationType?: NotificationType;
    /**
     * 
     * @type {boolean}
     * @memberof EventEndedNotification
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof EventEndedNotification
     */
    createdAt: Date;
    /**
     * 
     * @type {PublicUserPreview}
     * @memberof EventEndedNotification
     */
    sender?: PublicUserPreview | null;
    /**
     * 
     * @type {string}
     * @memberof EventEndedNotification
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof EventEndedNotification
     */
    eventName: string;
    /**
     * 
     * @type {string}
     * @memberof EventEndedNotification
     */
    eventBackgroundImage?: string;
}



/**
 * Check if a given object implements the EventEndedNotification interface.
 */
export function instanceOfEventEndedNotification(value: object): value is EventEndedNotification {
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('eventName' in value) || value['eventName'] === undefined) return false;
    return true;
}

export function EventEndedNotificationFromJSON(json: any): EventEndedNotification {
    return EventEndedNotificationFromJSONTyped(json, false);
}

export function EventEndedNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventEndedNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationType': json['notification_type'] == null ? undefined : NotificationTypeFromJSON(json['notification_type']),
        'isRead': json['is_read'],
        'createdAt': (new Date(json['created_at'])),
        'sender': json['sender'] == null ? undefined : PublicUserPreviewFromJSON(json['sender']),
        'eventId': json['event_id'],
        'eventName': json['event_name'],
        'eventBackgroundImage': json['event_background_image'] == null ? undefined : json['event_background_image'],
    };
}

  export function EventEndedNotificationToJSON(json: any): EventEndedNotification {
      return EventEndedNotificationToJSONTyped(json, false);
  }

  export function EventEndedNotificationToJSONTyped(value?: EventEndedNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notification_type': NotificationTypeToJSON(value['notificationType']),
        'is_read': value['isRead'],
        'created_at': ((value['createdAt']).toISOString()),
        'sender': PublicUserPreviewToJSON(value['sender']),
        'event_id': value['eventId'],
        'event_name': value['eventName'],
        'event_background_image': value['eventBackgroundImage'],
    };
}

