/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowNotificationState } from './FollowNotificationState';
import {
    FollowNotificationStateFromJSON,
    FollowNotificationStateFromJSONTyped,
    FollowNotificationStateToJSON,
    FollowNotificationStateToJSONTyped,
} from './FollowNotificationState';

/**
 * 
 * @export
 * @interface FollowNotificationStatesResponse
 */
export interface FollowNotificationStatesResponse {
    /**
     * 
     * @type {{ [key: string]: FollowNotificationState; }}
     * @memberof FollowNotificationStatesResponse
     */
    states: { [key: string]: FollowNotificationState; };
}

/**
 * Check if a given object implements the FollowNotificationStatesResponse interface.
 */
export function instanceOfFollowNotificationStatesResponse(value: object): value is FollowNotificationStatesResponse {
    if (!('states' in value) || value['states'] === undefined) return false;
    return true;
}

export function FollowNotificationStatesResponseFromJSON(json: any): FollowNotificationStatesResponse {
    return FollowNotificationStatesResponseFromJSONTyped(json, false);
}

export function FollowNotificationStatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowNotificationStatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'states': (mapValues(json['states'], FollowNotificationStateFromJSON)),
    };
}

  export function FollowNotificationStatesResponseToJSON(json: any): FollowNotificationStatesResponse {
      return FollowNotificationStatesResponseToJSONTyped(json, false);
  }

  export function FollowNotificationStatesResponseToJSONTyped(value?: FollowNotificationStatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'states': (mapValues(value['states'], FollowNotificationStateToJSON)),
    };
}

