/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FollowNotificationState = {
    All: 'all',
    None: 'none',
    Mixed: 'mixed'
} as const;
export type FollowNotificationState = typeof FollowNotificationState[keyof typeof FollowNotificationState];


export function instanceOfFollowNotificationState(value: any): boolean {
    for (const key in FollowNotificationState) {
        if (Object.prototype.hasOwnProperty.call(FollowNotificationState, key)) {
            if (FollowNotificationState[key as keyof typeof FollowNotificationState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FollowNotificationStateFromJSON(json: any): FollowNotificationState {
    return FollowNotificationStateFromJSONTyped(json, false);
}

export function FollowNotificationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowNotificationState {
    return json as FollowNotificationState;
}

export function FollowNotificationStateToJSON(value?: FollowNotificationState | null): any {
    return value as any;
}

export function FollowNotificationStateToJSONTyped(value: any, ignoreDiscriminator: boolean): FollowNotificationState {
    return value as FollowNotificationState;
}

