/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GalleryFolderCounts } from './GalleryFolderCounts';
import {
    GalleryFolderCountsFromJSON,
    GalleryFolderCountsFromJSONTyped,
    GalleryFolderCountsToJSON,
    GalleryFolderCountsToJSONTyped,
} from './GalleryFolderCounts';

/**
 * 
 * @export
 * @interface GalleryFolder
 */
export interface GalleryFolder {
    /**
     * 
     * @type {string}
     * @memberof GalleryFolder
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GalleryFolder
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GalleryFolder
     */
    color: string;
    /**
     * 
     * @type {Date}
     * @memberof GalleryFolder
     */
    createdAt: Date;
    /**
     * 
     * @type {GalleryFolderCounts}
     * @memberof GalleryFolder
     */
    counts: GalleryFolderCounts;
}

/**
 * Check if a given object implements the GalleryFolder interface.
 */
export function instanceOfGalleryFolder(value: object): value is GalleryFolder {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('counts' in value) || value['counts'] === undefined) return false;
    return true;
}

export function GalleryFolderFromJSON(json: any): GalleryFolder {
    return GalleryFolderFromJSONTyped(json, false);
}

export function GalleryFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleryFolder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
        'createdAt': (new Date(json['created_at'])),
        'counts': GalleryFolderCountsFromJSON(json['counts']),
    };
}

  export function GalleryFolderToJSON(json: any): GalleryFolder {
      return GalleryFolderToJSONTyped(json, false);
  }

  export function GalleryFolderToJSONTyped(value?: GalleryFolder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
        'created_at': ((value['createdAt']).toISOString()),
        'counts': GalleryFolderCountsToJSON(value['counts']),
    };
}

