/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GalleryFolderCounts
 */
export interface GalleryFolderCounts {
    /**
     * 
     * @type {number}
     * @memberof GalleryFolderCounts
     */
    picture?: number;
    /**
     * 
     * @type {number}
     * @memberof GalleryFolderCounts
     */
    video?: number;
    /**
     * 
     * @type {number}
     * @memberof GalleryFolderCounts
     */
    character?: number;
    /**
     * 
     * @type {number}
     * @memberof GalleryFolderCounts
     */
    story?: number;
    /**
     * 
     * @type {number}
     * @memberof GalleryFolderCounts
     */
    total?: number;
}

/**
 * Check if a given object implements the GalleryFolderCounts interface.
 */
export function instanceOfGalleryFolderCounts(value: object): value is GalleryFolderCounts {
    return true;
}

export function GalleryFolderCountsFromJSON(json: any): GalleryFolderCounts {
    return GalleryFolderCountsFromJSONTyped(json, false);
}

export function GalleryFolderCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleryFolderCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'picture': json['picture'] == null ? undefined : json['picture'],
        'video': json['video'] == null ? undefined : json['video'],
        'character': json['character'] == null ? undefined : json['character'],
        'story': json['story'] == null ? undefined : json['story'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

  export function GalleryFolderCountsToJSON(json: any): GalleryFolderCounts {
      return GalleryFolderCountsToJSONTyped(json, false);
  }

  export function GalleryFolderCountsToJSONTyped(value?: GalleryFolderCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'picture': value['picture'],
        'video': value['video'],
        'character': value['character'],
        'story': value['story'],
        'total': value['total'],
    };
}

