/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameAdventureSessionTargetProgress
 */
export interface GameAdventureSessionTargetProgress {
    /**
     * 
     * @type {string}
     * @memberof GameAdventureSessionTargetProgress
     */
    targetId: string;
    /**
     * 
     * @type {number}
     * @memberof GameAdventureSessionTargetProgress
     */
    score: number;
    /**
     * 
     * @type {number}
     * @memberof GameAdventureSessionTargetProgress
     */
    upperLimit: number;
    /**
     * 
     * @type {number}
     * @memberof GameAdventureSessionTargetProgress
     */
    lowerLimit: number;
    /**
     * 
     * @type {Date}
     * @memberof GameAdventureSessionTargetProgress
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GameAdventureSessionTargetProgress
     */
    condition?: string | null;
}

/**
 * Check if a given object implements the GameAdventureSessionTargetProgress interface.
 */
export function instanceOfGameAdventureSessionTargetProgress(value: object): value is GameAdventureSessionTargetProgress {
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('upperLimit' in value) || value['upperLimit'] === undefined) return false;
    if (!('lowerLimit' in value) || value['lowerLimit'] === undefined) return false;
    return true;
}

export function GameAdventureSessionTargetProgressFromJSON(json: any): GameAdventureSessionTargetProgress {
    return GameAdventureSessionTargetProgressFromJSONTyped(json, false);
}

export function GameAdventureSessionTargetProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureSessionTargetProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'targetId': json['target_id'],
        'score': json['score'],
        'upperLimit': json['upper_limit'],
        'lowerLimit': json['lower_limit'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'condition': json['condition'] == null ? undefined : json['condition'],
    };
}

  export function GameAdventureSessionTargetProgressToJSON(json: any): GameAdventureSessionTargetProgress {
      return GameAdventureSessionTargetProgressToJSONTyped(json, false);
  }

  export function GameAdventureSessionTargetProgressToJSONTyped(value?: GameAdventureSessionTargetProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_id': value['targetId'],
        'score': value['score'],
        'upper_limit': value['upperLimit'],
        'lower_limit': value['lowerLimit'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'condition': value['condition'],
    };
}

