/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameAdventureDifficulty = {
    Easy: 'easy',
    Normal: 'normal',
    Hard: 'hard'
} as const;
export type GameAdventureDifficulty = typeof GameAdventureDifficulty[keyof typeof GameAdventureDifficulty];


export function instanceOfGameAdventureDifficulty(value: any): boolean {
    for (const key in GameAdventureDifficulty) {
        if (Object.prototype.hasOwnProperty.call(GameAdventureDifficulty, key)) {
            if (GameAdventureDifficulty[key as keyof typeof GameAdventureDifficulty] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GameAdventureDifficultyFromJSON(json: any): GameAdventureDifficulty {
    return GameAdventureDifficultyFromJSONTyped(json, false);
}

export function GameAdventureDifficultyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureDifficulty {
    return json as GameAdventureDifficulty;
}

export function GameAdventureDifficultyToJSON(value?: GameAdventureDifficulty | null): any {
    return value as any;
}

export function GameAdventureDifficultyToJSONTyped(value: any, ignoreDiscriminator: boolean): GameAdventureDifficulty {
    return value as GameAdventureDifficulty;
}

