/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameAdventureTargetUpdate
 */
export interface GameAdventureTargetUpdate {
    /**
     * 
     * @type {string}
     * @memberof GameAdventureTargetUpdate
     */
    condition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameAdventureTargetUpdate
     */
    goodMoves?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameAdventureTargetUpdate
     */
    badMoves?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GameAdventureTargetUpdate
     */
    upperLimit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GameAdventureTargetUpdate
     */
    lowerLimit?: number | null;
}

/**
 * Check if a given object implements the GameAdventureTargetUpdate interface.
 */
export function instanceOfGameAdventureTargetUpdate(value: object): value is GameAdventureTargetUpdate {
    return true;
}

export function GameAdventureTargetUpdateFromJSON(json: any): GameAdventureTargetUpdate {
    return GameAdventureTargetUpdateFromJSONTyped(json, false);
}

export function GameAdventureTargetUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureTargetUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'condition': json['condition'] == null ? undefined : json['condition'],
        'goodMoves': json['good_moves'] == null ? undefined : json['good_moves'],
        'badMoves': json['bad_moves'] == null ? undefined : json['bad_moves'],
        'upperLimit': json['upper_limit'] == null ? undefined : json['upper_limit'],
        'lowerLimit': json['lower_limit'] == null ? undefined : json['lower_limit'],
    };
}

  export function GameAdventureTargetUpdateToJSON(json: any): GameAdventureTargetUpdate {
      return GameAdventureTargetUpdateToJSONTyped(json, false);
  }

  export function GameAdventureTargetUpdateToJSONTyped(value?: GameAdventureTargetUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condition': value['condition'],
        'good_moves': value['goodMoves'],
        'bad_moves': value['badMoves'],
        'upper_limit': value['upperLimit'],
        'lower_limit': value['lowerLimit'],
    };
}

