/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameAdventureSessionStatus } from './GameAdventureSessionStatus';
import {
    GameAdventureSessionStatusFromJSON,
    GameAdventureSessionStatusFromJSONTyped,
    GameAdventureSessionStatusToJSON,
    GameAdventureSessionStatusToJSONTyped,
} from './GameAdventureSessionStatus';
import type { GameAdventureSessionTargetProgress } from './GameAdventureSessionTargetProgress';
import {
    GameAdventureSessionTargetProgressFromJSON,
    GameAdventureSessionTargetProgressFromJSONTyped,
    GameAdventureSessionTargetProgressToJSON,
    GameAdventureSessionTargetProgressToJSONTyped,
} from './GameAdventureSessionTargetProgress';
import type { LLM } from './LLM';
import {
    LLMFromJSON,
    LLMFromJSONTyped,
    LLMToJSON,
    LLMToJSONTyped,
} from './LLM';

/**
 * 
 * @export
 * @interface GameAdventureSessionResponse
 */
export interface GameAdventureSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof GameAdventureSessionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GameAdventureSessionResponse
     */
    gameAdventureId: string;
    /**
     * 
     * @type {string}
     * @memberof GameAdventureSessionResponse
     */
    gameAdventureVersionId: string;
    /**
     * 
     * @type {GameAdventureSessionStatus}
     * @memberof GameAdventureSessionResponse
     */
    status: GameAdventureSessionStatus;
    /**
     * 
     * @type {boolean}
     * @memberof GameAdventureSessionResponse
     */
    isPreview: boolean;
    /**
     * 
     * @type {LLM}
     * @memberof GameAdventureSessionResponse
     */
    llmModel?: LLM | null;
    /**
     * 
     * @type {Date}
     * @memberof GameAdventureSessionResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GameAdventureSessionResponse
     */
    newerVersionExists: boolean;
    /**
     * 
     * @type {Array<GameAdventureSessionTargetProgress>}
     * @memberof GameAdventureSessionResponse
     */
    targets: Array<GameAdventureSessionTargetProgress>;
}



/**
 * Check if a given object implements the GameAdventureSessionResponse interface.
 */
export function instanceOfGameAdventureSessionResponse(value: object): value is GameAdventureSessionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('gameAdventureId' in value) || value['gameAdventureId'] === undefined) return false;
    if (!('gameAdventureVersionId' in value) || value['gameAdventureVersionId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('isPreview' in value) || value['isPreview'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('newerVersionExists' in value) || value['newerVersionExists'] === undefined) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    return true;
}

export function GameAdventureSessionResponseFromJSON(json: any): GameAdventureSessionResponse {
    return GameAdventureSessionResponseFromJSONTyped(json, false);
}

export function GameAdventureSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'gameAdventureId': json['game_adventure_id'],
        'gameAdventureVersionId': json['game_adventure_version_id'],
        'status': GameAdventureSessionStatusFromJSON(json['status']),
        'isPreview': json['is_preview'],
        'llmModel': json['llm_model'] == null ? undefined : LLMFromJSON(json['llm_model']),
        'createdAt': (new Date(json['created_at'])),
        'newerVersionExists': json['newer_version_exists'],
        'targets': ((json['targets'] as Array<any>).map(GameAdventureSessionTargetProgressFromJSON)),
    };
}

  export function GameAdventureSessionResponseToJSON(json: any): GameAdventureSessionResponse {
      return GameAdventureSessionResponseToJSONTyped(json, false);
  }

  export function GameAdventureSessionResponseToJSONTyped(value?: GameAdventureSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'game_adventure_id': value['gameAdventureId'],
        'game_adventure_version_id': value['gameAdventureVersionId'],
        'status': GameAdventureSessionStatusToJSON(value['status']),
        'is_preview': value['isPreview'],
        'llm_model': LLMToJSON(value['llmModel']),
        'created_at': ((value['createdAt']).toISOString()),
        'newer_version_exists': value['newerVersionExists'],
        'targets': ((value['targets'] as Array<any>).map(GameAdventureSessionTargetProgressToJSON)),
    };
}

