/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameAdventureStatus = {
    Draft: 'draft',
    Published: 'published'
} as const;
export type GameAdventureStatus = typeof GameAdventureStatus[keyof typeof GameAdventureStatus];


export function instanceOfGameAdventureStatus(value: any): boolean {
    for (const key in GameAdventureStatus) {
        if (Object.prototype.hasOwnProperty.call(GameAdventureStatus, key)) {
            if (GameAdventureStatus[key as keyof typeof GameAdventureStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GameAdventureStatusFromJSON(json: any): GameAdventureStatus {
    return GameAdventureStatusFromJSONTyped(json, false);
}

export function GameAdventureStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureStatus {
    return json as GameAdventureStatus;
}

export function GameAdventureStatusToJSON(value?: GameAdventureStatus | null): any {
    return value as any;
}

export function GameAdventureStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): GameAdventureStatus {
    return value as GameAdventureStatus;
}

