/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameAdventureSessionResponse } from './GameAdventureSessionResponse';
import {
    GameAdventureSessionResponseFromJSON,
    GameAdventureSessionResponseFromJSONTyped,
    GameAdventureSessionResponseToJSON,
    GameAdventureSessionResponseToJSONTyped,
} from './GameAdventureSessionResponse';

/**
 * 
 * @export
 * @interface GameAdventureSessionListResponse
 */
export interface GameAdventureSessionListResponse {
    /**
     * 
     * @type {Array<GameAdventureSessionResponse>}
     * @memberof GameAdventureSessionListResponse
     */
    sessions: Array<GameAdventureSessionResponse>;
}

/**
 * Check if a given object implements the GameAdventureSessionListResponse interface.
 */
export function instanceOfGameAdventureSessionListResponse(value: object): value is GameAdventureSessionListResponse {
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function GameAdventureSessionListResponseFromJSON(json: any): GameAdventureSessionListResponse {
    return GameAdventureSessionListResponseFromJSONTyped(json, false);
}

export function GameAdventureSessionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureSessionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': ((json['sessions'] as Array<any>).map(GameAdventureSessionResponseFromJSON)),
    };
}

  export function GameAdventureSessionListResponseToJSON(json: any): GameAdventureSessionListResponse {
      return GameAdventureSessionListResponseToJSONTyped(json, false);
  }

  export function GameAdventureSessionListResponseToJSONTyped(value?: GameAdventureSessionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': ((value['sessions'] as Array<any>).map(GameAdventureSessionResponseToJSON)),
    };
}

