/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameAdventureJournalEntryKind = {
    Visible: 'visible',
    Hidden: 'hidden',
    Admin: 'admin'
} as const;
export type GameAdventureJournalEntryKind = typeof GameAdventureJournalEntryKind[keyof typeof GameAdventureJournalEntryKind];


export function instanceOfGameAdventureJournalEntryKind(value: any): boolean {
    for (const key in GameAdventureJournalEntryKind) {
        if (Object.prototype.hasOwnProperty.call(GameAdventureJournalEntryKind, key)) {
            if (GameAdventureJournalEntryKind[key as keyof typeof GameAdventureJournalEntryKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GameAdventureJournalEntryKindFromJSON(json: any): GameAdventureJournalEntryKind {
    return GameAdventureJournalEntryKindFromJSONTyped(json, false);
}

export function GameAdventureJournalEntryKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureJournalEntryKind {
    return json as GameAdventureJournalEntryKind;
}

export function GameAdventureJournalEntryKindToJSON(value?: GameAdventureJournalEntryKind | null): any {
    return value as any;
}

export function GameAdventureJournalEntryKindToJSONTyped(value: any, ignoreDiscriminator: boolean): GameAdventureJournalEntryKind {
    return value as GameAdventureJournalEntryKind;
}

