/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameAdventureCreatorResponse } from './GameAdventureCreatorResponse';
import {
    GameAdventureCreatorResponseFromJSON,
    GameAdventureCreatorResponseFromJSONTyped,
    GameAdventureCreatorResponseToJSON,
    GameAdventureCreatorResponseToJSONTyped,
} from './GameAdventureCreatorResponse';

/**
 * 
 * @export
 * @interface GameAdventureCreatorListResponse
 */
export interface GameAdventureCreatorListResponse {
    /**
     * 
     * @type {Array<GameAdventureCreatorResponse>}
     * @memberof GameAdventureCreatorListResponse
     */
    gameAdventures: Array<GameAdventureCreatorResponse>;
}

/**
 * Check if a given object implements the GameAdventureCreatorListResponse interface.
 */
export function instanceOfGameAdventureCreatorListResponse(value: object): value is GameAdventureCreatorListResponse {
    if (!('gameAdventures' in value) || value['gameAdventures'] === undefined) return false;
    return true;
}

export function GameAdventureCreatorListResponseFromJSON(json: any): GameAdventureCreatorListResponse {
    return GameAdventureCreatorListResponseFromJSONTyped(json, false);
}

export function GameAdventureCreatorListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAdventureCreatorListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'gameAdventures': ((json['game_adventures'] as Array<any>).map(GameAdventureCreatorResponseFromJSON)),
    };
}

  export function GameAdventureCreatorListResponseToJSON(json: any): GameAdventureCreatorListResponse {
      return GameAdventureCreatorListResponseToJSONTyped(json, false);
  }

  export function GameAdventureCreatorListResponseToJSONTyped(value?: GameAdventureCreatorListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game_adventures': ((value['gameAdventures'] as Array<any>).map(GameAdventureCreatorResponseToJSON)),
    };
}

