/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveRoleplayHistoryMessage } from './LiveRoleplayHistoryMessage';
import {
    LiveRoleplayHistoryMessageFromJSON,
    LiveRoleplayHistoryMessageFromJSONTyped,
    LiveRoleplayHistoryMessageToJSON,
    LiveRoleplayHistoryMessageToJSONTyped,
} from './LiveRoleplayHistoryMessage';

/**
 * 
 * @export
 * @interface GetLiveRoleplayHistoryResponse
 */
export interface GetLiveRoleplayHistoryResponse {
    /**
     * 
     * @type {string}
     * @memberof GetLiveRoleplayHistoryResponse
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof GetLiveRoleplayHistoryResponse
     */
    recipientId: string;
    /**
     * 
     * @type {number}
     * @memberof GetLiveRoleplayHistoryResponse
     */
    affectionScore: number;
    /**
     * 
     * @type {Array<LiveRoleplayHistoryMessage>}
     * @memberof GetLiveRoleplayHistoryResponse
     */
    messages: Array<LiveRoleplayHistoryMessage>;
}

/**
 * Check if a given object implements the GetLiveRoleplayHistoryResponse interface.
 */
export function instanceOfGetLiveRoleplayHistoryResponse(value: object): value is GetLiveRoleplayHistoryResponse {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('recipientId' in value) || value['recipientId'] === undefined) return false;
    if (!('affectionScore' in value) || value['affectionScore'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function GetLiveRoleplayHistoryResponseFromJSON(json: any): GetLiveRoleplayHistoryResponse {
    return GetLiveRoleplayHistoryResponseFromJSONTyped(json, false);
}

export function GetLiveRoleplayHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLiveRoleplayHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversation_id'],
        'recipientId': json['recipient_id'],
        'affectionScore': json['affection_score'],
        'messages': ((json['messages'] as Array<any>).map(LiveRoleplayHistoryMessageFromJSON)),
    };
}

  export function GetLiveRoleplayHistoryResponseToJSON(json: any): GetLiveRoleplayHistoryResponse {
      return GetLiveRoleplayHistoryResponseToJSONTyped(json, false);
  }

  export function GetLiveRoleplayHistoryResponseToJSONTyped(value?: GetLiveRoleplayHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation_id': value['conversationId'],
        'recipient_id': value['recipientId'],
        'affection_score': value['affectionScore'],
        'messages': ((value['messages'] as Array<any>).map(LiveRoleplayHistoryMessageToJSON)),
    };
}

