/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddonProductPrice } from './AddonProductPrice';
import {
    AddonProductPriceFromJSON,
    AddonProductPriceFromJSONTyped,
    AddonProductPriceToJSON,
    AddonProductPriceToJSONTyped,
} from './AddonProductPrice';
import type { SubscriptionPlanPrice } from './SubscriptionPlanPrice';
import {
    SubscriptionPlanPriceFromJSON,
    SubscriptionPlanPriceFromJSONTyped,
    SubscriptionPlanPriceToJSON,
    SubscriptionPlanPriceToJSONTyped,
} from './SubscriptionPlanPrice';
import type { SubscriptionTokenUsage } from './SubscriptionTokenUsage';
import {
    SubscriptionTokenUsageFromJSON,
    SubscriptionTokenUsageFromJSONTyped,
    SubscriptionTokenUsageToJSON,
    SubscriptionTokenUsageToJSONTyped,
} from './SubscriptionTokenUsage';
import type { PaymentCurrency } from './PaymentCurrency';
import {
    PaymentCurrencyFromJSON,
    PaymentCurrencyFromJSONTyped,
    PaymentCurrencyToJSON,
    PaymentCurrencyToJSONTyped,
} from './PaymentCurrency';

/**
 * 
 * @export
 * @interface GetPricesResponse
 */
export interface GetPricesResponse {
    /**
     * 
     * @type {PaymentCurrency}
     * @memberof GetPricesResponse
     */
    currency: PaymentCurrency;
    /**
     * 
     * @type {{ [key: string]: SubscriptionTokenUsage; }}
     * @memberof GetPricesResponse
     */
    tokenUsage: { [key: string]: SubscriptionTokenUsage; };
    /**
     * 
     * @type {{ [key: string]: Array<SubscriptionPlanPrice>; }}
     * @memberof GetPricesResponse
     */
    subscriptions: { [key: string]: Array<SubscriptionPlanPrice>; };
    /**
     * 
     * @type {{ [key: string]: Array<AddonProductPrice>; }}
     * @memberof GetPricesResponse
     */
    addons: { [key: string]: Array<AddonProductPrice>; };
}



/**
 * Check if a given object implements the GetPricesResponse interface.
 */
export function instanceOfGetPricesResponse(value: object): value is GetPricesResponse {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('tokenUsage' in value) || value['tokenUsage'] === undefined) return false;
    if (!('subscriptions' in value) || value['subscriptions'] === undefined) return false;
    if (!('addons' in value) || value['addons'] === undefined) return false;
    return true;
}

export function GetPricesResponseFromJSON(json: any): GetPricesResponse {
    return GetPricesResponseFromJSONTyped(json, false);
}

export function GetPricesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPricesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': PaymentCurrencyFromJSON(json['currency']),
        'tokenUsage': (mapValues(json['token_usage'], SubscriptionTokenUsageFromJSON)),
        'subscriptions': json['subscriptions'],
        'addons': json['addons'],
    };
}

  export function GetPricesResponseToJSON(json: any): GetPricesResponse {
      return GetPricesResponseToJSONTyped(json, false);
  }

  export function GetPricesResponseToJSONTyped(value?: GetPricesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': PaymentCurrencyToJSON(value['currency']),
        'token_usage': (mapValues(value['tokenUsage'], SubscriptionTokenUsageToJSON)),
        'subscriptions': value['subscriptions'],
        'addons': value['addons'],
    };
}

