/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagCategory } from './TagCategory';
import {
    TagCategoryFromJSON,
    TagCategoryFromJSONTyped,
    TagCategoryToJSON,
    TagCategoryToJSONTyped,
} from './TagCategory';

/**
 * 
 * @export
 * @interface HubTag
 */
export interface HubTag {
    /**
     * 
     * @type {TagCategory}
     * @memberof HubTag
     */
    category: TagCategory;
    /**
     * 
     * @type {string}
     * @memberof HubTag
     */
    value: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HubTag
     */
    previewImageUrls?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof HubTag
     */
    indexable?: boolean;
}



/**
 * Check if a given object implements the HubTag interface.
 */
export function instanceOfHubTag(value: object): value is HubTag {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function HubTagFromJSON(json: any): HubTag {
    return HubTagFromJSONTyped(json, false);
}

export function HubTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): HubTag {
    if (json == null) {
        return json;
    }
    return {
        
        'category': TagCategoryFromJSON(json['category']),
        'value': json['value'],
        'previewImageUrls': json['preview_image_urls'] == null ? undefined : json['preview_image_urls'],
        'indexable': json['indexable'] == null ? undefined : json['indexable'],
    };
}

  export function HubTagToJSON(json: any): HubTag {
      return HubTagToJSONTyped(json, false);
  }

  export function HubTagToJSONTyped(value?: HubTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': TagCategoryToJSON(value['category']),
        'value': value['value'],
        'preview_image_urls': value['previewImageUrls'],
        'indexable': value['indexable'],
    };
}

