/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HubTag } from './HubTag';
import {
    HubTagFromJSON,
    HubTagFromJSONTyped,
    HubTagToJSON,
    HubTagToJSONTyped,
} from './HubTag';

/**
 * 
 * @export
 * @interface HubTagsResponse
 */
export interface HubTagsResponse {
    /**
     * 
     * @type {Array<HubTag>}
     * @memberof HubTagsResponse
     */
    hubTags: Array<HubTag>;
}

/**
 * Check if a given object implements the HubTagsResponse interface.
 */
export function instanceOfHubTagsResponse(value: object): value is HubTagsResponse {
    if (!('hubTags' in value) || value['hubTags'] === undefined) return false;
    return true;
}

export function HubTagsResponseFromJSON(json: any): HubTagsResponse {
    return HubTagsResponseFromJSONTyped(json, false);
}

export function HubTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HubTagsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hubTags': ((json['hub_tags'] as Array<any>).map(HubTagFromJSON)),
    };
}

  export function HubTagsResponseToJSON(json: any): HubTagsResponse {
      return HubTagsResponseToJSONTyped(json, false);
  }

  export function HubTagsResponseToJSONTyped(value?: HubTagsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hub_tags': ((value['hubTags'] as Array<any>).map(HubTagToJSON)),
    };
}

