/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoLoraName } from './VideoLoraName';
import {
    VideoLoraNameFromJSON,
    VideoLoraNameFromJSONTyped,
    VideoLoraNameToJSON,
    VideoLoraNameToJSONTyped,
} from './VideoLoraName';

/**
 * 
 * @export
 * @interface ImageToVideoRequest
 */
export interface ImageToVideoRequest {
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    model: ImageToVideoRequestModelEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    prompt: string;
    /**
     * 
     * @type {number}
     * @memberof ImageToVideoRequest
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    chatbotId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    inputImageId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    resolution: ImageToVideoRequestResolutionEnum;
    /**
     * 
     * @type {Array<VideoLoraName>}
     * @memberof ImageToVideoRequest
     */
    loras?: Array<VideoLoraName> | null;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRequest
     */
    negativePrompt?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ImageToVideoRequest
     */
    watermark?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImageToVideoRequest
     */
    promptExtend?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ImageToVideoRequest
     */
    seed?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ImageToVideoRequest
     */
    audioGeneration?: boolean;
}


/**
 * @export
 */
export const ImageToVideoRequestModelEnum = {
    _22I2V: 'WAN_22_I2V',
    _27I2V: 'WAN_27_I2V'
} as const;
export type ImageToVideoRequestModelEnum = typeof ImageToVideoRequestModelEnum[keyof typeof ImageToVideoRequestModelEnum];

/**
 * @export
 */
export const ImageToVideoRequestResolutionEnum = {
    P480: 'P480',
    P720: 'P720',
    P1080: 'P1080'
} as const;
export type ImageToVideoRequestResolutionEnum = typeof ImageToVideoRequestResolutionEnum[keyof typeof ImageToVideoRequestResolutionEnum];


/**
 * Check if a given object implements the ImageToVideoRequest interface.
 */
export function instanceOfImageToVideoRequest(value: object): value is ImageToVideoRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('chatbotId' in value) || value['chatbotId'] === undefined) return false;
    if (!('inputImageId' in value) || value['inputImageId'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    return true;
}

export function ImageToVideoRequestFromJSON(json: any): ImageToVideoRequest {
    return ImageToVideoRequestFromJSONTyped(json, false);
}

export function ImageToVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageToVideoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'prompt': json['prompt'],
        'duration': json['duration'],
        'clientId': json['client_id'],
        'requestId': json['request_id'],
        'chatbotId': json['chatbot_id'],
        'inputImageId': json['input_image_id'],
        'resolution': json['resolution'],
        'loras': json['loras'] == null ? undefined : ((json['loras'] as Array<any>).map(VideoLoraNameFromJSON)),
        'negativePrompt': json['negative_prompt'] == null ? undefined : json['negative_prompt'],
        'watermark': json['watermark'] == null ? undefined : json['watermark'],
        'promptExtend': json['prompt_extend'] == null ? undefined : json['prompt_extend'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'audioGeneration': json['audio_generation'] == null ? undefined : json['audio_generation'],
    };
}

  export function ImageToVideoRequestToJSON(json: any): ImageToVideoRequest {
      return ImageToVideoRequestToJSONTyped(json, false);
  }

  export function ImageToVideoRequestToJSONTyped(value?: ImageToVideoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'prompt': value['prompt'],
        'duration': value['duration'],
        'client_id': value['clientId'],
        'request_id': value['requestId'],
        'chatbot_id': value['chatbotId'],
        'input_image_id': value['inputImageId'],
        'resolution': value['resolution'],
        'loras': value['loras'] == null ? undefined : ((value['loras'] as Array<any>).map(VideoLoraNameToJSON)),
        'negative_prompt': value['negativePrompt'],
        'watermark': value['watermark'],
        'prompt_extend': value['promptExtend'],
        'seed': value['seed'],
        'audio_generation': value['audioGeneration'],
    };
}

