/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstanceType } from './InstanceType';
import {
    InstanceTypeFromJSON,
    InstanceTypeFromJSONTyped,
    InstanceTypeToJSON,
    InstanceTypeToJSONTyped,
} from './InstanceType';
import type { InstanceProvider } from './InstanceProvider';
import {
    InstanceProviderFromJSON,
    InstanceProviderFromJSONTyped,
    InstanceProviderToJSON,
    InstanceProviderToJSONTyped,
} from './InstanceProvider';

/**
 * 
 * @export
 * @interface InstanceTypeUrlResponse
 */
export interface InstanceTypeUrlResponse {
    /**
     * 
     * @type {InstanceType}
     * @memberof InstanceTypeUrlResponse
     */
    type: InstanceType;
    /**
     * 
     * @type {string}
     * @memberof InstanceTypeUrlResponse
     */
    url: string;
    /**
     * 
     * @type {InstanceProvider}
     * @memberof InstanceTypeUrlResponse
     */
    provider: InstanceProvider;
}



/**
 * Check if a given object implements the InstanceTypeUrlResponse interface.
 */
export function instanceOfInstanceTypeUrlResponse(value: object): value is InstanceTypeUrlResponse {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function InstanceTypeUrlResponseFromJSON(json: any): InstanceTypeUrlResponse {
    return InstanceTypeUrlResponseFromJSONTyped(json, false);
}

export function InstanceTypeUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceTypeUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'type': InstanceTypeFromJSON(json['type']),
        'url': json['url'],
        'provider': InstanceProviderFromJSON(json['provider']),
    };
}

  export function InstanceTypeUrlResponseToJSON(json: any): InstanceTypeUrlResponse {
      return InstanceTypeUrlResponseToJSONTyped(json, false);
  }

  export function InstanceTypeUrlResponseToJSONTyped(value?: InstanceTypeUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': InstanceTypeToJSON(value['type']),
        'url': value['url'],
        'provider': InstanceProviderToJSON(value['provider']),
    };
}

