/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveDonateRequest
 */
export interface LiveDonateRequest {
    /**
     * 
     * @type {number}
     * @memberof LiveDonateRequest
     */
    strips: number;
    /**
     * 
     * @type {string}
     * @memberof LiveDonateRequest
     */
    idempotencyKey: string;
}

/**
 * Check if a given object implements the LiveDonateRequest interface.
 */
export function instanceOfLiveDonateRequest(value: object): value is LiveDonateRequest {
    if (!('strips' in value) || value['strips'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function LiveDonateRequestFromJSON(json: any): LiveDonateRequest {
    return LiveDonateRequestFromJSONTyped(json, false);
}

export function LiveDonateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveDonateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'strips': json['strips'],
        'idempotencyKey': json['idempotency_key'],
    };
}

  export function LiveDonateRequestToJSON(json: any): LiveDonateRequest {
      return LiveDonateRequestToJSONTyped(json, false);
  }

  export function LiveDonateRequestToJSONTyped(value?: LiveDonateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strips': value['strips'],
        'idempotency_key': value['idempotencyKey'],
    };
}

