/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatRole } from './ChatRole';
import {
    ChatRoleFromJSON,
    ChatRoleFromJSONTyped,
    ChatRoleToJSON,
    ChatRoleToJSONTyped,
} from './ChatRole';

/**
 * 
 * @export
 * @interface LiveRoleplaySeedMessage
 */
export interface LiveRoleplaySeedMessage {
    /**
     * 
     * @type {string}
     * @memberof LiveRoleplaySeedMessage
     */
    content: string;
    /**
     * 
     * @type {ChatRole}
     * @memberof LiveRoleplaySeedMessage
     */
    role: ChatRole;
}



/**
 * Check if a given object implements the LiveRoleplaySeedMessage interface.
 */
export function instanceOfLiveRoleplaySeedMessage(value: object): value is LiveRoleplaySeedMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function LiveRoleplaySeedMessageFromJSON(json: any): LiveRoleplaySeedMessage {
    return LiveRoleplaySeedMessageFromJSONTyped(json, false);
}

export function LiveRoleplaySeedMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveRoleplaySeedMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'role': ChatRoleFromJSON(json['role']),
    };
}

  export function LiveRoleplaySeedMessageToJSON(json: any): LiveRoleplaySeedMessage {
      return LiveRoleplaySeedMessageToJSONTyped(json, false);
  }

  export function LiveRoleplaySeedMessageToJSONTyped(value?: LiveRoleplaySeedMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'role': ChatRoleToJSON(value['role']),
    };
}

