/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The caller's own live state, so a reload does not lose it.
 * @export
 * @interface LiveMeState
 */
export interface LiveMeState {
    /**
     * 
     * @type {string}
     * @memberof LiveMeState
     */
    vote?: string | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof LiveMeState
     */
    boosts?: { [key: string]: number; };
    /**
     * 
     * @type {number}
     * @memberof LiveMeState
     */
    strips?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof LiveMeState
     */
    upvotes?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof LiveMeState
     */
    backing?: { [key: string]: number; };
    /**
     * 
     * @type {Array<string>}
     * @memberof LiveMeState
     */
    candidateIds?: Array<string>;
}

/**
 * Check if a given object implements the LiveMeState interface.
 */
export function instanceOfLiveMeState(value: object): value is LiveMeState {
    return true;
}

export function LiveMeStateFromJSON(json: any): LiveMeState {
    return LiveMeStateFromJSONTyped(json, false);
}

export function LiveMeStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveMeState {
    if (json == null) {
        return json;
    }
    return {
        
        'vote': json['vote'] == null ? undefined : json['vote'],
        'boosts': json['boosts'] == null ? undefined : json['boosts'],
        'strips': json['strips'] == null ? undefined : json['strips'],
        'upvotes': json['upvotes'] == null ? undefined : json['upvotes'],
        'backing': json['backing'] == null ? undefined : json['backing'],
        'candidateIds': json['candidate_ids'] == null ? undefined : json['candidate_ids'],
    };
}

  export function LiveMeStateToJSON(json: any): LiveMeState {
      return LiveMeStateToJSONTyped(json, false);
  }

  export function LiveMeStateToJSONTyped(value?: LiveMeState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vote': value['vote'],
        'boosts': value['boosts'],
        'strips': value['strips'],
        'upvotes': value['upvotes'],
        'backing': value['backing'],
        'candidate_ids': value['candidateIds'],
    };
}

