/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LiveReactionType = {
    Note: 'note',
    Emoji: 'emoji',
    Sticker: 'sticker'
} as const;
export type LiveReactionType = typeof LiveReactionType[keyof typeof LiveReactionType];


export function instanceOfLiveReactionType(value: any): boolean {
    for (const key in LiveReactionType) {
        if (Object.prototype.hasOwnProperty.call(LiveReactionType, key)) {
            if (LiveReactionType[key as keyof typeof LiveReactionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LiveReactionTypeFromJSON(json: any): LiveReactionType {
    return LiveReactionTypeFromJSONTyped(json, false);
}

export function LiveReactionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveReactionType {
    return json as LiveReactionType;
}

export function LiveReactionTypeToJSON(value?: LiveReactionType | null): any {
    return value as any;
}

export function LiveReactionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LiveReactionType {
    return value as LiveReactionType;
}

