/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveQueueUpvoteRequest
 */
export interface LiveQueueUpvoteRequest {
    /**
     * 
     * @type {boolean}
     * @memberof LiveQueueUpvoteRequest
     */
    on: boolean;
}

/**
 * Check if a given object implements the LiveQueueUpvoteRequest interface.
 */
export function instanceOfLiveQueueUpvoteRequest(value: object): value is LiveQueueUpvoteRequest {
    if (!('on' in value) || value['on'] === undefined) return false;
    return true;
}

export function LiveQueueUpvoteRequestFromJSON(json: any): LiveQueueUpvoteRequest {
    return LiveQueueUpvoteRequestFromJSONTyped(json, false);
}

export function LiveQueueUpvoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveQueueUpvoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'on': json['on'],
    };
}

  export function LiveQueueUpvoteRequestToJSON(json: any): LiveQueueUpvoteRequest {
      return LiveQueueUpvoteRequestToJSONTyped(json, false);
  }

  export function LiveQueueUpvoteRequestToJSONTyped(value?: LiveQueueUpvoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'on': value['on'],
    };
}

