/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveAdminForceWinnerRequest
 */
export interface LiveAdminForceWinnerRequest {
    /**
     * 
     * @type {string}
     * @memberof LiveAdminForceWinnerRequest
     */
    optionId: string;
}

/**
 * Check if a given object implements the LiveAdminForceWinnerRequest interface.
 */
export function instanceOfLiveAdminForceWinnerRequest(value: object): value is LiveAdminForceWinnerRequest {
    if (!('optionId' in value) || value['optionId'] === undefined) return false;
    return true;
}

export function LiveAdminForceWinnerRequestFromJSON(json: any): LiveAdminForceWinnerRequest {
    return LiveAdminForceWinnerRequestFromJSONTyped(json, false);
}

export function LiveAdminForceWinnerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveAdminForceWinnerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'optionId': json['option_id'],
    };
}

  export function LiveAdminForceWinnerRequestToJSON(json: any): LiveAdminForceWinnerRequest {
      return LiveAdminForceWinnerRequestToJSONTyped(json, false);
  }

  export function LiveAdminForceWinnerRequestToJSONTyped(value?: LiveAdminForceWinnerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'option_id': value['optionId'],
    };
}

