/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What delivers the picture to this viewer right now; `none` while nothing is playing.
 * @export
 */
export const LivePlayerTransport = {
    Webrtc: 'webrtc',
    Llhls: 'llhls',
    None: 'none'
} as const;
export type LivePlayerTransport = typeof LivePlayerTransport[keyof typeof LivePlayerTransport];


export function instanceOfLivePlayerTransport(value: any): boolean {
    for (const key in LivePlayerTransport) {
        if (Object.prototype.hasOwnProperty.call(LivePlayerTransport, key)) {
            if (LivePlayerTransport[key as keyof typeof LivePlayerTransport] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LivePlayerTransportFromJSON(json: any): LivePlayerTransport {
    return LivePlayerTransportFromJSONTyped(json, false);
}

export function LivePlayerTransportFromJSONTyped(json: any, ignoreDiscriminator: boolean): LivePlayerTransport {
    return json as LivePlayerTransport;
}

export function LivePlayerTransportToJSON(value?: LivePlayerTransport | null): any {
    return value as any;
}

export function LivePlayerTransportToJSONTyped(value: any, ignoreDiscriminator: boolean): LivePlayerTransport {
    return value as LivePlayerTransport;
}

