/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveReaction } from './LiveReaction';
import {
    LiveReactionFromJSON,
    LiveReactionFromJSONTyped,
    LiveReactionToJSON,
    LiveReactionToJSONTyped,
} from './LiveReaction';
import type { LiveChatKind } from './LiveChatKind';
import {
    LiveChatKindFromJSON,
    LiveChatKindFromJSONTyped,
    LiveChatKindToJSON,
    LiveChatKindToJSONTyped,
} from './LiveChatKind';

/**
 * 
 * @export
 * @interface LiveChatMessage
 */
export interface LiveChatMessage {
    /**
     * 
     * @type {string}
     * @memberof LiveChatMessage
     */
    id: string;
    /**
     * 
     * @type {LiveChatKind}
     * @memberof LiveChatMessage
     */
    kind: LiveChatKind;
    /**
     * 
     * @type {string}
     * @memberof LiveChatMessage
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof LiveChatMessage
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveChatMessage
     */
    text: string;
    /**
     * 
     * @type {LiveReaction}
     * @memberof LiveChatMessage
     */
    reaction?: LiveReaction | null;
    /**
     * 
     * @type {number}
     * @memberof LiveChatMessage
     */
    amount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LiveChatMessage
     */
    at: number;
}



/**
 * Check if a given object implements the LiveChatMessage interface.
 */
export function instanceOfLiveChatMessage(value: object): value is LiveChatMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('at' in value) || value['at'] === undefined) return false;
    return true;
}

export function LiveChatMessageFromJSON(json: any): LiveChatMessage {
    return LiveChatMessageFromJSONTyped(json, false);
}

export function LiveChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': LiveChatKindFromJSON(json['kind']),
        'user': json['user'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'text': json['text'],
        'reaction': json['reaction'] == null ? undefined : LiveReactionFromJSON(json['reaction']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'at': json['at'],
    };
}

  export function LiveChatMessageToJSON(json: any): LiveChatMessage {
      return LiveChatMessageToJSONTyped(json, false);
  }

  export function LiveChatMessageToJSONTyped(value?: LiveChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': LiveChatKindToJSON(value['kind']),
        'user': value['user'],
        'avatar_url': value['avatarUrl'],
        'text': value['text'],
        'reaction': LiveReactionToJSON(value['reaction']),
        'amount': value['amount'],
        'at': value['at'],
    };
}

