/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveReaction } from './LiveReaction';
import {
    LiveReactionFromJSON,
    LiveReactionFromJSONTyped,
    LiveReactionToJSON,
    LiveReactionToJSONTyped,
} from './LiveReaction';

/**
 * 
 * @export
 * @interface LiveChatRequest
 */
export interface LiveChatRequest {
    /**
     * 
     * @type {LiveReaction}
     * @memberof LiveChatRequest
     */
    reaction: LiveReaction;
}

/**
 * Check if a given object implements the LiveChatRequest interface.
 */
export function instanceOfLiveChatRequest(value: object): value is LiveChatRequest {
    if (!('reaction' in value) || value['reaction'] === undefined) return false;
    return true;
}

export function LiveChatRequestFromJSON(json: any): LiveChatRequest {
    return LiveChatRequestFromJSONTyped(json, false);
}

export function LiveChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reaction': LiveReactionFromJSON(json['reaction']),
    };
}

  export function LiveChatRequestToJSON(json: any): LiveChatRequest {
      return LiveChatRequestToJSONTyped(json, false);
  }

  export function LiveChatRequestToJSONTyped(value?: LiveChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reaction': LiveReactionToJSON(value['reaction']),
    };
}

