/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveConvertResponse
 */
export interface LiveConvertResponse {
    /**
     * 
     * @type {number}
     * @memberof LiveConvertResponse
     */
    strips: number;
    /**
     * 
     * @type {number}
     * @memberof LiveConvertResponse
     */
    remainingTokens: number;
    /**
     * 
     * @type {number}
     * @memberof LiveConvertResponse
     */
    convertedStrips: number;
    /**
     * 
     * @type {boolean}
     * @memberof LiveConvertResponse
     */
    applied: boolean;
}

/**
 * Check if a given object implements the LiveConvertResponse interface.
 */
export function instanceOfLiveConvertResponse(value: object): value is LiveConvertResponse {
    if (!('strips' in value) || value['strips'] === undefined) return false;
    if (!('remainingTokens' in value) || value['remainingTokens'] === undefined) return false;
    if (!('convertedStrips' in value) || value['convertedStrips'] === undefined) return false;
    if (!('applied' in value) || value['applied'] === undefined) return false;
    return true;
}

export function LiveConvertResponseFromJSON(json: any): LiveConvertResponse {
    return LiveConvertResponseFromJSONTyped(json, false);
}

export function LiveConvertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveConvertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'strips': json['strips'],
        'remainingTokens': json['remaining_tokens'],
        'convertedStrips': json['converted_strips'],
        'applied': json['applied'],
    };
}

  export function LiveConvertResponseToJSON(json: any): LiveConvertResponse {
      return LiveConvertResponseToJSONTyped(json, false);
  }

  export function LiveConvertResponseToJSONTyped(value?: LiveConvertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strips': value['strips'],
        'remaining_tokens': value['remainingTokens'],
        'converted_strips': value['convertedStrips'],
        'applied': value['applied'],
    };
}

