/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveCandidate } from './LiveCandidate';
import {
    LiveCandidateFromJSON,
    LiveCandidateFromJSONTyped,
    LiveCandidateToJSON,
    LiveCandidateToJSONTyped,
} from './LiveCandidate';

/**
 * 
 * @export
 * @interface LiveQueueState
 */
export interface LiveQueueState {
    /**
     * 
     * @type {Array<LiveCandidate>}
     * @memberof LiveQueueState
     */
    candidates: Array<LiveCandidate>;
    /**
     * 
     * @type {number}
     * @memberof LiveQueueState
     */
    nextLockAt: number;
    /**
     * 
     * @type {number}
     * @memberof LiveQueueState
     */
    minOpeningVotes: number;
    /**
     * 
     * @type {number}
     * @memberof LiveQueueState
     */
    votePriceStrips: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof LiveQueueState
     */
    myUpvotes?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof LiveQueueState
     */
    myBoughtVotes?: { [key: string]: number; };
}

/**
 * Check if a given object implements the LiveQueueState interface.
 */
export function instanceOfLiveQueueState(value: object): value is LiveQueueState {
    if (!('candidates' in value) || value['candidates'] === undefined) return false;
    if (!('nextLockAt' in value) || value['nextLockAt'] === undefined) return false;
    if (!('minOpeningVotes' in value) || value['minOpeningVotes'] === undefined) return false;
    if (!('votePriceStrips' in value) || value['votePriceStrips'] === undefined) return false;
    return true;
}

export function LiveQueueStateFromJSON(json: any): LiveQueueState {
    return LiveQueueStateFromJSONTyped(json, false);
}

export function LiveQueueStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveQueueState {
    if (json == null) {
        return json;
    }
    return {
        
        'candidates': ((json['candidates'] as Array<any>).map(LiveCandidateFromJSON)),
        'nextLockAt': json['next_lock_at'],
        'minOpeningVotes': json['min_opening_votes'],
        'votePriceStrips': json['vote_price_strips'],
        'myUpvotes': json['my_upvotes'] == null ? undefined : json['my_upvotes'],
        'myBoughtVotes': json['my_bought_votes'] == null ? undefined : json['my_bought_votes'],
    };
}

  export function LiveQueueStateToJSON(json: any): LiveQueueState {
      return LiveQueueStateToJSONTyped(json, false);
  }

  export function LiveQueueStateToJSONTyped(value?: LiveQueueState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidates': ((value['candidates'] as Array<any>).map(LiveCandidateToJSON)),
        'next_lock_at': value['nextLockAt'],
        'min_opening_votes': value['minOpeningVotes'],
        'vote_price_strips': value['votePriceStrips'],
        'my_upvotes': value['myUpvotes'],
        'my_bought_votes': value['myBoughtVotes'],
    };
}

