/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveBoostRequest
 */
export interface LiveBoostRequest {
    /**
     * 
     * @type {string}
     * @memberof LiveBoostRequest
     */
    optionId: string;
    /**
     * 
     * @type {number}
     * @memberof LiveBoostRequest
     */
    strips: number;
    /**
     * 
     * @type {string}
     * @memberof LiveBoostRequest
     */
    idempotencyKey: string;
}

/**
 * Check if a given object implements the LiveBoostRequest interface.
 */
export function instanceOfLiveBoostRequest(value: object): value is LiveBoostRequest {
    if (!('optionId' in value) || value['optionId'] === undefined) return false;
    if (!('strips' in value) || value['strips'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function LiveBoostRequestFromJSON(json: any): LiveBoostRequest {
    return LiveBoostRequestFromJSONTyped(json, false);
}

export function LiveBoostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveBoostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'optionId': json['option_id'],
        'strips': json['strips'],
        'idempotencyKey': json['idempotency_key'],
    };
}

  export function LiveBoostRequestToJSON(json: any): LiveBoostRequest {
      return LiveBoostRequestToJSONTyped(json, false);
  }

  export function LiveBoostRequestToJSONTyped(value?: LiveBoostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'option_id': value['optionId'],
        'strips': value['strips'],
        'idempotency_key': value['idempotencyKey'],
    };
}

