/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveWalletResponse
 */
export interface LiveWalletResponse {
    /**
     * 
     * @type {number}
     * @memberof LiveWalletResponse
     */
    strips: number;
    /**
     * 
     * @type {number}
     * @memberof LiveWalletResponse
     */
    stripsPerToken: number;
    /**
     * 
     * @type {number}
     * @memberof LiveWalletResponse
     */
    minTokens: number;
}

/**
 * Check if a given object implements the LiveWalletResponse interface.
 */
export function instanceOfLiveWalletResponse(value: object): value is LiveWalletResponse {
    if (!('strips' in value) || value['strips'] === undefined) return false;
    if (!('stripsPerToken' in value) || value['stripsPerToken'] === undefined) return false;
    if (!('minTokens' in value) || value['minTokens'] === undefined) return false;
    return true;
}

export function LiveWalletResponseFromJSON(json: any): LiveWalletResponse {
    return LiveWalletResponseFromJSONTyped(json, false);
}

export function LiveWalletResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveWalletResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'strips': json['strips'],
        'stripsPerToken': json['strips_per_token'],
        'minTokens': json['min_tokens'],
    };
}

  export function LiveWalletResponseToJSON(json: any): LiveWalletResponse {
      return LiveWalletResponseToJSONTyped(json, false);
  }

  export function LiveWalletResponseToJSONTyped(value?: LiveWalletResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strips': value['strips'],
        'strips_per_token': value['stripsPerToken'],
        'min_tokens': value['minTokens'],
    };
}

