/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LiveChatKind = {
    Chat: 'chat',
    Boost: 'boost',
    Donation: 'donation',
    System: 'system'
} as const;
export type LiveChatKind = typeof LiveChatKind[keyof typeof LiveChatKind];


export function instanceOfLiveChatKind(value: any): boolean {
    for (const key in LiveChatKind) {
        if (Object.prototype.hasOwnProperty.call(LiveChatKind, key)) {
            if (LiveChatKind[key as keyof typeof LiveChatKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LiveChatKindFromJSON(json: any): LiveChatKind {
    return LiveChatKindFromJSONTyped(json, false);
}

export function LiveChatKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveChatKind {
    return json as LiveChatKind;
}

export function LiveChatKindToJSON(value?: LiveChatKind | null): any {
    return value as any;
}

export function LiveChatKindToJSONTyped(value: any, ignoreDiscriminator: boolean): LiveChatKind {
    return value as LiveChatKind;
}

