/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What a babe performs in her slot; steers the script writer.
 * @export
 */
export const LiveSegment = {
    Sitcom: 'sitcom',
    Adventure: 'adventure',
    Romance: 'romance',
    Horror: 'horror',
    Gym: 'gym',
    Cosplay: 'cosplay',
    Feet: 'feet',
    Hardcore: 'hardcore'
} as const;
export type LiveSegment = typeof LiveSegment[keyof typeof LiveSegment];


export function instanceOfLiveSegment(value: any): boolean {
    for (const key in LiveSegment) {
        if (Object.prototype.hasOwnProperty.call(LiveSegment, key)) {
            if (LiveSegment[key as keyof typeof LiveSegment] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LiveSegmentFromJSON(json: any): LiveSegment {
    return LiveSegmentFromJSONTyped(json, false);
}

export function LiveSegmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveSegment {
    return json as LiveSegment;
}

export function LiveSegmentToJSON(value?: LiveSegment | null): any {
    return value as any;
}

export function LiveSegmentToJSONTyped(value: any, ignoreDiscriminator: boolean): LiveSegment {
    return value as LiveSegment;
}

