/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The story engine's view of the channel, as it last wrote it (None when no story engine runs or the key expired).
 * @export
 * @interface LiveAdminStory
 */
export interface LiveAdminStory {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LiveAdminStory
     */
    snapshot: { [key: string]: any; } | null;
    /**
     * 
     * @type {number}
     * @memberof LiveAdminStory
     */
    ageMs: number | null;
}

/**
 * Check if a given object implements the LiveAdminStory interface.
 */
export function instanceOfLiveAdminStory(value: object): value is LiveAdminStory {
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    if (!('ageMs' in value) || value['ageMs'] === undefined) return false;
    return true;
}

export function LiveAdminStoryFromJSON(json: any): LiveAdminStory {
    return LiveAdminStoryFromJSONTyped(json, false);
}

export function LiveAdminStoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveAdminStory {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshot': json['snapshot'],
        'ageMs': json['age_ms'],
    };
}

  export function LiveAdminStoryToJSON(json: any): LiveAdminStory {
      return LiveAdminStoryToJSONTyped(json, false);
  }

  export function LiveAdminStoryToJSONTyped(value?: LiveAdminStory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snapshot': value['snapshot'],
        'age_ms': value['ageMs'],
    };
}

