/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveReactionType } from './LiveReactionType';
import {
    LiveReactionTypeFromJSON,
    LiveReactionTypeFromJSONTyped,
    LiveReactionTypeToJSON,
    LiveReactionTypeToJSONTyped,
} from './LiveReactionType';

/**
 * A pick from the chat vocabulary.
 * 
 * The catalog (notes, emojis, sticker packs) lives in the frontend only, in `liveReactions.ts`;
 * the backend does not mirror it. It enforces the one rule that matters here, no free text: an id
 * is a short slug, and the row's text is that slug.
 * @export
 * @interface LiveReaction
 */
export interface LiveReaction {
    /**
     * 
     * @type {LiveReactionType}
     * @memberof LiveReaction
     */
    type: LiveReactionType;
    /**
     * 
     * @type {string}
     * @memberof LiveReaction
     */
    id: string;
}



/**
 * Check if a given object implements the LiveReaction interface.
 */
export function instanceOfLiveReaction(value: object): value is LiveReaction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function LiveReactionFromJSON(json: any): LiveReaction {
    return LiveReactionFromJSONTyped(json, false);
}

export function LiveReactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveReaction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': LiveReactionTypeFromJSON(json['type']),
        'id': json['id'],
    };
}

  export function LiveReactionToJSON(json: any): LiveReaction {
      return LiveReactionToJSONTyped(json, false);
  }

  export function LiveReactionToJSONTyped(value?: LiveReaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': LiveReactionTypeToJSON(value['type']),
        'id': value['id'],
    };
}

