/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveOptionKind } from './LiveOptionKind';
import {
    LiveOptionKindFromJSON,
    LiveOptionKindFromJSONTyped,
    LiveOptionKindToJSON,
    LiveOptionKindToJSONTyped,
} from './LiveOptionKind';

/**
 * 
 * @export
 * @interface LiveOption
 */
export interface LiveOption {
    /**
     * 
     * @type {string}
     * @memberof LiveOption
     */
    id: string;
    /**
     * 
     * @type {LiveOptionKind}
     * @memberof LiveOption
     */
    kind: LiveOptionKind;
    /**
     * 
     * @type {string}
     * @memberof LiveOption
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof LiveOption
     */
    intensity: number;
    /**
     * 
     * @type {number}
     * @memberof LiveOption
     */
    votes?: number;
    /**
     * 
     * @type {number}
     * @memberof LiveOption
     */
    heat?: number;
    /**
     * 
     * @type {string}
     * @memberof LiveOption
     */
    clipUrl?: string | null;
}



/**
 * Check if a given object implements the LiveOption interface.
 */
export function instanceOfLiveOption(value: object): value is LiveOption {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('intensity' in value) || value['intensity'] === undefined) return false;
    return true;
}

export function LiveOptionFromJSON(json: any): LiveOption {
    return LiveOptionFromJSONTyped(json, false);
}

export function LiveOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveOption {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': LiveOptionKindFromJSON(json['kind']),
        'label': json['label'],
        'intensity': json['intensity'],
        'votes': json['votes'] == null ? undefined : json['votes'],
        'heat': json['heat'] == null ? undefined : json['heat'],
        'clipUrl': json['clip_url'] == null ? undefined : json['clip_url'],
    };
}

  export function LiveOptionToJSON(json: any): LiveOption {
      return LiveOptionToJSONTyped(json, false);
  }

  export function LiveOptionToJSONTyped(value?: LiveOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': LiveOptionKindToJSON(value['kind']),
        'label': value['label'],
        'intensity': value['intensity'],
        'votes': value['votes'],
        'heat': value['heat'],
        'clip_url': value['clipUrl'],
    };
}

