/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveAdminSettingsRequest
 */
export interface LiveAdminSettingsRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LiveAdminSettingsRequest
     */
    settings: { [key: string]: any; };
}

/**
 * Check if a given object implements the LiveAdminSettingsRequest interface.
 */
export function instanceOfLiveAdminSettingsRequest(value: object): value is LiveAdminSettingsRequest {
    if (!('settings' in value) || value['settings'] === undefined) return false;
    return true;
}

export function LiveAdminSettingsRequestFromJSON(json: any): LiveAdminSettingsRequest {
    return LiveAdminSettingsRequestFromJSONTyped(json, false);
}

export function LiveAdminSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveAdminSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'settings': json['settings'],
    };
}

  export function LiveAdminSettingsRequestToJSON(json: any): LiveAdminSettingsRequest {
      return LiveAdminSettingsRequestToJSONTyped(json, false);
  }

  export function LiveAdminSettingsRequestToJSONTyped(value?: LiveAdminSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': value['settings'],
    };
}

