/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveAdminChannel } from './LiveAdminChannel';
import {
    LiveAdminChannelFromJSON,
    LiveAdminChannelFromJSONTyped,
    LiveAdminChannelToJSON,
    LiveAdminChannelToJSONTyped,
} from './LiveAdminChannel';
import type { LiveAdminSpendHealth } from './LiveAdminSpendHealth';
import {
    LiveAdminSpendHealthFromJSON,
    LiveAdminSpendHealthFromJSONTyped,
    LiveAdminSpendHealthToJSON,
    LiveAdminSpendHealthToJSONTyped,
} from './LiveAdminSpendHealth';
import type { LiveHeatState } from './LiveHeatState';
import {
    LiveHeatStateFromJSON,
    LiveHeatStateFromJSONTyped,
    LiveHeatStateToJSON,
    LiveHeatStateToJSONTyped,
} from './LiveHeatState';
import type { LiveRoundSnapshot } from './LiveRoundSnapshot';
import {
    LiveRoundSnapshotFromJSON,
    LiveRoundSnapshotFromJSONTyped,
    LiveRoundSnapshotToJSON,
    LiveRoundSnapshotToJSONTyped,
} from './LiveRoundSnapshot';

/**
 * 
 * @export
 * @interface LiveAdminStatus
 */
export interface LiveAdminStatus {
    /**
     * 
     * @type {LiveAdminChannel}
     * @memberof LiveAdminStatus
     */
    channel: LiveAdminChannel | null;
    /**
     * 
     * @type {LiveRoundSnapshot}
     * @memberof LiveAdminStatus
     */
    round: LiveRoundSnapshot | null;
    /**
     * 
     * @type {LiveHeatState}
     * @memberof LiveAdminStatus
     */
    heat: LiveHeatState;
    /**
     * 
     * @type {number}
     * @memberof LiveAdminStatus
     */
    viewers: number;
    /**
     * 
     * @type {number}
     * @memberof LiveAdminStatus
     */
    queueLength: number;
    /**
     * 
     * @type {LiveAdminSpendHealth}
     * @memberof LiveAdminStatus
     */
    spend: LiveAdminSpendHealth;
    /**
     * 
     * @type {number}
     * @memberof LiveAdminStatus
     */
    engineHeartbeatAgeMs: number | null;
    /**
     * 
     * @type {number}
     * @memberof LiveAdminStatus
     */
    serverNow: number;
}

/**
 * Check if a given object implements the LiveAdminStatus interface.
 */
export function instanceOfLiveAdminStatus(value: object): value is LiveAdminStatus {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('round' in value) || value['round'] === undefined) return false;
    if (!('heat' in value) || value['heat'] === undefined) return false;
    if (!('viewers' in value) || value['viewers'] === undefined) return false;
    if (!('queueLength' in value) || value['queueLength'] === undefined) return false;
    if (!('spend' in value) || value['spend'] === undefined) return false;
    if (!('engineHeartbeatAgeMs' in value) || value['engineHeartbeatAgeMs'] === undefined) return false;
    if (!('serverNow' in value) || value['serverNow'] === undefined) return false;
    return true;
}

export function LiveAdminStatusFromJSON(json: any): LiveAdminStatus {
    return LiveAdminStatusFromJSONTyped(json, false);
}

export function LiveAdminStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveAdminStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': LiveAdminChannelFromJSON(json['channel']),
        'round': LiveRoundSnapshotFromJSON(json['round']),
        'heat': LiveHeatStateFromJSON(json['heat']),
        'viewers': json['viewers'],
        'queueLength': json['queue_length'],
        'spend': LiveAdminSpendHealthFromJSON(json['spend']),
        'engineHeartbeatAgeMs': json['engine_heartbeat_age_ms'],
        'serverNow': json['server_now'],
    };
}

  export function LiveAdminStatusToJSON(json: any): LiveAdminStatus {
      return LiveAdminStatusToJSONTyped(json, false);
  }

  export function LiveAdminStatusToJSONTyped(value?: LiveAdminStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel': LiveAdminChannelToJSON(value['channel']),
        'round': LiveRoundSnapshotToJSON(value['round']),
        'heat': LiveHeatStateToJSON(value['heat']),
        'viewers': value['viewers'],
        'queue_length': value['queueLength'],
        'spend': LiveAdminSpendHealthToJSON(value['spend']),
        'engine_heartbeat_age_ms': value['engineHeartbeatAgeMs'],
        'server_now': value['serverNow'],
    };
}

