/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveStreamSource
 */
export interface LiveStreamSource {
    /**
     * 
     * @type {string}
     * @memberof LiveStreamSource
     */
    kind?: LiveStreamSourceKindEnum;
    /**
     * 
     * @type {string}
     * @memberof LiveStreamSource
     */
    wsUrl: string;
    /**
     * 
     * @type {string}
     * @memberof LiveStreamSource
     */
    llhlsUrl: string;
    /**
     * 
     * @type {string}
     * @memberof LiveStreamSource
     */
    token?: string | null;
}


/**
 * @export
 */
export const LiveStreamSourceKindEnum = {
    Stream: 'stream'
} as const;
export type LiveStreamSourceKindEnum = typeof LiveStreamSourceKindEnum[keyof typeof LiveStreamSourceKindEnum];


/**
 * Check if a given object implements the LiveStreamSource interface.
 */
export function instanceOfLiveStreamSource(value: object): value is LiveStreamSource {
    if (!('wsUrl' in value) || value['wsUrl'] === undefined) return false;
    if (!('llhlsUrl' in value) || value['llhlsUrl'] === undefined) return false;
    return true;
}

export function LiveStreamSourceFromJSON(json: any): LiveStreamSource {
    return LiveStreamSourceFromJSONTyped(json, false);
}

export function LiveStreamSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveStreamSource {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'wsUrl': json['ws_url'],
        'llhlsUrl': json['llhls_url'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function LiveStreamSourceToJSON(json: any): LiveStreamSource {
      return LiveStreamSourceToJSONTyped(json, false);
  }

  export function LiveStreamSourceToJSONTyped(value?: LiveStreamSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'ws_url': value['wsUrl'],
        'llhls_url': value['llhlsUrl'],
        'token': value['token'],
    };
}

