/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveSegment } from './LiveSegment';
import {
    LiveSegmentFromJSON,
    LiveSegmentFromJSONTyped,
    LiveSegmentToJSON,
    LiveSegmentToJSONTyped,
} from './LiveSegment';

/**
 * 
 * @export
 * @interface LiveBabe
 */
export interface LiveBabe {
    /**
     * 
     * @type {string}
     * @memberof LiveBabe
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LiveBabe
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LiveBabe
     */
    avatarUrl: string;
    /**
     * 
     * @type {string}
     * @memberof LiveBabe
     */
    bio?: string | null;
    /**
     * 
     * @type {LiveSegment}
     * @memberof LiveBabe
     */
    segment?: LiveSegment | null;
    /**
     * 
     * @type {string}
     * @memberof LiveBabe
     */
    owner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveBabe
     */
    ownerAvatarUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LiveBabe
     */
    startsAt: number;
    /**
     * 
     * @type {number}
     * @memberof LiveBabe
     */
    durationMs: number;
}



/**
 * Check if a given object implements the LiveBabe interface.
 */
export function instanceOfLiveBabe(value: object): value is LiveBabe {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    return true;
}

export function LiveBabeFromJSON(json: any): LiveBabe {
    return LiveBabeFromJSONTyped(json, false);
}

export function LiveBabeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveBabe {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'avatarUrl': json['avatar_url'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'segment': json['segment'] == null ? undefined : LiveSegmentFromJSON(json['segment']),
        'owner': json['owner'] == null ? undefined : json['owner'],
        'ownerAvatarUrl': json['owner_avatar_url'] == null ? undefined : json['owner_avatar_url'],
        'startsAt': json['starts_at'],
        'durationMs': json['duration_ms'],
    };
}

  export function LiveBabeToJSON(json: any): LiveBabe {
      return LiveBabeToJSONTyped(json, false);
  }

  export function LiveBabeToJSONTyped(value?: LiveBabe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'avatar_url': value['avatarUrl'],
        'bio': value['bio'],
        'segment': LiveSegmentToJSON(value['segment']),
        'owner': value['owner'],
        'owner_avatar_url': value['ownerAvatarUrl'],
        'starts_at': value['startsAt'],
        'duration_ms': value['durationMs'],
    };
}

