/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LivePhaseDurations
 */
export interface LivePhaseDurations {
    /**
     * 
     * @type {number}
     * @memberof LivePhaseDurations
     */
    votingMs: number;
    /**
     * 
     * @type {number}
     * @memberof LivePhaseDurations
     */
    lockingMs: number;
}

/**
 * Check if a given object implements the LivePhaseDurations interface.
 */
export function instanceOfLivePhaseDurations(value: object): value is LivePhaseDurations {
    if (!('votingMs' in value) || value['votingMs'] === undefined) return false;
    if (!('lockingMs' in value) || value['lockingMs'] === undefined) return false;
    return true;
}

export function LivePhaseDurationsFromJSON(json: any): LivePhaseDurations {
    return LivePhaseDurationsFromJSONTyped(json, false);
}

export function LivePhaseDurationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LivePhaseDurations {
    if (json == null) {
        return json;
    }
    return {
        
        'votingMs': json['voting_ms'],
        'lockingMs': json['locking_ms'],
    };
}

  export function LivePhaseDurationsToJSON(json: any): LivePhaseDurations {
      return LivePhaseDurationsToJSONTyped(json, false);
  }

  export function LivePhaseDurationsToJSONTyped(value?: LivePhaseDurations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'voting_ms': value['votingMs'],
        'locking_ms': value['lockingMs'],
    };
}

