/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveVoteRequest
 */
export interface LiveVoteRequest {
    /**
     * 
     * @type {string}
     * @memberof LiveVoteRequest
     */
    optionId: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVoteRequest
     */
    idempotencyKey: string;
}

/**
 * Check if a given object implements the LiveVoteRequest interface.
 */
export function instanceOfLiveVoteRequest(value: object): value is LiveVoteRequest {
    if (!('optionId' in value) || value['optionId'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function LiveVoteRequestFromJSON(json: any): LiveVoteRequest {
    return LiveVoteRequestFromJSONTyped(json, false);
}

export function LiveVoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveVoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'optionId': json['option_id'],
        'idempotencyKey': json['idempotency_key'],
    };
}

  export function LiveVoteRequestToJSON(json: any): LiveVoteRequest {
      return LiveVoteRequestToJSONTyped(json, false);
  }

  export function LiveVoteRequestToJSONTyped(value?: LiveVoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'option_id': value['optionId'],
        'idempotency_key': value['idempotencyKey'],
    };
}

