/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MediaOrigin = {
    Generator: 'generator',
    ChatRequest: 'chat_request',
    ChatAuto: 'chat_auto',
    Adventure: 'adventure',
    ChatLegacy: 'chat_legacy',
    Unknown: 'unknown'
} as const;
export type MediaOrigin = typeof MediaOrigin[keyof typeof MediaOrigin];


export function instanceOfMediaOrigin(value: any): boolean {
    for (const key in MediaOrigin) {
        if (Object.prototype.hasOwnProperty.call(MediaOrigin, key)) {
            if (MediaOrigin[key as keyof typeof MediaOrigin] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MediaOriginFromJSON(json: any): MediaOrigin {
    return MediaOriginFromJSONTyped(json, false);
}

export function MediaOriginFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaOrigin {
    return json as MediaOrigin;
}

export function MediaOriginToJSON(value?: MediaOrigin | null): any {
    return value as any;
}

export function MediaOriginToJSONTyped(value: any, ignoreDiscriminator: boolean): MediaOrigin {
    return value as MediaOrigin;
}

