/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonthlyTokens
 */
export interface MonthlyTokens {
}

/**
 * Check if a given object implements the MonthlyTokens interface.
 */
export function instanceOfMonthlyTokens(value: object): value is MonthlyTokens {
    return true;
}

export function MonthlyTokensFromJSON(json: any): MonthlyTokens {
    return MonthlyTokensFromJSONTyped(json, false);
}

export function MonthlyTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyTokens {
    return json;
}

  export function MonthlyTokensToJSON(json: any): MonthlyTokens {
      return MonthlyTokensToJSONTyped(json, false);
  }

  export function MonthlyTokensToJSONTyped(value?: MonthlyTokens | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

