/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Code1 } from './Code1';
import {
    Code1FromJSON,
    Code1FromJSONTyped,
    Code1ToJSON,
    Code1ToJSONTyped,
} from './Code1';
import type { MuleRouterWanTaskError } from './MuleRouterWanTaskError';
import {
    MuleRouterWanTaskErrorFromJSON,
    MuleRouterWanTaskErrorFromJSONTyped,
    MuleRouterWanTaskErrorToJSON,
    MuleRouterWanTaskErrorToJSONTyped,
} from './MuleRouterWanTaskError';
import type { Title1 } from './Title1';
import {
    Title1FromJSON,
    Title1FromJSONTyped,
    Title1ToJSON,
    Title1ToJSONTyped,
} from './Title1';
import type { Detail } from './Detail';
import {
    DetailFromJSON,
    DetailFromJSONTyped,
    DetailToJSON,
    DetailToJSONTyped,
} from './Detail';

/**
 * 
 * @export
 * @interface MuleRouterWanTaskInfoError
 */
export interface MuleRouterWanTaskInfoError {
    /**
     * 
     * @type {Code1}
     * @memberof MuleRouterWanTaskInfoError
     */
    code?: Code1;
    /**
     * 
     * @type {Title1}
     * @memberof MuleRouterWanTaskInfoError
     */
    title?: Title1;
    /**
     * 
     * @type {Detail}
     * @memberof MuleRouterWanTaskInfoError
     */
    detail?: Detail;
}

/**
 * Check if a given object implements the MuleRouterWanTaskInfoError interface.
 */
export function instanceOfMuleRouterWanTaskInfoError(value: object): value is MuleRouterWanTaskInfoError {
    return true;
}

export function MuleRouterWanTaskInfoErrorFromJSON(json: any): MuleRouterWanTaskInfoError {
    return MuleRouterWanTaskInfoErrorFromJSONTyped(json, false);
}

export function MuleRouterWanTaskInfoErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MuleRouterWanTaskInfoError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : Code1FromJSON(json['code']),
        'title': json['title'] == null ? undefined : Title1FromJSON(json['title']),
        'detail': json['detail'] == null ? undefined : DetailFromJSON(json['detail']),
    };
}

  export function MuleRouterWanTaskInfoErrorToJSON(json: any): MuleRouterWanTaskInfoError {
      return MuleRouterWanTaskInfoErrorToJSONTyped(json, false);
  }

  export function MuleRouterWanTaskInfoErrorToJSONTyped(value?: MuleRouterWanTaskInfoError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': Code1ToJSON(value['code']),
        'title': Title1ToJSON(value['title']),
        'detail': DetailToJSON(value['detail']),
    };
}

