/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuleRouterWanTaskResponseTaskInfo } from './MuleRouterWanTaskResponseTaskInfo';
import {
    MuleRouterWanTaskResponseTaskInfoFromJSON,
    MuleRouterWanTaskResponseTaskInfoFromJSONTyped,
    MuleRouterWanTaskResponseTaskInfoToJSON,
    MuleRouterWanTaskResponseTaskInfoToJSONTyped,
} from './MuleRouterWanTaskResponseTaskInfo';
import type { Videos } from './Videos';
import {
    VideosFromJSON,
    VideosFromJSONTyped,
    VideosToJSON,
    VideosToJSONTyped,
} from './Videos';

/**
 * 
 * @export
 * @interface MuleRouterWanTaskResponse
 */
export interface MuleRouterWanTaskResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {MuleRouterWanTaskResponseTaskInfo}
     * @memberof MuleRouterWanTaskResponse
     */
    taskInfo?: MuleRouterWanTaskResponseTaskInfo;
    /**
     * 
     * @type {Videos}
     * @memberof MuleRouterWanTaskResponse
     */
    videos?: Videos;
}

/**
 * Check if a given object implements the MuleRouterWanTaskResponse interface.
 */
export function instanceOfMuleRouterWanTaskResponse(value: object): value is MuleRouterWanTaskResponse {
    return true;
}

export function MuleRouterWanTaskResponseFromJSON(json: any): MuleRouterWanTaskResponse {
    return MuleRouterWanTaskResponseFromJSONTyped(json, false);
}

export function MuleRouterWanTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MuleRouterWanTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'taskInfo': json['task_info'] == null ? undefined : MuleRouterWanTaskResponseTaskInfoFromJSON(json['task_info']),
        'videos': json['videos'] == null ? undefined : VideosFromJSON(json['videos']),
    };
}

  export function MuleRouterWanTaskResponseToJSON(json: any): MuleRouterWanTaskResponse {
      return MuleRouterWanTaskResponseToJSONTyped(json, false);
  }

  export function MuleRouterWanTaskResponseToJSONTyped(value?: MuleRouterWanTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'task_info': MuleRouterWanTaskResponseTaskInfoToJSON(value['taskInfo']),
        'videos': VideosToJSON(value['videos']),
    };
}

