/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuleRouterWanTaskInfo } from './MuleRouterWanTaskInfo';
import {
    MuleRouterWanTaskInfoFromJSON,
    MuleRouterWanTaskInfoFromJSONTyped,
    MuleRouterWanTaskInfoToJSON,
    MuleRouterWanTaskInfoToJSONTyped,
} from './MuleRouterWanTaskInfo';
import type { MuleRouterWanTaskInfoError } from './MuleRouterWanTaskInfoError';
import {
    MuleRouterWanTaskInfoErrorFromJSON,
    MuleRouterWanTaskInfoErrorFromJSONTyped,
    MuleRouterWanTaskInfoErrorToJSON,
    MuleRouterWanTaskInfoErrorToJSONTyped,
} from './MuleRouterWanTaskInfoError';

/**
 * 
 * @export
 * @interface MuleRouterWanTaskResponseTaskInfo
 */
export interface MuleRouterWanTaskResponseTaskInfo {
    /**
     * 
     * @type {string}
     * @memberof MuleRouterWanTaskResponseTaskInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MuleRouterWanTaskResponseTaskInfo
     */
    status: MuleRouterWanTaskResponseTaskInfoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof MuleRouterWanTaskResponseTaskInfo
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof MuleRouterWanTaskResponseTaskInfo
     */
    updatedAt: string;
    /**
     * 
     * @type {MuleRouterWanTaskInfoError}
     * @memberof MuleRouterWanTaskResponseTaskInfo
     */
    error?: MuleRouterWanTaskInfoError;
}


/**
 * @export
 */
export const MuleRouterWanTaskResponseTaskInfoStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type MuleRouterWanTaskResponseTaskInfoStatusEnum = typeof MuleRouterWanTaskResponseTaskInfoStatusEnum[keyof typeof MuleRouterWanTaskResponseTaskInfoStatusEnum];


/**
 * Check if a given object implements the MuleRouterWanTaskResponseTaskInfo interface.
 */
export function instanceOfMuleRouterWanTaskResponseTaskInfo(value: object): value is MuleRouterWanTaskResponseTaskInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MuleRouterWanTaskResponseTaskInfoFromJSON(json: any): MuleRouterWanTaskResponseTaskInfo {
    return MuleRouterWanTaskResponseTaskInfoFromJSONTyped(json, false);
}

export function MuleRouterWanTaskResponseTaskInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MuleRouterWanTaskResponseTaskInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'error': json['error'] == null ? undefined : MuleRouterWanTaskInfoErrorFromJSON(json['error']),
    };
}

  export function MuleRouterWanTaskResponseTaskInfoToJSON(json: any): MuleRouterWanTaskResponseTaskInfo {
      return MuleRouterWanTaskResponseTaskInfoToJSONTyped(json, false);
  }

  export function MuleRouterWanTaskResponseTaskInfoToJSONTyped(value?: MuleRouterWanTaskResponseTaskInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'error': MuleRouterWanTaskInfoErrorToJSON(value['error']),
    };
}

