/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationCountsResponse
 */
export interface NotificationCountsResponse {
    /**
     * 
     * @type {number}
     * @memberof NotificationCountsResponse
     */
    total: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof NotificationCountsResponse
     */
    categories: { [key: string]: number; };
}

/**
 * Check if a given object implements the NotificationCountsResponse interface.
 */
export function instanceOfNotificationCountsResponse(value: object): value is NotificationCountsResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function NotificationCountsResponseFromJSON(json: any): NotificationCountsResponse {
    return NotificationCountsResponseFromJSONTyped(json, false);
}

export function NotificationCountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationCountsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'categories': json['categories'],
    };
}

  export function NotificationCountsResponseToJSON(json: any): NotificationCountsResponse {
      return NotificationCountsResponseToJSONTyped(json, false);
  }

  export function NotificationCountsResponseToJSONTyped(value?: NotificationCountsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'categories': value['categories'],
    };
}

