/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LikedPostNotification } from './LikedPostNotification';
import {
    LikedPostNotificationFromJSON,
    LikedPostNotificationFromJSONTyped,
    LikedPostNotificationToJSON,
    LikedPostNotificationToJSONTyped,
} from './LikedPostNotification';

/**
 * 
 * @export
 * @interface NotificationPostsResponse
 */
export interface NotificationPostsResponse {
    /**
     * 
     * @type {Array<LikedPostNotification>}
     * @memberof NotificationPostsResponse
     */
    posts: Array<LikedPostNotification>;
    /**
     * 
     * @type {string}
     * @memberof NotificationPostsResponse
     */
    paginationToken: string | null;
}

/**
 * Check if a given object implements the NotificationPostsResponse interface.
 */
export function instanceOfNotificationPostsResponse(value: object): value is NotificationPostsResponse {
    if (!('posts' in value) || value['posts'] === undefined) return false;
    if (!('paginationToken' in value) || value['paginationToken'] === undefined) return false;
    return true;
}

export function NotificationPostsResponseFromJSON(json: any): NotificationPostsResponse {
    return NotificationPostsResponseFromJSONTyped(json, false);
}

export function NotificationPostsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationPostsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'posts': ((json['posts'] as Array<any>).map(LikedPostNotificationFromJSON)),
        'paginationToken': json['pagination_token'],
    };
}

  export function NotificationPostsResponseToJSON(json: any): NotificationPostsResponse {
      return NotificationPostsResponseToJSONTyped(json, false);
  }

  export function NotificationPostsResponseToJSONTyped(value?: NotificationPostsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'posts': ((value['posts'] as Array<any>).map(LikedPostNotificationToJSON)),
        'pagination_token': value['paginationToken'],
    };
}

