/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OneTimeTokens
 */
export interface OneTimeTokens {
}

/**
 * Check if a given object implements the OneTimeTokens interface.
 */
export function instanceOfOneTimeTokens(value: object): value is OneTimeTokens {
    return true;
}

export function OneTimeTokensFromJSON(json: any): OneTimeTokens {
    return OneTimeTokensFromJSONTyped(json, false);
}

export function OneTimeTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneTimeTokens {
    return json;
}

  export function OneTimeTokensToJSON(json: any): OneTimeTokens {
      return OneTimeTokensToJSONTyped(json, false);
  }

  export function OneTimeTokensToJSONTyped(value?: OneTimeTokens | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

