/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentType } from './ContentType';
import {
    ContentTypeFromJSON,
    ContentTypeFromJSONTyped,
    ContentTypeToJSON,
    ContentTypeToJSONTyped,
} from './ContentType';

/**
 * 
 * @export
 * @interface PatchFollowNotificationsRequest
 */
export interface PatchFollowNotificationsRequest {
    /**
     * 
     * @type {ContentType}
     * @memberof PatchFollowNotificationsRequest
     */
    contentType: ContentType;
    /**
     * 
     * @type {boolean}
     * @memberof PatchFollowNotificationsRequest
     */
    enabled: boolean;
}



/**
 * Check if a given object implements the PatchFollowNotificationsRequest interface.
 */
export function instanceOfPatchFollowNotificationsRequest(value: object): value is PatchFollowNotificationsRequest {
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function PatchFollowNotificationsRequestFromJSON(json: any): PatchFollowNotificationsRequest {
    return PatchFollowNotificationsRequestFromJSONTyped(json, false);
}

export function PatchFollowNotificationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchFollowNotificationsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': ContentTypeFromJSON(json['content_type']),
        'enabled': json['enabled'],
    };
}

  export function PatchFollowNotificationsRequestToJSON(json: any): PatchFollowNotificationsRequest {
      return PatchFollowNotificationsRequestToJSONTyped(json, false);
  }

  export function PatchFollowNotificationsRequestToJSONTyped(value?: PatchFollowNotificationsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': ContentTypeToJSON(value['contentType']),
        'enabled': value['enabled'],
    };
}

