/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PaymentCurrency = {
    Usd: 'USD',
    Eur: 'EUR'
} as const;
export type PaymentCurrency = typeof PaymentCurrency[keyof typeof PaymentCurrency];


export function instanceOfPaymentCurrency(value: any): boolean {
    for (const key in PaymentCurrency) {
        if (Object.prototype.hasOwnProperty.call(PaymentCurrency, key)) {
            if (PaymentCurrency[key as keyof typeof PaymentCurrency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentCurrencyFromJSON(json: any): PaymentCurrency {
    return PaymentCurrencyFromJSONTyped(json, false);
}

export function PaymentCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCurrency {
    return json as PaymentCurrency;
}

export function PaymentCurrencyToJSON(value?: PaymentCurrency | null): any {
    return value as any;
}

export function PaymentCurrencyToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentCurrency {
    return value as PaymentCurrency;
}

