/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostGameAdventureImageRequest
 */
export interface PostGameAdventureImageRequest {
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureImageRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureImageRequest
     */
    messageRequestId: string;
}

/**
 * Check if a given object implements the PostGameAdventureImageRequest interface.
 */
export function instanceOfPostGameAdventureImageRequest(value: object): value is PostGameAdventureImageRequest {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('messageRequestId' in value) || value['messageRequestId'] === undefined) return false;
    return true;
}

export function PostGameAdventureImageRequestFromJSON(json: any): PostGameAdventureImageRequest {
    return PostGameAdventureImageRequestFromJSONTyped(json, false);
}

export function PostGameAdventureImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGameAdventureImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'],
        'messageRequestId': json['message_request_id'],
    };
}

  export function PostGameAdventureImageRequestToJSON(json: any): PostGameAdventureImageRequest {
      return PostGameAdventureImageRequestToJSONTyped(json, false);
  }

  export function PostGameAdventureImageRequestToJSONTyped(value?: PostGameAdventureImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'message_request_id': value['messageRequestId'],
    };
}

