/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameAdventureJournalEntry } from './GameAdventureJournalEntry';
import {
    GameAdventureJournalEntryFromJSON,
    GameAdventureJournalEntryFromJSONTyped,
    GameAdventureJournalEntryToJSON,
    GameAdventureJournalEntryToJSONTyped,
} from './GameAdventureJournalEntry';

/**
 * 
 * @export
 * @interface PostGameAdventureJournalReviewResponse
 */
export interface PostGameAdventureJournalReviewResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PostGameAdventureJournalReviewResponse
     */
    updated: boolean;
    /**
     * 
     * @type {Array<GameAdventureJournalEntry>}
     * @memberof PostGameAdventureJournalReviewResponse
     */
    journal: Array<GameAdventureJournalEntry>;
}

/**
 * Check if a given object implements the PostGameAdventureJournalReviewResponse interface.
 */
export function instanceOfPostGameAdventureJournalReviewResponse(value: object): value is PostGameAdventureJournalReviewResponse {
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('journal' in value) || value['journal'] === undefined) return false;
    return true;
}

export function PostGameAdventureJournalReviewResponseFromJSON(json: any): PostGameAdventureJournalReviewResponse {
    return PostGameAdventureJournalReviewResponseFromJSONTyped(json, false);
}

export function PostGameAdventureJournalReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGameAdventureJournalReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'updated': json['updated'],
        'journal': ((json['journal'] as Array<any>).map(GameAdventureJournalEntryFromJSON)),
    };
}

  export function PostGameAdventureJournalReviewResponseToJSON(json: any): PostGameAdventureJournalReviewResponse {
      return PostGameAdventureJournalReviewResponseToJSONTyped(json, false);
  }

  export function PostGameAdventureJournalReviewResponseToJSONTyped(value?: PostGameAdventureJournalReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updated': value['updated'],
        'journal': ((value['journal'] as Array<any>).map(GameAdventureJournalEntryToJSON)),
    };
}

