/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostLiveRoleplayRequest
 */
export interface PostLiveRoleplayRequest {
    /**
     * 
     * @type {string}
     * @memberof PostLiveRoleplayRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof PostLiveRoleplayRequest
     */
    query: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostLiveRoleplayRequest
     */
    debug?: boolean | null;
}

/**
 * Check if a given object implements the PostLiveRoleplayRequest interface.
 */
export function instanceOfPostLiveRoleplayRequest(value: object): value is PostLiveRoleplayRequest {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function PostLiveRoleplayRequestFromJSON(json: any): PostLiveRoleplayRequest {
    return PostLiveRoleplayRequestFromJSONTyped(json, false);
}

export function PostLiveRoleplayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLiveRoleplayRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'],
        'query': json['query'],
        'debug': json['debug'] == null ? undefined : json['debug'],
    };
}

  export function PostLiveRoleplayRequestToJSON(json: any): PostLiveRoleplayRequest {
      return PostLiveRoleplayRequestToJSONTyped(json, false);
  }

  export function PostLiveRoleplayRequestToJSONTyped(value?: PostLiveRoleplayRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'query': value['query'],
        'debug': value['debug'],
    };
}

