/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentType } from './ContentType';
import {
    ContentTypeFromJSON,
    ContentTypeFromJSONTyped,
    ContentTypeToJSON,
    ContentTypeToJSONTyped,
} from './ContentType';

/**
 * 
 * @export
 * @interface PostDonateRequest
 */
export interface PostDonateRequest {
    /**
     * 
     * @type {string}
     * @memberof PostDonateRequest
     */
    recipientUserId: string;
    /**
     * 
     * @type {number}
     * @memberof PostDonateRequest
     */
    tokens: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostDonateRequest
     */
    anonymous?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostDonateRequest
     */
    message?: string | null;
    /**
     * 
     * @type {ContentType}
     * @memberof PostDonateRequest
     */
    contentType?: ContentType | null;
    /**
     * 
     * @type {string}
     * @memberof PostDonateRequest
     */
    contentId?: string | null;
}



/**
 * Check if a given object implements the PostDonateRequest interface.
 */
export function instanceOfPostDonateRequest(value: object): value is PostDonateRequest {
    if (!('recipientUserId' in value) || value['recipientUserId'] === undefined) return false;
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    return true;
}

export function PostDonateRequestFromJSON(json: any): PostDonateRequest {
    return PostDonateRequestFromJSONTyped(json, false);
}

export function PostDonateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDonateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientUserId': json['recipient_user_id'],
        'tokens': json['tokens'],
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
        'message': json['message'] == null ? undefined : json['message'],
        'contentType': json['content_type'] == null ? undefined : ContentTypeFromJSON(json['content_type']),
        'contentId': json['content_id'] == null ? undefined : json['content_id'],
    };
}

  export function PostDonateRequestToJSON(json: any): PostDonateRequest {
      return PostDonateRequestToJSONTyped(json, false);
  }

  export function PostDonateRequestToJSONTyped(value?: PostDonateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient_user_id': value['recipientUserId'],
        'tokens': value['tokens'],
        'anonymous': value['anonymous'],
        'message': value['message'],
        'content_type': ContentTypeToJSON(value['contentType']),
        'content_id': value['contentId'],
    };
}

