/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameAdventurePlayerAction } from './GameAdventurePlayerAction';
import {
    GameAdventurePlayerActionFromJSON,
    GameAdventurePlayerActionFromJSONTyped,
    GameAdventurePlayerActionToJSON,
    GameAdventurePlayerActionToJSONTyped,
} from './GameAdventurePlayerAction';
import type { LLM } from './LLM';
import {
    LLMFromJSON,
    LLMFromJSONTyped,
    LLMToJSON,
    LLMToJSONTyped,
} from './LLM';

/**
 * 
 * @export
 * @interface PostGameAdventureMessageRequest
 */
export interface PostGameAdventureMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureMessageRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureMessageRequest
     */
    content?: string | null;
    /**
     * 
     * @type {GameAdventurePlayerAction}
     * @memberof PostGameAdventureMessageRequest
     */
    action?: GameAdventurePlayerAction | null;
    /**
     * 
     * @type {LLM}
     * @memberof PostGameAdventureMessageRequest
     */
    llmModel?: LLM | null;
}



/**
 * Check if a given object implements the PostGameAdventureMessageRequest interface.
 */
export function instanceOfPostGameAdventureMessageRequest(value: object): value is PostGameAdventureMessageRequest {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function PostGameAdventureMessageRequestFromJSON(json: any): PostGameAdventureMessageRequest {
    return PostGameAdventureMessageRequestFromJSONTyped(json, false);
}

export function PostGameAdventureMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGameAdventureMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'action': json['action'] == null ? undefined : GameAdventurePlayerActionFromJSON(json['action']),
        'llmModel': json['llm_model'] == null ? undefined : LLMFromJSON(json['llm_model']),
    };
}

  export function PostGameAdventureMessageRequestToJSON(json: any): PostGameAdventureMessageRequest {
      return PostGameAdventureMessageRequestToJSONTyped(json, false);
  }

  export function PostGameAdventureMessageRequestToJSONTyped(value?: PostGameAdventureMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'content': value['content'],
        'action': GameAdventurePlayerActionToJSON(value['action']),
        'llm_model': LLMToJSON(value['llmModel']),
    };
}

