/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostInstanceDestroyResponse
 */
export interface PostInstanceDestroyResponse {
    /**
     * 
     * @type {string}
     * @memberof PostInstanceDestroyResponse
     */
    instanceId: string;
}

/**
 * Check if a given object implements the PostInstanceDestroyResponse interface.
 */
export function instanceOfPostInstanceDestroyResponse(value: object): value is PostInstanceDestroyResponse {
    if (!('instanceId' in value) || value['instanceId'] === undefined) return false;
    return true;
}

export function PostInstanceDestroyResponseFromJSON(json: any): PostInstanceDestroyResponse {
    return PostInstanceDestroyResponseFromJSONTyped(json, false);
}

export function PostInstanceDestroyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostInstanceDestroyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'instanceId': json['instance_id'],
    };
}

  export function PostInstanceDestroyResponseToJSON(json: any): PostInstanceDestroyResponse {
      return PostInstanceDestroyResponseToJSONTyped(json, false);
  }

  export function PostInstanceDestroyResponseToJSONTyped(value?: PostInstanceDestroyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance_id': value['instanceId'],
    };
}

