/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageToVideoRequest } from './ImageToVideoRequest';
import {
    ImageToVideoRequestFromJSON,
    ImageToVideoRequestFromJSONTyped,
    ImageToVideoRequestToJSON,
    ImageToVideoRequestToJSONTyped,
} from './ImageToVideoRequest';

/**
 * 
 * @export
 * @interface PostGameAdventureVideoRequest
 */
export interface PostGameAdventureVideoRequest {
    /**
     * 
     * @type {ImageToVideoRequest}
     * @memberof PostGameAdventureVideoRequest
     */
    video: ImageToVideoRequest;
}

/**
 * Check if a given object implements the PostGameAdventureVideoRequest interface.
 */
export function instanceOfPostGameAdventureVideoRequest(value: object): value is PostGameAdventureVideoRequest {
    if (!('video' in value) || value['video'] === undefined) return false;
    return true;
}

export function PostGameAdventureVideoRequestFromJSON(json: any): PostGameAdventureVideoRequest {
    return PostGameAdventureVideoRequestFromJSONTyped(json, false);
}

export function PostGameAdventureVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGameAdventureVideoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'video': ImageToVideoRequestFromJSON(json['video']),
    };
}

  export function PostGameAdventureVideoRequestToJSON(json: any): PostGameAdventureVideoRequest {
      return PostGameAdventureVideoRequestToJSONTyped(json, false);
  }

  export function PostGameAdventureVideoRequestToJSONTyped(value?: PostGameAdventureVideoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video': ImageToVideoRequestToJSON(value['video']),
    };
}

