/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostGameAdventureJournalReviewRequest
 */
export interface PostGameAdventureJournalReviewRequest {
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureJournalReviewRequest
     */
    messageRequestId: string;
}

/**
 * Check if a given object implements the PostGameAdventureJournalReviewRequest interface.
 */
export function instanceOfPostGameAdventureJournalReviewRequest(value: object): value is PostGameAdventureJournalReviewRequest {
    if (!('messageRequestId' in value) || value['messageRequestId'] === undefined) return false;
    return true;
}

export function PostGameAdventureJournalReviewRequestFromJSON(json: any): PostGameAdventureJournalReviewRequest {
    return PostGameAdventureJournalReviewRequestFromJSONTyped(json, false);
}

export function PostGameAdventureJournalReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGameAdventureJournalReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messageRequestId': json['message_request_id'],
    };
}

  export function PostGameAdventureJournalReviewRequestToJSON(json: any): PostGameAdventureJournalReviewRequest {
      return PostGameAdventureJournalReviewRequestToJSONTyped(json, false);
  }

  export function PostGameAdventureJournalReviewRequestToJSONTyped(value?: PostGameAdventureJournalReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message_request_id': value['messageRequestId'],
    };
}

