/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostGameAdventureMediaResponse
 */
export interface PostGameAdventureMediaResponse {
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureMediaResponse
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof PostGameAdventureMediaResponse
     */
    contentId: string;
}

/**
 * Check if a given object implements the PostGameAdventureMediaResponse interface.
 */
export function instanceOfPostGameAdventureMediaResponse(value: object): value is PostGameAdventureMediaResponse {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('contentId' in value) || value['contentId'] === undefined) return false;
    return true;
}

export function PostGameAdventureMediaResponseFromJSON(json: any): PostGameAdventureMediaResponse {
    return PostGameAdventureMediaResponseFromJSONTyped(json, false);
}

export function PostGameAdventureMediaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGameAdventureMediaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['message_id'],
        'contentId': json['content_id'],
    };
}

  export function PostGameAdventureMediaResponseToJSON(json: any): PostGameAdventureMediaResponse {
      return PostGameAdventureMediaResponseToJSONTyped(json, false);
  }

  export function PostGameAdventureMediaResponseToJSONTyped(value?: PostGameAdventureMediaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message_id': value['messageId'],
        'content_id': value['contentId'],
    };
}

