/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatchUserPreferenceProfileRequest } from './PatchUserPreferenceProfileRequest';
import {
    PatchUserPreferenceProfileRequestFromJSON,
    PatchUserPreferenceProfileRequestFromJSONTyped,
    PatchUserPreferenceProfileRequestToJSON,
    PatchUserPreferenceProfileRequestToJSONTyped,
} from './PatchUserPreferenceProfileRequest';

/**
 * 
 * @export
 * @interface PostUserPreferencesOnboardingRequest
 */
export interface PostUserPreferencesOnboardingRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserPreferencesOnboardingRequest
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof PostUserPreferencesOnboardingRequest
     */
    version: string;
    /**
     * 
     * @type {Date}
     * @memberof PostUserPreferencesOnboardingRequest
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {PatchUserPreferenceProfileRequest}
     * @memberof PostUserPreferencesOnboardingRequest
     */
    preferences: PatchUserPreferenceProfileRequest;
}

/**
 * Check if a given object implements the PostUserPreferencesOnboardingRequest interface.
 */
export function instanceOfPostUserPreferencesOnboardingRequest(value: object): value is PostUserPreferencesOnboardingRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('preferences' in value) || value['preferences'] === undefined) return false;
    return true;
}

export function PostUserPreferencesOnboardingRequestFromJSON(json: any): PostUserPreferencesOnboardingRequest {
    return PostUserPreferencesOnboardingRequestFromJSONTyped(json, false);
}

export function PostUserPreferencesOnboardingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUserPreferencesOnboardingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'version': json['version'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'preferences': PatchUserPreferenceProfileRequestFromJSON(json['preferences']),
    };
}

  export function PostUserPreferencesOnboardingRequestToJSON(json: any): PostUserPreferencesOnboardingRequest {
      return PostUserPreferencesOnboardingRequestToJSONTyped(json, false);
  }

  export function PostUserPreferencesOnboardingRequestToJSONTyped(value?: PostUserPreferencesOnboardingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'version': value['version'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'preferences': PatchUserPreferenceProfileRequestToJSON(value['preferences']),
    };
}

