/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAnonymousChatRequest
 */
export interface PostAnonymousChatRequest {
    /**
     * 
     * @type {string}
     * @memberof PostAnonymousChatRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PostAnonymousChatRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof PostAnonymousChatRequest
     */
    query: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostAnonymousChatRequest
     */
    debug?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PostAnonymousChatRequest
     */
    conversationId: string;
}

/**
 * Check if a given object implements the PostAnonymousChatRequest interface.
 */
export function instanceOfPostAnonymousChatRequest(value: object): value is PostAnonymousChatRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    return true;
}

export function PostAnonymousChatRequestFromJSON(json: any): PostAnonymousChatRequest {
    return PostAnonymousChatRequestFromJSONTyped(json, false);
}

export function PostAnonymousChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAnonymousChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'requestId': json['request_id'],
        'query': json['query'],
        'debug': json['debug'] == null ? undefined : json['debug'],
        'conversationId': json['conversation_id'],
    };
}

  export function PostAnonymousChatRequestToJSON(json: any): PostAnonymousChatRequest {
      return PostAnonymousChatRequestToJSONTyped(json, false);
  }

  export function PostAnonymousChatRequestToJSONTyped(value?: PostAnonymousChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'request_id': value['requestId'],
        'query': value['query'],
        'debug': value['debug'],
        'conversation_id': value['conversationId'],
    };
}

