/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPreferenceModel } from './UserPreferenceModel';
import {
    UserPreferenceModelFromJSON,
    UserPreferenceModelFromJSONTyped,
    UserPreferenceModelToJSON,
    UserPreferenceModelToJSONTyped,
} from './UserPreferenceModel';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender';
import type { LLM } from './LLM';
import {
    LLMFromJSON,
    LLMFromJSONTyped,
    LLMToJSON,
    LLMToJSONTyped,
} from './LLM';

/**
 * 
 * @export
 * @interface Preferences
 */
export interface Preferences {
    /**
     * 
     * @type {Date}
     * @memberof Preferences
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Preferences
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Preferences
     */
    displayGirls?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Preferences
     */
    displayAnime?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Preferences
     */
    usernameUpdated?: boolean;
    /**
     * 
     * @type {LLM}
     * @memberof Preferences
     */
    llmName?: LLM;
    /**
     * 
     * @type {Gender}
     * @memberof Preferences
     */
    gender?: Gender;
    /**
     * 
     * @type {Array<string>}
     * @memberof Preferences
     */
    preferredContentStyles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Preferences
     */
    preferredContentGenders?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Preferences
     */
    preferredOrientations?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    pronouns?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Preferences
     */
    onboardingState?: { [key: string]: any; };
}



/**
 * Check if a given object implements the Preferences interface.
 */
export function instanceOfPreferences(value: object): value is Preferences {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function PreferencesFromJSON(json: any): Preferences {
    return PreferencesFromJSONTyped(json, false);
}

export function PreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preferences {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'],
        'displayGirls': json['display_girls'] == null ? undefined : json['display_girls'],
        'displayAnime': json['display_anime'] == null ? undefined : json['display_anime'],
        'usernameUpdated': json['username_updated'] == null ? undefined : json['username_updated'],
        'llmName': json['llm_name'] == null ? undefined : LLMFromJSON(json['llm_name']),
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'preferredContentStyles': json['preferred_content_styles'] == null ? undefined : json['preferred_content_styles'],
        'preferredContentGenders': json['preferred_content_genders'] == null ? undefined : json['preferred_content_genders'],
        'preferredOrientations': json['preferred_orientations'] == null ? undefined : json['preferred_orientations'],
        'pronouns': json['pronouns'] == null ? undefined : json['pronouns'],
        'onboardingState': json['onboarding_state'] == null ? undefined : json['onboarding_state'],
    };
}

  export function PreferencesToJSON(json: any): Preferences {
      return PreferencesToJSONTyped(json, false);
  }

  export function PreferencesToJSONTyped(value?: Preferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
        'user_id': value['userId'],
        'display_girls': value['displayGirls'],
        'display_anime': value['displayAnime'],
        'username_updated': value['usernameUpdated'],
        'llm_name': LLMToJSON(value['llmName']),
        'gender': GenderToJSON(value['gender']),
        'preferred_content_styles': value['preferredContentStyles'],
        'preferred_content_genders': value['preferredContentGenders'],
        'preferred_orientations': value['preferredOrientations'],
        'pronouns': value['pronouns'],
        'onboarding_state': value['onboardingState'],
    };
}

