/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PricingDisplayContext = {
    Addon: 'addon',
    Premium: 'premium',
    Ultra: 'ultra'
} as const;
export type PricingDisplayContext = typeof PricingDisplayContext[keyof typeof PricingDisplayContext];


export function instanceOfPricingDisplayContext(value: any): boolean {
    for (const key in PricingDisplayContext) {
        if (Object.prototype.hasOwnProperty.call(PricingDisplayContext, key)) {
            if (PricingDisplayContext[key as keyof typeof PricingDisplayContext] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PricingDisplayContextFromJSON(json: any): PricingDisplayContext {
    return PricingDisplayContextFromJSONTyped(json, false);
}

export function PricingDisplayContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingDisplayContext {
    return json as PricingDisplayContext;
}

export function PricingDisplayContextToJSON(value?: PricingDisplayContext | null): any {
    return value as any;
}

export function PricingDisplayContextToJSONTyped(value: any, ignoreDiscriminator: boolean): PricingDisplayContext {
    return value as PricingDisplayContext;
}

