/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromotionResponse } from './PromotionResponse';
import {
    PromotionResponseFromJSON,
    PromotionResponseFromJSONTyped,
    PromotionResponseToJSON,
    PromotionResponseToJSONTyped,
} from './PromotionResponse';

/**
 * 
 * @export
 * @interface PromotionListResponse
 */
export interface PromotionListResponse {
    /**
     * 
     * @type {Array<PromotionResponse>}
     * @memberof PromotionListResponse
     */
    promotions: Array<PromotionResponse>;
}

/**
 * Check if a given object implements the PromotionListResponse interface.
 */
export function instanceOfPromotionListResponse(value: object): value is PromotionListResponse {
    if (!('promotions' in value) || value['promotions'] === undefined) return false;
    return true;
}

export function PromotionListResponseFromJSON(json: any): PromotionListResponse {
    return PromotionListResponseFromJSONTyped(json, false);
}

export function PromotionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promotions': ((json['promotions'] as Array<any>).map(PromotionResponseFromJSON)),
    };
}

  export function PromotionListResponseToJSON(json: any): PromotionListResponse {
      return PromotionListResponseToJSONTyped(json, false);
  }

  export function PromotionListResponseToJSONTyped(value?: PromotionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promotions': ((value['promotions'] as Array<any>).map(PromotionResponseToJSON)),
    };
}

