/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromotionSummary
 */
export interface PromotionSummary {
    /**
     * 
     * @type {string}
     * @memberof PromotionSummary
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionSummary
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof PromotionSummary
     */
    percentOff: number;
    /**
     * 
     * @type {Date}
     * @memberof PromotionSummary
     */
    startsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PromotionSummary
     */
    endsAt: Date;
}

/**
 * Check if a given object implements the PromotionSummary interface.
 */
export function instanceOfPromotionSummary(value: object): value is PromotionSummary {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('percentOff' in value) || value['percentOff'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    return true;
}

export function PromotionSummaryFromJSON(json: any): PromotionSummary {
    return PromotionSummaryFromJSONTyped(json, false);
}

export function PromotionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'title': json['title'],
        'percentOff': json['percent_off'],
        'startsAt': (new Date(json['starts_at'])),
        'endsAt': (new Date(json['ends_at'])),
    };
}

  export function PromotionSummaryToJSON(json: any): PromotionSummary {
      return PromotionSummaryToJSONTyped(json, false);
  }

  export function PromotionSummaryToJSONTyped(value?: PromotionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'title': value['title'],
        'percent_off': value['percentOff'],
        'starts_at': ((value['startsAt']).toISOString()),
        'ends_at': ((value['endsAt']).toISOString()),
    };
}

