/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentType } from './ContentType';
import {
    ContentTypeFromJSON,
    ContentTypeFromJSONTyped,
    ContentTypeToJSON,
    ContentTypeToJSONTyped,
} from './ContentType';

/**
 * 
 * @export
 * @interface PutFollowNotificationsRequest
 */
export interface PutFollowNotificationsRequest {
    /**
     * 
     * @type {string}
     * @memberof PutFollowNotificationsRequest
     */
    followeeId: string;
    /**
     * 
     * @type {Array<ContentType>}
     * @memberof PutFollowNotificationsRequest
     */
    contentTypes: Array<ContentType>;
}

/**
 * Check if a given object implements the PutFollowNotificationsRequest interface.
 */
export function instanceOfPutFollowNotificationsRequest(value: object): value is PutFollowNotificationsRequest {
    if (!('followeeId' in value) || value['followeeId'] === undefined) return false;
    if (!('contentTypes' in value) || value['contentTypes'] === undefined) return false;
    return true;
}

export function PutFollowNotificationsRequestFromJSON(json: any): PutFollowNotificationsRequest {
    return PutFollowNotificationsRequestFromJSONTyped(json, false);
}

export function PutFollowNotificationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutFollowNotificationsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'followeeId': json['followee_id'],
        'contentTypes': ((json['content_types'] as Array<any>).map(ContentTypeFromJSON)),
    };
}

  export function PutFollowNotificationsRequestToJSON(json: any): PutFollowNotificationsRequest {
      return PutFollowNotificationsRequestToJSONTyped(json, false);
  }

  export function PutFollowNotificationsRequestToJSONTyped(value?: PutFollowNotificationsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'followee_id': value['followeeId'],
        'content_types': ((value['contentTypes'] as Array<any>).map(ContentTypeToJSON)),
    };
}

