/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RedeemAgeVerificationResponse
 */
export interface RedeemAgeVerificationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RedeemAgeVerificationResponse
     */
    verified: boolean;
}

/**
 * Check if a given object implements the RedeemAgeVerificationResponse interface.
 */
export function instanceOfRedeemAgeVerificationResponse(value: object): value is RedeemAgeVerificationResponse {
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function RedeemAgeVerificationResponseFromJSON(json: any): RedeemAgeVerificationResponse {
    return RedeemAgeVerificationResponseFromJSONTyped(json, false);
}

export function RedeemAgeVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedeemAgeVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verified': json['verified'],
    };
}

  export function RedeemAgeVerificationResponseToJSON(json: any): RedeemAgeVerificationResponse {
      return RedeemAgeVerificationResponseToJSONTyped(json, false);
  }

  export function RedeemAgeVerificationResponseToJSONTyped(value?: RedeemAgeVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verified': value['verified'],
    };
}

