/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RedeemAgeVerificationRequest
 */
export interface RedeemAgeVerificationRequest {
    /**
     * 
     * @type {string}
     * @memberof RedeemAgeVerificationRequest
     */
    ticket: string;
}

/**
 * Check if a given object implements the RedeemAgeVerificationRequest interface.
 */
export function instanceOfRedeemAgeVerificationRequest(value: object): value is RedeemAgeVerificationRequest {
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    return true;
}

export function RedeemAgeVerificationRequestFromJSON(json: any): RedeemAgeVerificationRequest {
    return RedeemAgeVerificationRequestFromJSONTyped(json, false);
}

export function RedeemAgeVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedeemAgeVerificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ticket': json['ticket'],
    };
}

  export function RedeemAgeVerificationRequestToJSON(json: any): RedeemAgeVerificationRequest {
      return RedeemAgeVerificationRequestToJSONTyped(json, false);
  }

  export function RedeemAgeVerificationRequestToJSONTyped(value?: RedeemAgeVerificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticket': value['ticket'],
    };
}

