/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WanTaskOutput } from './WanTaskOutput';
import {
    WanTaskOutputFromJSON,
    WanTaskOutputFromJSONTyped,
    WanTaskOutputToJSON,
    WanTaskOutputToJSONTyped,
} from './WanTaskOutput';
import type { MuleRouterWanTaskResponseTaskInfo } from './MuleRouterWanTaskResponseTaskInfo';
import {
    MuleRouterWanTaskResponseTaskInfoFromJSON,
    MuleRouterWanTaskResponseTaskInfoFromJSONTyped,
    MuleRouterWanTaskResponseTaskInfoToJSON,
    MuleRouterWanTaskResponseTaskInfoToJSONTyped,
} from './MuleRouterWanTaskResponseTaskInfo';
import type { WanTaskResponse } from './WanTaskResponse';
import {
    WanTaskResponseFromJSON,
    WanTaskResponseFromJSONTyped,
    WanTaskResponseToJSON,
    WanTaskResponseToJSONTyped,
} from './WanTaskResponse';
import type { MuleRouterWanTaskResponse } from './MuleRouterWanTaskResponse';
import {
    MuleRouterWanTaskResponseFromJSON,
    MuleRouterWanTaskResponseFromJSONTyped,
    MuleRouterWanTaskResponseToJSON,
    MuleRouterWanTaskResponseToJSONTyped,
} from './MuleRouterWanTaskResponse';
import type { Videos } from './Videos';
import {
    VideosFromJSON,
    VideosFromJSONTyped,
    VideosToJSON,
    VideosToJSONTyped,
} from './Videos';

/**
 * 
 * @export
 * @interface ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
 */
export interface ResponseGetWanTaskStatusVideoWanTaskTaskIdGet {
    /**
     * 
     * @type {MuleRouterWanTaskResponseTaskInfo}
     * @memberof ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
     */
    taskInfo?: MuleRouterWanTaskResponseTaskInfo;
    /**
     * 
     * @type {Videos}
     * @memberof ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
     */
    videos?: Videos;
    /**
     * 
     * @type {string}
     * @memberof ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
     */
    requestId?: string;
    /**
     * 
     * @type {WanTaskOutput}
     * @memberof ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
     */
    output?: WanTaskOutput;
    /**
     * 
     * @type {string}
     * @memberof ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGetWanTaskStatusVideoWanTaskTaskIdGet
     */
    message?: string;
}

/**
 * Check if a given object implements the ResponseGetWanTaskStatusVideoWanTaskTaskIdGet interface.
 */
export function instanceOfResponseGetWanTaskStatusVideoWanTaskTaskIdGet(value: object): value is ResponseGetWanTaskStatusVideoWanTaskTaskIdGet {
    return true;
}

export function ResponseGetWanTaskStatusVideoWanTaskTaskIdGetFromJSON(json: any): ResponseGetWanTaskStatusVideoWanTaskTaskIdGet {
    return ResponseGetWanTaskStatusVideoWanTaskTaskIdGetFromJSONTyped(json, false);
}

export function ResponseGetWanTaskStatusVideoWanTaskTaskIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetWanTaskStatusVideoWanTaskTaskIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'taskInfo': json['task_info'] == null ? undefined : MuleRouterWanTaskResponseTaskInfoFromJSON(json['task_info']),
        'videos': json['videos'] == null ? undefined : VideosFromJSON(json['videos']),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'output': json['output'] == null ? undefined : WanTaskOutputFromJSON(json['output']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

  export function ResponseGetWanTaskStatusVideoWanTaskTaskIdGetToJSON(json: any): ResponseGetWanTaskStatusVideoWanTaskTaskIdGet {
      return ResponseGetWanTaskStatusVideoWanTaskTaskIdGetToJSONTyped(json, false);
  }

  export function ResponseGetWanTaskStatusVideoWanTaskTaskIdGetToJSONTyped(value?: ResponseGetWanTaskStatusVideoWanTaskTaskIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_info': MuleRouterWanTaskResponseTaskInfoToJSON(value['taskInfo']),
        'videos': VideosToJSON(value['videos']),
        'request_id': value['requestId'],
        'output': WanTaskOutputToJSON(value['output']),
        'code': value['code'],
        'message': value['message'],
    };
}

