/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeedanceImageToVideoCompletionPayload
 */
export interface SeedanceImageToVideoCompletionPayload {
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    videoUrl: string;
}

/**
 * Check if a given object implements the SeedanceImageToVideoCompletionPayload interface.
 */
export function instanceOfSeedanceImageToVideoCompletionPayload(value: object): value is SeedanceImageToVideoCompletionPayload {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('videoUrl' in value) || value['videoUrl'] === undefined) return false;
    return true;
}

export function SeedanceImageToVideoCompletionPayloadFromJSON(json: any): SeedanceImageToVideoCompletionPayload {
    return SeedanceImageToVideoCompletionPayloadFromJSONTyped(json, false);
}

export function SeedanceImageToVideoCompletionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedanceImageToVideoCompletionPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['video_id'],
        'videoUrl': json['video_url'],
    };
}

  export function SeedanceImageToVideoCompletionPayloadToJSON(json: any): SeedanceImageToVideoCompletionPayload {
      return SeedanceImageToVideoCompletionPayloadToJSONTyped(json, false);
  }

  export function SeedanceImageToVideoCompletionPayloadToJSONTyped(value?: SeedanceImageToVideoCompletionPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_id': value['videoId'],
        'video_url': value['videoUrl'],
    };
}

