/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeedanceImageToVideoResponse
 */
export interface SeedanceImageToVideoResponse {
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoResponse
     */
    id: string;
}

/**
 * Check if a given object implements the SeedanceImageToVideoResponse interface.
 */
export function instanceOfSeedanceImageToVideoResponse(value: object): value is SeedanceImageToVideoResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SeedanceImageToVideoResponseFromJSON(json: any): SeedanceImageToVideoResponse {
    return SeedanceImageToVideoResponseFromJSONTyped(json, false);
}

export function SeedanceImageToVideoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedanceImageToVideoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

  export function SeedanceImageToVideoResponseToJSON(json: any): SeedanceImageToVideoResponse {
      return SeedanceImageToVideoResponseToJSONTyped(json, false);
  }

  export function SeedanceImageToVideoResponseToJSONTyped(value?: SeedanceImageToVideoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

