/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeedConversationResponse
 */
export interface SeedConversationResponse {
    /**
     * 
     * @type {string}
     * @memberof SeedConversationResponse
     */
    conversationId: string;
    /**
     * 
     * @type {boolean}
     * @memberof SeedConversationResponse
     */
    seeded: boolean;
}

/**
 * Check if a given object implements the SeedConversationResponse interface.
 */
export function instanceOfSeedConversationResponse(value: object): value is SeedConversationResponse {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('seeded' in value) || value['seeded'] === undefined) return false;
    return true;
}

export function SeedConversationResponseFromJSON(json: any): SeedConversationResponse {
    return SeedConversationResponseFromJSONTyped(json, false);
}

export function SeedConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversation_id'],
        'seeded': json['seeded'],
    };
}

  export function SeedConversationResponseToJSON(json: any): SeedConversationResponse {
      return SeedConversationResponseToJSONTyped(json, false);
  }

  export function SeedConversationResponseToJSONTyped(value?: SeedConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation_id': value['conversationId'],
        'seeded': value['seeded'],
    };
}

