/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeedanceImageToVideoCompletionPayload
 */
export interface SeedanceImageToVideoCompletionPayload {
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    videoUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    lastFrameUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    resolution?: SeedanceImageToVideoCompletionPayloadResolutionEnum | null;
    /**
     * 
     * @type {number}
     * @memberof SeedanceImageToVideoCompletionPayload
     */
    duration?: number | null;
}


/**
 * @export
 */
export const SeedanceImageToVideoCompletionPayloadResolutionEnum = {
    _480p: '480p',
    _720p: '720p',
    _1080p: '1080p',
    _4k: '4k'
} as const;
export type SeedanceImageToVideoCompletionPayloadResolutionEnum = typeof SeedanceImageToVideoCompletionPayloadResolutionEnum[keyof typeof SeedanceImageToVideoCompletionPayloadResolutionEnum];


/**
 * Check if a given object implements the SeedanceImageToVideoCompletionPayload interface.
 */
export function instanceOfSeedanceImageToVideoCompletionPayload(value: object): value is SeedanceImageToVideoCompletionPayload {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('videoUrl' in value) || value['videoUrl'] === undefined) return false;
    return true;
}

export function SeedanceImageToVideoCompletionPayloadFromJSON(json: any): SeedanceImageToVideoCompletionPayload {
    return SeedanceImageToVideoCompletionPayloadFromJSONTyped(json, false);
}

export function SeedanceImageToVideoCompletionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedanceImageToVideoCompletionPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['video_id'],
        'videoUrl': json['video_url'],
        'lastFrameUrl': json['last_frame_url'] == null ? undefined : json['last_frame_url'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

  export function SeedanceImageToVideoCompletionPayloadToJSON(json: any): SeedanceImageToVideoCompletionPayload {
      return SeedanceImageToVideoCompletionPayloadToJSONTyped(json, false);
  }

  export function SeedanceImageToVideoCompletionPayloadToJSONTyped(value?: SeedanceImageToVideoCompletionPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_id': value['videoId'],
        'video_url': value['videoUrl'],
        'last_frame_url': value['lastFrameUrl'],
        'resolution': value['resolution'],
        'duration': value['duration'],
    };
}

