/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoResolution } from './VideoResolution';
import {
    VideoResolutionFromJSON,
    VideoResolutionFromJSONTyped,
    VideoResolutionToJSON,
    VideoResolutionToJSONTyped,
} from './VideoResolution';

/**
 * 
 * @export
 * @interface SeedanceImageToVideoRequest
 */
export interface SeedanceImageToVideoRequest {
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoRequest
     */
    chatbotId: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoRequest
     */
    inputImageId: string;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof SeedanceImageToVideoRequest
     */
    prompt: string;
    /**
     * 
     * @type {number}
     * @memberof SeedanceImageToVideoRequest
     */
    duration?: number;
    /**
     * 
     * @type {VideoResolution}
     * @memberof SeedanceImageToVideoRequest
     */
    resolution?: VideoResolution;
    /**
     * 
     * @type {boolean}
     * @memberof SeedanceImageToVideoRequest
     */
    watermark?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SeedanceImageToVideoRequest
     */
    audioGeneration?: boolean;
}



/**
 * Check if a given object implements the SeedanceImageToVideoRequest interface.
 */
export function instanceOfSeedanceImageToVideoRequest(value: object): value is SeedanceImageToVideoRequest {
    if (!('chatbotId' in value) || value['chatbotId'] === undefined) return false;
    if (!('inputImageId' in value) || value['inputImageId'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function SeedanceImageToVideoRequestFromJSON(json: any): SeedanceImageToVideoRequest {
    return SeedanceImageToVideoRequestFromJSONTyped(json, false);
}

export function SeedanceImageToVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedanceImageToVideoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chatbotId': json['chatbot_id'],
        'inputImageId': json['input_image_id'],
        'clientId': json['client_id'],
        'requestId': json['request_id'],
        'prompt': json['prompt'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'resolution': json['resolution'] == null ? undefined : VideoResolutionFromJSON(json['resolution']),
        'watermark': json['watermark'] == null ? undefined : json['watermark'],
        'audioGeneration': json['audio_generation'] == null ? undefined : json['audio_generation'],
    };
}

  export function SeedanceImageToVideoRequestToJSON(json: any): SeedanceImageToVideoRequest {
      return SeedanceImageToVideoRequestToJSONTyped(json, false);
  }

  export function SeedanceImageToVideoRequestToJSONTyped(value?: SeedanceImageToVideoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatbot_id': value['chatbotId'],
        'input_image_id': value['inputImageId'],
        'client_id': value['clientId'],
        'request_id': value['requestId'],
        'prompt': value['prompt'],
        'duration': value['duration'],
        'resolution': VideoResolutionToJSON(value['resolution']),
        'watermark': value['watermark'],
        'audio_generation': value['audioGeneration'],
    };
}

