/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveStreamSource } from './LiveStreamSource';
import {
    LiveStreamSourceFromJSON,
    LiveStreamSourceFromJSONTyped,
    LiveStreamSourceToJSON,
    LiveStreamSourceToJSONTyped,
} from './LiveStreamSource';
import type { LiveClipSource } from './LiveClipSource';
import {
    LiveClipSourceFromJSON,
    LiveClipSourceFromJSONTyped,
    LiveClipSourceToJSON,
    LiveClipSourceToJSONTyped,
} from './LiveClipSource';

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    kind?: SourceKindEnum;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    wsUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    llhlsUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    clipUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    posterUrl?: string;
}


/**
 * @export
 */
export const SourceKindEnum = {
    Clip: 'clip'
} as const;
export type SourceKindEnum = typeof SourceKindEnum[keyof typeof SourceKindEnum];


/**
 * Check if a given object implements the Source interface.
 */
export function instanceOfSource(value: object): value is Source {
    if (!('wsUrl' in value) || value['wsUrl'] === undefined) return false;
    if (!('llhlsUrl' in value) || value['llhlsUrl'] === undefined) return false;
    if (!('clipUrl' in value) || value['clipUrl'] === undefined) return false;
    return true;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'wsUrl': json['ws_url'],
        'llhlsUrl': json['llhls_url'],
        'token': json['token'] == null ? undefined : json['token'],
        'clipUrl': json['clip_url'],
        'posterUrl': json['poster_url'] == null ? undefined : json['poster_url'],
    };
}

  export function SourceToJSON(json: any): Source {
      return SourceToJSONTyped(json, false);
  }

  export function SourceToJSONTyped(value?: Source | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'ws_url': value['wsUrl'],
        'llhls_url': value['llhlsUrl'],
        'token': value['token'],
        'clip_url': value['clipUrl'],
        'poster_url': value['posterUrl'],
    };
}

