/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartsAt
 */
export interface StartsAt {
}

/**
 * Check if a given object implements the StartsAt interface.
 */
export function instanceOfStartsAt(value: object): value is StartsAt {
    return true;
}

export function StartsAtFromJSON(json: any): StartsAt {
    return StartsAtFromJSONTyped(json, false);
}

export function StartsAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartsAt {
    return json;
}

  export function StartsAtToJSON(json: any): StartsAt {
      return StartsAtToJSONTyped(json, false);
  }

  export function StartsAtToJSONTyped(value?: StartsAt | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

