/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageToVideoModel } from './ImageToVideoModel';
import {
    ImageToVideoModelFromJSON,
    ImageToVideoModelFromJSONTyped,
    ImageToVideoModelToJSON,
    ImageToVideoModelToJSONTyped,
} from './ImageToVideoModel';
import type { VideoResolution } from './VideoResolution';
import {
    VideoResolutionFromJSON,
    VideoResolutionFromJSONTyped,
    VideoResolutionToJSON,
    VideoResolutionToJSONTyped,
} from './VideoResolution';

/**
 * 
 * @export
 * @interface SubscriptionVideoGenerationEstimate
 */
export interface SubscriptionVideoGenerationEstimate {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    tokenCost: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    maximumMonthlyCount: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    unlimited: boolean;
    /**
     * 
     * @type {ImageToVideoModel}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    model: ImageToVideoModel;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    displayName: string;
    /**
     * 
     * @type {VideoResolution}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    resolution: VideoResolution;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionVideoGenerationEstimate
     */
    durationSeconds: number;
}



/**
 * Check if a given object implements the SubscriptionVideoGenerationEstimate interface.
 */
export function instanceOfSubscriptionVideoGenerationEstimate(value: object): value is SubscriptionVideoGenerationEstimate {
    if (!('tokenCost' in value) || value['tokenCost'] === undefined) return false;
    if (!('maximumMonthlyCount' in value) || value['maximumMonthlyCount'] === undefined) return false;
    if (!('unlimited' in value) || value['unlimited'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('durationSeconds' in value) || value['durationSeconds'] === undefined) return false;
    return true;
}

export function SubscriptionVideoGenerationEstimateFromJSON(json: any): SubscriptionVideoGenerationEstimate {
    return SubscriptionVideoGenerationEstimateFromJSONTyped(json, false);
}

export function SubscriptionVideoGenerationEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionVideoGenerationEstimate {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenCost': json['token_cost'],
        'maximumMonthlyCount': json['maximum_monthly_count'],
        'unlimited': json['unlimited'],
        'model': ImageToVideoModelFromJSON(json['model']),
        'displayName': json['display_name'],
        'resolution': VideoResolutionFromJSON(json['resolution']),
        'durationSeconds': json['duration_seconds'],
    };
}

  export function SubscriptionVideoGenerationEstimateToJSON(json: any): SubscriptionVideoGenerationEstimate {
      return SubscriptionVideoGenerationEstimateToJSONTyped(json, false);
  }

  export function SubscriptionVideoGenerationEstimateToJSONTyped(value?: SubscriptionVideoGenerationEstimate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token_cost': value['tokenCost'],
        'maximum_monthly_count': value['maximumMonthlyCount'],
        'unlimited': value['unlimited'],
        'model': ImageToVideoModelToJSON(value['model']),
        'display_name': value['displayName'],
        'resolution': VideoResolutionToJSON(value['resolution']),
        'duration_seconds': value['durationSeconds'],
    };
}

