/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionGenerationEstimate
 */
export interface SubscriptionGenerationEstimate {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionGenerationEstimate
     */
    tokenCost: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionGenerationEstimate
     */
    maximumMonthlyCount: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionGenerationEstimate
     */
    unlimited: boolean;
}

/**
 * Check if a given object implements the SubscriptionGenerationEstimate interface.
 */
export function instanceOfSubscriptionGenerationEstimate(value: object): value is SubscriptionGenerationEstimate {
    if (!('tokenCost' in value) || value['tokenCost'] === undefined) return false;
    if (!('maximumMonthlyCount' in value) || value['maximumMonthlyCount'] === undefined) return false;
    if (!('unlimited' in value) || value['unlimited'] === undefined) return false;
    return true;
}

export function SubscriptionGenerationEstimateFromJSON(json: any): SubscriptionGenerationEstimate {
    return SubscriptionGenerationEstimateFromJSONTyped(json, false);
}

export function SubscriptionGenerationEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionGenerationEstimate {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenCost': json['token_cost'],
        'maximumMonthlyCount': json['maximum_monthly_count'],
        'unlimited': json['unlimited'],
    };
}

  export function SubscriptionGenerationEstimateToJSON(json: any): SubscriptionGenerationEstimate {
      return SubscriptionGenerationEstimateToJSONTyped(json, false);
  }

  export function SubscriptionGenerationEstimateToJSONTyped(value?: SubscriptionGenerationEstimate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token_cost': value['tokenCost'],
        'maximum_monthly_count': value['maximumMonthlyCount'],
        'unlimited': value['unlimited'],
    };
}

