/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Title1
 */
export interface Title1 {
}

/**
 * Check if a given object implements the Title1 interface.
 */
export function instanceOfTitle1(value: object): value is Title1 {
    return true;
}

export function Title1FromJSON(json: any): Title1 {
    return Title1FromJSONTyped(json, false);
}

export function Title1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Title1 {
    return json;
}

  export function Title1ToJSON(json: any): Title1 {
      return Title1ToJSONTyped(json, false);
  }

  export function Title1ToJSONTyped(value?: Title1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

