/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Title
 */
export interface Title {
}

/**
 * Check if a given object implements the Title interface.
 */
export function instanceOfTitle(value: object): value is Title {
    return true;
}

export function TitleFromJSON(json: any): Title {
    return TitleFromJSONTyped(json, false);
}

export function TitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Title {
    return json;
}

  export function TitleToJSON(json: any): Title {
      return TitleToJSONTyped(json, false);
  }

  export function TitleToJSONTyped(value?: Title | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

