/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Why a user's token balance moved. Every balance change writes one `token_transaction` row tagged with one of these,
 * so spending can be broken down per feature and a user's history replays to their current balance.
 * @export
 */
export const TokenTransactionReason = {
    ChatMessage: 'chat_message',
    ImageGeneration: 'image_generation',
    CustomChatbotImage: 'custom_chatbot_image',
    VoiceGeneration: 'voice_generation',
    VideoGeneration: 'video_generation',
    GameAdventure: 'game_adventure',
    StoryEpisodePurchase: 'story_episode_purchase',
    BadgePurchase: 'badge_purchase',
    DonationSent: 'donation_sent',
    StoryEpisodeSale: 'story_episode_sale',
    BadgeAward: 'badge_award',
    DonationReceived: 'donation_received',
    GiftCode: 'gift_code',
    TokenPackPurchase: 'token_pack_purchase',
    SubscriptionActivation: 'subscription_activation',
    SubscriptionRenewal: 'subscription_renewal',
    SubscriptionBonus: 'subscription_bonus',
    RatingBonus: 'rating_bonus',
    SocialFollowBonus: 'social_follow_bonus',
    DailyLoginBonus: 'daily_login_bonus',
    AdminAdjustment: 'admin_adjustment',
    OpeningBalance: 'opening_balance'
} as const;
export type TokenTransactionReason = typeof TokenTransactionReason[keyof typeof TokenTransactionReason];


export function instanceOfTokenTransactionReason(value: any): boolean {
    for (const key in TokenTransactionReason) {
        if (Object.prototype.hasOwnProperty.call(TokenTransactionReason, key)) {
            if (TokenTransactionReason[key as keyof typeof TokenTransactionReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TokenTransactionReasonFromJSON(json: any): TokenTransactionReason {
    return TokenTransactionReasonFromJSONTyped(json, false);
}

export function TokenTransactionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenTransactionReason {
    return json as TokenTransactionReason;
}

export function TokenTransactionReasonToJSON(value?: TokenTransactionReason | null): any {
    return value as any;
}

export function TokenTransactionReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): TokenTransactionReason {
    return value as TokenTransactionReason;
}

