/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenUsageCalculationMode } from './TokenUsageCalculationMode';
import {
    TokenUsageCalculationModeFromJSON,
    TokenUsageCalculationModeFromJSONTyped,
    TokenUsageCalculationModeToJSON,
    TokenUsageCalculationModeToJSONTyped,
} from './TokenUsageCalculationMode';

/**
 * 
 * @export
 * @interface TokenPriceConfig
 */
export interface TokenPriceConfig {
    /**
     * 
     * @type {TokenUsageCalculationMode}
     * @memberof TokenPriceConfig
     */
    usageBy: TokenUsageCalculationMode;
    /**
     * 
     * @type {number}
     * @memberof TokenPriceConfig
     */
    tokenPrice: number;
    /**
     * 
     * @type {number}
     * @memberof TokenPriceConfig
     */
    unitSize: number;
    /**
     * 
     * @type {number}
     * @memberof TokenPriceConfig
     */
    minimumUnits: number;
}



/**
 * Check if a given object implements the TokenPriceConfig interface.
 */
export function instanceOfTokenPriceConfig(value: object): value is TokenPriceConfig {
    if (!('usageBy' in value) || value['usageBy'] === undefined) return false;
    if (!('tokenPrice' in value) || value['tokenPrice'] === undefined) return false;
    if (!('unitSize' in value) || value['unitSize'] === undefined) return false;
    if (!('minimumUnits' in value) || value['minimumUnits'] === undefined) return false;
    return true;
}

export function TokenPriceConfigFromJSON(json: any): TokenPriceConfig {
    return TokenPriceConfigFromJSONTyped(json, false);
}

export function TokenPriceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPriceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'usageBy': TokenUsageCalculationModeFromJSON(json['usage_by']),
        'tokenPrice': json['token_price'],
        'unitSize': json['unit_size'],
        'minimumUnits': json['minimum_units'],
    };
}

  export function TokenPriceConfigToJSON(json: any): TokenPriceConfig {
      return TokenPriceConfigToJSONTyped(json, false);
  }

  export function TokenPriceConfigToJSONTyped(value?: TokenPriceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usage_by': TokenUsageCalculationModeToJSON(value['usageBy']),
        'token_price': value['tokenPrice'],
        'unit_size': value['unitSize'],
        'minimum_units': value['minimumUnits'],
    };
}

