/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TokenUsageCalculationMode = {
    Fixed: 'fixed',
    UnitCount: 'unit_count',
    Duration: 'duration'
} as const;
export type TokenUsageCalculationMode = typeof TokenUsageCalculationMode[keyof typeof TokenUsageCalculationMode];


export function instanceOfTokenUsageCalculationMode(value: any): boolean {
    for (const key in TokenUsageCalculationMode) {
        if (Object.prototype.hasOwnProperty.call(TokenUsageCalculationMode, key)) {
            if (TokenUsageCalculationMode[key as keyof typeof TokenUsageCalculationMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TokenUsageCalculationModeFromJSON(json: any): TokenUsageCalculationMode {
    return TokenUsageCalculationModeFromJSONTyped(json, false);
}

export function TokenUsageCalculationModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenUsageCalculationMode {
    return json as TokenUsageCalculationMode;
}

export function TokenUsageCalculationModeToJSON(value?: TokenUsageCalculationMode | null): any {
    return value as any;
}

export function TokenUsageCalculationModeToJSONTyped(value: any, ignoreDiscriminator: boolean): TokenUsageCalculationMode {
    return value as TokenUsageCalculationMode;
}

