/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversionEvent } from './ConversionEvent';
import {
    ConversionEventFromJSON,
    ConversionEventFromJSONTyped,
    ConversionEventToJSON,
    ConversionEventToJSONTyped,
} from './ConversionEvent';

/**
 * 
 * @export
 * @interface TrackConversionEventRequest
 */
export interface TrackConversionEventRequest {
    /**
     * 
     * @type {ConversionEvent}
     * @memberof TrackConversionEventRequest
     */
    event: ConversionEvent;
}



/**
 * Check if a given object implements the TrackConversionEventRequest interface.
 */
export function instanceOfTrackConversionEventRequest(value: object): value is TrackConversionEventRequest {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function TrackConversionEventRequestFromJSON(json: any): TrackConversionEventRequest {
    return TrackConversionEventRequestFromJSONTyped(json, false);
}

export function TrackConversionEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackConversionEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event': ConversionEventFromJSON(json['event']),
    };
}

  export function TrackConversionEventRequestToJSON(json: any): TrackConversionEventRequest {
      return TrackConversionEventRequestToJSONTyped(json, false);
  }

  export function TrackConversionEventRequestToJSONTyped(value?: TrackConversionEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': ConversionEventToJSON(value['event']),
    };
}

