/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackConversionEventResponse
 */
export interface TrackConversionEventResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TrackConversionEventResponse
     */
    sent: boolean;
}

/**
 * Check if a given object implements the TrackConversionEventResponse interface.
 */
export function instanceOfTrackConversionEventResponse(value: object): value is TrackConversionEventResponse {
    if (!('sent' in value) || value['sent'] === undefined) return false;
    return true;
}

export function TrackConversionEventResponseFromJSON(json: any): TrackConversionEventResponse {
    return TrackConversionEventResponseFromJSONTyped(json, false);
}

export function TrackConversionEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackConversionEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sent': json['sent'],
    };
}

  export function TrackConversionEventResponseToJSON(json: any): TrackConversionEventResponse {
      return TrackConversionEventResponseToJSONTyped(json, false);
  }

  export function TrackConversionEventResponseToJSONTyped(value?: TrackConversionEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sent': value['sent'],
    };
}

