/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGalleryFolderRequest
 */
export interface UpdateGalleryFolderRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateGalleryFolderRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateGalleryFolderRequest
     */
    color?: string | null;
}

/**
 * Check if a given object implements the UpdateGalleryFolderRequest interface.
 */
export function instanceOfUpdateGalleryFolderRequest(value: object): value is UpdateGalleryFolderRequest {
    return true;
}

export function UpdateGalleryFolderRequestFromJSON(json: any): UpdateGalleryFolderRequest {
    return UpdateGalleryFolderRequestFromJSONTyped(json, false);
}

export function UpdateGalleryFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGalleryFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

  export function UpdateGalleryFolderRequestToJSON(json: any): UpdateGalleryFolderRequest {
      return UpdateGalleryFolderRequestToJSONTyped(json, false);
  }

  export function UpdateGalleryFolderRequestToJSONTyped(value?: UpdateGalleryFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
    };
}

