/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PreferenceOption } from './PreferenceOption';
import {
    PreferenceOptionFromJSON,
    PreferenceOptionFromJSONTyped,
    PreferenceOptionToJSON,
    PreferenceOptionToJSONTyped,
} from './PreferenceOption';

/**
 * 
 * @export
 * @interface UserPreferenceTaxonomyResponse
 */
export interface UserPreferenceTaxonomyResponse {
    /**
     * 
     * @type {Array<PreferenceOption>}
     * @memberof UserPreferenceTaxonomyResponse
     */
    contentStyles: Array<PreferenceOption>;
    /**
     * 
     * @type {Array<PreferenceOption>}
     * @memberof UserPreferenceTaxonomyResponse
     */
    contentGenders: Array<PreferenceOption>;
    /**
     * 
     * @type {Array<PreferenceOption>}
     * @memberof UserPreferenceTaxonomyResponse
     */
    orientations: Array<PreferenceOption>;
    /**
     * 
     * @type {Array<PreferenceOption>}
     * @memberof UserPreferenceTaxonomyResponse
     */
    pronouns: Array<PreferenceOption>;
}

/**
 * Check if a given object implements the UserPreferenceTaxonomyResponse interface.
 */
export function instanceOfUserPreferenceTaxonomyResponse(value: object): value is UserPreferenceTaxonomyResponse {
    if (!('contentStyles' in value) || value['contentStyles'] === undefined) return false;
    if (!('contentGenders' in value) || value['contentGenders'] === undefined) return false;
    if (!('orientations' in value) || value['orientations'] === undefined) return false;
    if (!('pronouns' in value) || value['pronouns'] === undefined) return false;
    return true;
}

export function UserPreferenceTaxonomyResponseFromJSON(json: any): UserPreferenceTaxonomyResponse {
    return UserPreferenceTaxonomyResponseFromJSONTyped(json, false);
}

export function UserPreferenceTaxonomyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferenceTaxonomyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'contentStyles': ((json['content_styles'] as Array<any>).map(PreferenceOptionFromJSON)),
        'contentGenders': ((json['content_genders'] as Array<any>).map(PreferenceOptionFromJSON)),
        'orientations': ((json['orientations'] as Array<any>).map(PreferenceOptionFromJSON)),
        'pronouns': ((json['pronouns'] as Array<any>).map(PreferenceOptionFromJSON)),
    };
}

  export function UserPreferenceTaxonomyResponseToJSON(json: any): UserPreferenceTaxonomyResponse {
      return UserPreferenceTaxonomyResponseToJSONTyped(json, false);
  }

  export function UserPreferenceTaxonomyResponseToJSONTyped(value?: UserPreferenceTaxonomyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_styles': ((value['contentStyles'] as Array<any>).map(PreferenceOptionToJSON)),
        'content_genders': ((value['contentGenders'] as Array<any>).map(PreferenceOptionToJSON)),
        'orientations': ((value['orientations'] as Array<any>).map(PreferenceOptionToJSON)),
        'pronouns': ((value['pronouns'] as Array<any>).map(PreferenceOptionToJSON)),
    };
}

