/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserJourneyEventType = {
    Conversation: 'conversation',
    Transaction: 'transaction',
    GeneratedImage: 'generated_image',
    GeneratedVideo: 'generated_video',
    WatchedStory: 'watched_story',
    Chatbot: 'chatbot'
} as const;
export type UserJourneyEventType = typeof UserJourneyEventType[keyof typeof UserJourneyEventType];


export function instanceOfUserJourneyEventType(value: any): boolean {
    for (const key in UserJourneyEventType) {
        if (Object.prototype.hasOwnProperty.call(UserJourneyEventType, key)) {
            if (UserJourneyEventType[key as keyof typeof UserJourneyEventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserJourneyEventTypeFromJSON(json: any): UserJourneyEventType {
    return UserJourneyEventTypeFromJSONTyped(json, false);
}

export function UserJourneyEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJourneyEventType {
    return json as UserJourneyEventType;
}

export function UserJourneyEventTypeToJSON(value?: UserJourneyEventType | null): any {
    return value as any;
}

export function UserJourneyEventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): UserJourneyEventType {
    return value as UserJourneyEventType;
}

