/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The lengths a model offers, described both ways at once.
 * 
 * `kind` says which control to render: `choices` is a short list of discrete lengths, `range` is every second
 * between the bounds and suits a slider. Both representations are always populated, so a client can render from
 * `kind` and still validate a picked length against `values`.
 * @export
 * @interface VideoDurationOptions
 */
export interface VideoDurationOptions {
    /**
     * 
     * @type {string}
     * @memberof VideoDurationOptions
     */
    kind: VideoDurationOptionsKindEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof VideoDurationOptions
     */
    values: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof VideoDurationOptions
     */
    minSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof VideoDurationOptions
     */
    maxSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof VideoDurationOptions
     */
    stepSeconds?: number;
}


/**
 * @export
 */
export const VideoDurationOptionsKindEnum = {
    Choices: 'choices',
    Range: 'range'
} as const;
export type VideoDurationOptionsKindEnum = typeof VideoDurationOptionsKindEnum[keyof typeof VideoDurationOptionsKindEnum];


/**
 * Check if a given object implements the VideoDurationOptions interface.
 */
export function instanceOfVideoDurationOptions(value: object): value is VideoDurationOptions {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('minSeconds' in value) || value['minSeconds'] === undefined) return false;
    if (!('maxSeconds' in value) || value['maxSeconds'] === undefined) return false;
    return true;
}

export function VideoDurationOptionsFromJSON(json: any): VideoDurationOptions {
    return VideoDurationOptionsFromJSONTyped(json, false);
}

export function VideoDurationOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoDurationOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'values': json['values'],
        'minSeconds': json['min_seconds'],
        'maxSeconds': json['max_seconds'],
        'stepSeconds': json['step_seconds'] == null ? undefined : json['step_seconds'],
    };
}

  export function VideoDurationOptionsToJSON(json: any): VideoDurationOptions {
      return VideoDurationOptionsToJSONTyped(json, false);
  }

  export function VideoDurationOptionsToJSONTyped(value?: VideoDurationOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'values': value['values'],
        'min_seconds': value['minSeconds'],
        'max_seconds': value['maxSeconds'],
        'step_seconds': value['stepSeconds'],
    };
}

