/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoMergeResult
 */
export interface VideoMergeResult {
    /**
     * 
     * @type {boolean}
     * @memberof VideoMergeResult
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof VideoMergeResult
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoMergeResult
     */
    width?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoMergeResult
     */
    height?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoMergeResult
     */
    hasAudio?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof VideoMergeResult
     */
    outputBytes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoMergeResult
     */
    callbackToken?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof VideoMergeResult
     */
    context?: { [key: string]: any; };
}

/**
 * Check if a given object implements the VideoMergeResult interface.
 */
export function instanceOfVideoMergeResult(value: object): value is VideoMergeResult {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function VideoMergeResultFromJSON(json: any): VideoMergeResult {
    return VideoMergeResultFromJSONTyped(json, false);
}

export function VideoMergeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoMergeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'hasAudio': json['has_audio'] == null ? undefined : json['has_audio'],
        'outputBytes': json['output_bytes'] == null ? undefined : json['output_bytes'],
        'callbackToken': json['callback_token'] == null ? undefined : json['callback_token'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

  export function VideoMergeResultToJSON(json: any): VideoMergeResult {
      return VideoMergeResultToJSONTyped(json, false);
  }

  export function VideoMergeResultToJSONTyped(value?: VideoMergeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'width': value['width'],
        'height': value['height'],
        'has_audio': value['hasAudio'],
        'output_bytes': value['outputBytes'],
        'callback_token': value['callbackToken'],
        'context': value['context'],
    };
}

