/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Videos
 */
export interface Videos {
}

/**
 * Check if a given object implements the Videos interface.
 */
export function instanceOfVideos(value: object): value is Videos {
    return true;
}

export function VideosFromJSON(json: any): Videos {
    return VideosFromJSONTyped(json, false);
}

export function VideosFromJSONTyped(json: any, ignoreDiscriminator: boolean): Videos {
    return json;
}

  export function VideosToJSON(json: any): Videos {
      return VideosToJSONTyped(json, false);
  }

  export function VideosToJSONTyped(value?: Videos | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

