/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoContent
 */
export interface VideoContent {
    /**
     * 
     * @type {string}
     * @memberof VideoContent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VideoContent
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof VideoContent
     */
    width?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoContent
     */
    height?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoContent
     */
    generationId: string;
    /**
     * 
     * @type {string}
     * @memberof VideoContent
     */
    originalImageId: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoContent
     */
    originalImageUrl: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoContent
     */
    durationSeconds?: number | null;
}

/**
 * Check if a given object implements the VideoContent interface.
 */
export function instanceOfVideoContent(value: object): value is VideoContent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('generationId' in value) || value['generationId'] === undefined) return false;
    if (!('originalImageId' in value) || value['originalImageId'] === undefined) return false;
    if (!('originalImageUrl' in value) || value['originalImageUrl'] === undefined) return false;
    return true;
}

export function VideoContentFromJSON(json: any): VideoContent {
    return VideoContentFromJSONTyped(json, false);
}

export function VideoContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoContent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'generationId': json['generation_id'],
        'originalImageId': json['original_image_id'],
        'originalImageUrl': json['original_image_url'],
        'durationSeconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
    };
}

  export function VideoContentToJSON(json: any): VideoContent {
      return VideoContentToJSONTyped(json, false);
  }

  export function VideoContentToJSONTyped(value?: VideoContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'width': value['width'],
        'height': value['height'],
        'generation_id': value['generationId'],
        'original_image_id': value['originalImageId'],
        'original_image_url': value['originalImageUrl'],
        'duration_seconds': value['durationSeconds'],
    };
}

