/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoLoraName = {
    PovInsertion: 'pov_insertion',
    FacialsV2: 'facials_v2',
    CumInMouth: 'cum_in_mouth',
    AnimeCumshotHair: 'anime_cumshot_hair',
    AnimeFacials: 'anime_facials',
    AnimeCumshotMouth: 'anime_cumshot_mouth',
    AnimeCumshotTongue: 'anime_cumshot_tongue',
    AnimeCumshot: 'anime_cumshot',
    MouthfullCumshot: 'mouthfull_cumshot',
    BreastExpansion: 'breast_expansion',
    Cunnilingus: 'cunnilingus',
    Airblowjob: 'airblowjob',
    DildoHandjob: 'dildo_handjob',
    BreastPlayGrabbingSolo: 'breast_play_grabbing_solo',
    BreastPlayGrabbingMan: 'breast_play_grabbing_man',
    BreastPlayCoverSolo: 'breast_play_cover_solo',
    BreastPlayRubSolo: 'breast_play_rub_solo',
    BreastPlayNipplePinch: 'breast_play_nipple_pinch',
    BreastPlay: 'breast_play',
    PovIntimateContact: 'pov_intimate_contact',
    TwerkV2: 'twerk_v2',
    HandjobBlowjob: 'handjob_blowjob',
    StomachBulgeV2: 'stomach_bulge_v2',
    BigSplash: 'big_splash',
    FingeringV2: 'fingering_v2',
    FaceToFeet: 'face_to_feet',
    Meatspin: 'meatspin',
    TentaclesV2: 'tentacles_v2',
    FutaMasturbationCumshot: 'futa_masturbation_cumshot',
    MatingPress: 'mating_press',
    FootjobV2: 'footjob_v2',
    FutaSoloToSex: 'futa_solo_to_sex',
    OrgasmFace: 'orgasm_face',
    OrgasmBodyShake: 'orgasm_body_shake',
    FootWorshipSucking: 'foot_worship_sucking',
    JoiHandGesture: 'joi_hand_gesture',
    PenisAndBreastsSizeController: 'penis_and_breasts_size_controller',
    FrenchKiss: 'french_kiss',
    Creampie: 'creampie',
    PovTittyFuck: 'pov_titty_fuck',
    PovKissing: 'pov_kissing',
    DildoPenetration: 'dildo_penetration',
    SexyMoves: 'sexy_moves',
    DeepthroatFaceFuck: 'deepthroat_face_fuck',
    SmoothAnimation: 'smooth_animation',
    PovPulloutCumshotNoTouching: 'pov_pullout_cumshot_no_touching',
    PovPulloutCumshotManFinishes: 'pov_pullout_cumshot_man_finishes',
    PovPulloutCumshotFemaleFinishes: 'pov_pullout_cumshot_female_finishes',
    AhegaoDroolingWithMiddlefinger: 'ahegao_drooling_with_middlefinger',
    PenisInsert: 'penis_insert',
    SelfNippleSucking: 'self_nipple_sucking',
    CumhaterFacial: 'cumhater_facial',
    FurryEnhancer: 'furry_enhancer',
    Pronebone: 'pronebone',
    GaggingDisgustedExpression: 'gagging_disgusted_expression',
    FootjobSockjobShoejob: 'footjob_sockjob_shoejob',
    BodyGrowth: 'body_growth',
    BodyGrowthClothesRipoff: 'body_growth_clothes_ripoff',
    AnimeXrayCreampie: 'anime_xray_creampie',
    TongueOut: 'tongue_out',
    Rimjob: 'rimjob',
    BoobBounceV2: 'boob_bounce_v2',
    TakerPovBlowjob: 'taker_pov_blowjob',
    SpitToCamera: 'spit_to_camera',
    RunningBoobBounce: 'running_boob_bounce',
    SplitTongue: 'split_tongue',
    ThunderGodEyes: 'thunder_god_eyes',
    OralPenisInsertion: 'oral_penis_insertion',
    FaceToFeetAlternative: 'face_to_feet_alternative',
    Deepthroat: 'deepthroat',
    ImpliedBlowjob: 'implied_blowjob',
    MissionaryV2: 'missionary_v2',
    DoggystyleV2: 'doggystyle_v2',
    CowgirlV2: 'cowgirl_v2',
    BlowjobV2: 'blowjob_v2',
    ReverseCowgirl: 'reverse_cowgirl',
    DoubleBlowjob: 'double_blowjob',
    GeneralSexPoses: 'general_sex_poses',
    SeriesOfCumshots: 'series_of_cumshots',
    Bukkake: 'bukkake',
    FaceDownAssUp: 'face_down_ass_up',
    HandjobV2: 'handjob_v2',
    HandjobDoublehand: 'handjob_doublehand',
    DildoRide: 'dildo_ride',
    Anal: 'anal',
    FemaleSquirt: 'female_squirt',
    Ahegao: 'ahegao',
    Bondage: 'bondage',
    Dancing: 'dancing',
    Spanking: 'spanking',
    FemaleMasturbation: 'female_masturbation',
    PovDoggyStyle: 'pov_doggy_style',
    Blowjob: 'blowjob',
    PovMissionary: 'pov_missionary',
    PovCowgirl: 'pov_cowgirl',
    TittyFuck: 'titty_fuck',
    FemaleGenitalsHelpter: 'female_genitals_helpter',
    Fingering: 'fingering',
    PovDoggyStyle2: 'pov_doggy_style2',
    Handjob: 'handjob',
    BoobGrab: 'boob_grab',
    FootJob: 'foot_job',
    Tentacles: 'tentacles',
    StomachBulge: 'stomach_bulge',
    PovFuttaFelatio: 'pov_futta_felatio',
    FutanariMasturbation: 'futanari_masturbation',
    BoobsBounce: 'boobs_bounce',
    Penis: 'penis',
    Cumshot: 'cumshot',
    Twerk: 'twerk',
    Facials: 'facials',
    FaceFuck: 'face_fuck',
    BoobsJiggling: 'boobs_jiggling',
    H3Fingering: 'h3_fingering',
    H3HandInPanties: 'h3_hand_in_panties',
    H3MasturbationSquirting: 'h3_masturbation_squirting',
    H3VibratorSquirting: 'h3_vibrator_squirting',
    H3MagicWand: 'h3_magic_wand',
    H3DildoMasturbation: 'h3_dildo_masturbation',
    H3SexMachine: 'h3_sex_machine',
    H3SybianRide: 'h3_sybian_ride',
    H3PillowHumping: 'h3_pillow_humping',
    H3PussySpread: 'h3_pussy_spread',
    H3OrgasmContractions: 'h3_orgasm_contractions',
    H3BreastPlay: 'h3_breast_play',
    H3BreastCaress: 'h3_breast_caress',
    H3NipplePlay: 'h3_nipple_play',
    H3BouncingBoobs: 'h3_bouncing_boobs',
    H3HeavyBreastBounce: 'h3_heavy_breast_bounce',
    H3BreastJiggle: 'h3_breast_jiggle',
    H3JiggleWalk: 'h3_jiggle_walk',
    H3StrutWalk: 'h3_strut_walk',
    H3Twerk: 'h3_twerk',
    H3HipSwayDance: 'h3_hip_sway_dance',
    H3HipGyration: 'h3_hip_gyration',
    H3Blowjob: 'h3_blowjob',
    H3OralSex: 'h3_oral_sex',
    H3Deepthroat: 'h3_deepthroat',
    H3PovDeepthroat: 'h3_pov_deepthroat',
    H3SideViewDeepthroat: 'h3_side_view_deepthroat',
    H3FaceFuck: 'h3_face_fuck',
    H3LickingPenisBalls: 'h3_licking_penis_balls',
    H3CockWorship: 'h3_cock_worship',
    H3CockFaceSlap: 'h3_cock_face_slap',
    H3Titfuck: 'h3_titfuck',
    H3Footjob: 'h3_footjob',
    H3PussyGrinding: 'h3_pussy_grinding',
    H3HeJerksOff: 'h3_he_jerks_off',
    H3LesbianPussyLicking: 'h3_lesbian_pussy_licking',
    H3LesbianScissoring: 'h3_lesbian_scissoring',
    H3PassionateKissing: 'h3_passionate_kissing',
    H3MissionaryPov: 'h3_missionary_pov',
    H3PovPenisInsertion: 'h3_pov_penis_insertion',
    H3PovMissionaryDoggy: 'h3_pov_missionary_doggy',
    H3DoggyStyle: 'h3_doggy_style',
    H3DoggyStylePov: 'h3_doggy_style_pov',
    H3DoggyStyleLegUp: 'h3_doggy_style_leg_up',
    H3Cowgirl: 'h3_cowgirl',
    H3CowgirlFromBehind: 'h3_cowgirl_from_behind',
    H3CowgirlSideView: 'h3_cowgirl_side_view',
    H3RidingPov: 'h3_riding_pov',
    H3GrindingOnTop: 'h3_grinding_on_top',
    H3FasterHarder: 'h3_faster_harder',
    H3StomachBulge: 'h3_stomach_bulge',
    H3ThumbInButt: 'h3_thumb_in_butt',
    H3Pegging: 'h3_pegging',
    H3BreastExpansion: 'h3_breast_expansion',
    H3BreastShrinking: 'h3_breast_shrinking',
    H3BodyThickening: 'h3_body_thickening',
    H3FutaTransformation: 'h3_futa_transformation',
    H3FutaReveal: 'h3_futa_reveal',
    H3FutaMasturbationCumshot: 'h3_futa_masturbation_cumshot',
    H3RopeBondage: 'h3_rope_bondage',
    H3Hogtie: 'h3_hogtie',
    H3Spanking: 'h3_spanking',
    H3Whipping: 'h3_whipping',
    H3BallKicking: 'h3_ball_kicking',
    H3Lipples: 'h3_lipples',
    H3Upskirt: 'h3_upskirt',
    H3Cameltoe: 'h3_cameltoe',
    H3Cumshot: 'h3_cumshot',
    H3FacialCumshot: 'h3_facial_cumshot',
    H3HugeCumshot: 'h3_huge_cumshot',
    H3CumshotInHair: 'h3_cumshot_in_hair',
    H3CumSwallow: 'h3_cum_swallow',
    H3CumInsideThrobbing: 'h3_cum_inside_throbbing',
    H3AhegaoFace: 'h3_ahegao_face',
    H3PleasureMoans: 'h3_pleasure_moans',
    H3Whispering: 'h3_whispering',
    H3AsmrWhisper: 'h3_asmr_whisper',
    H3NaturalSpeech: 'h3_natural_speech',
    H3MalePov: 'h3_male_pov',
    H3FemalePov: 'h3_female_pov',
    H3CinematicLook: 'h3_cinematic_look',
    H3SocialVideoLook: 'h3_social_video_look',
    H3MotionStabilizer: 'h3_motion_stabilizer',
    H3FightScene: 'h3_fight_scene',
    H3WeaponCombat: 'h3_weapon_combat',
    H3AnimeMotion: 'h3_anime_motion'
} as const;
export type VideoLoraName = typeof VideoLoraName[keyof typeof VideoLoraName];


export function instanceOfVideoLoraName(value: any): boolean {
    for (const key in VideoLoraName) {
        if (Object.prototype.hasOwnProperty.call(VideoLoraName, key)) {
            if (VideoLoraName[key as keyof typeof VideoLoraName] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoLoraNameFromJSON(json: any): VideoLoraName {
    return VideoLoraNameFromJSONTyped(json, false);
}

export function VideoLoraNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoLoraName {
    return json as VideoLoraName;
}

export function VideoLoraNameToJSON(value?: VideoLoraName | null): any {
    return value as any;
}

export function VideoLoraNameToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoLoraName {
    return value as VideoLoraName;
}

