/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoQualityConfig
 */
export interface VideoQualityConfig {
    /**
     * 
     * @type {string}
     * @memberof VideoQualityConfig
     */
    resolution: VideoQualityConfigResolutionEnum;
    /**
     * 
     * @type {number}
     * @memberof VideoQualityConfig
     */
    tokenCostPerSecond: number;
}


/**
 * @export
 */
export const VideoQualityConfigResolutionEnum = {
    P480: 'P480',
    P720: 'P720',
    P1080: 'P1080',
    P1440: 'P1440',
    P2160: 'P2160'
} as const;
export type VideoQualityConfigResolutionEnum = typeof VideoQualityConfigResolutionEnum[keyof typeof VideoQualityConfigResolutionEnum];


/**
 * Check if a given object implements the VideoQualityConfig interface.
 */
export function instanceOfVideoQualityConfig(value: object): value is VideoQualityConfig {
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('tokenCostPerSecond' in value) || value['tokenCostPerSecond'] === undefined) return false;
    return true;
}

export function VideoQualityConfigFromJSON(json: any): VideoQualityConfig {
    return VideoQualityConfigFromJSONTyped(json, false);
}

export function VideoQualityConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoQualityConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'resolution': json['resolution'],
        'tokenCostPerSecond': json['token_cost_per_second'],
    };
}

  export function VideoQualityConfigToJSON(json: any): VideoQualityConfig {
      return VideoQualityConfigToJSONTyped(json, false);
  }

  export function VideoQualityConfigToJSONTyped(value?: VideoQualityConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resolution': value['resolution'],
        'token_cost_per_second': value['tokenCostPerSecond'],
    };
}

